### ISSUE TITLE
httplib2.ServerNotFoundError: Unable to find the server at www.googleapis.com

### ISSUE THREAD

**Issue by gdreelin** [sabeechen/hassio-google-drive-backup#18] opened 2019-04-12 20:08 UTC
I have been getting this error but it did upload once without issues.

Traceback (most recent call last):
  File "/app/backup/engine.py", line 94, in doBackupWorkflow
    self._checkForBackup()
  File "/app/backup/engine.py", line 300, in _checkForBackup
    self._syncSnapshots()
  File "/app/backup/engine.py", line 238, in _syncSnapshots
    self.folder_id = self.drive.getFolderId()
  File "/app/backup/drive.py", line 170, in getFolderId
    folder = self._retryDriveServiceCall(self._drive().files().get(fileId=folder_id, fields='id,trashed,capabilities'))
  File "/app/backup/drive.py", line 64, in _drive
    return build(DRIVE_SERVICE, DRIVE_VERSION, credentials=self.creds)
  File "/usr/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/googleapiclient/discovery.py", line 224, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey)
  File "/usr/lib/python3.6/site-packages/googleapiclient/discovery.py", line 274, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 1926, in request
    cachekey,
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 1595, in _request
    conn, request_uri, method, body, headers
  File "/usr/lib/python3.6/site-packages/httplib2/__init__.py", line 1508, in _conn_request
    raise ServerNotFoundError("Unable to find the server at %s" % conn.host)
httplib2.ServerNotFoundError: Unable to find the server at www.googleapis.com

**Comment by sabeechen** [comment] 2019-04-12 23:45
You're the second person to make a bug for this, so I'd presume a lot of folks are running into this.  I've never seen it in any of my development and I'd like to get to the bottom of it.  The error indicates that the add-on can't find the google api server used to make calls to Google Drive.  In that sense fixing it is kind of out of my hands but it would be great if I could provide an error message that gives some probable causes when people run into it.

Do you have anything strange going on with your network configuration at home? Anything like custom DNS servers, network-wide ad-blocking (pi-hole for example), etc.  These might be inadvertently identifying the add-on traffic as spam.

Some normal debugging applies:
* Try clicking the "Sync Snapshots" button, and see if the error persists after a few seconds
* Restart the add-on, see if it persists
* Restart hass.io (not just home assistant) and see if it persists

**Comment by sabeechen** [comment] 2019-04-17 07:08
I tried installing pi-hole on my instance but didn't run into any errors with DNS blocking (at least not after an hour or two) but I'll leave it running overnight to see if something comes up.

I randomly stumbled into [this issue](https://github.com/home-assistant/hassio/issues/305), which present similarly to what you're seeing.  It suggest that giving your Home Assistance instance a static IP might fix the problem, or that your router might be using a stale DNS server.

**Comment by sabeechen** [comment] 2019-04-17 16:02
Duplicate of #15

**Closed by sabeechen** 2019-04-17 16:02 UTC
Labels: duplicate
