### ISSUE TITLE
Read only file error.

### ISSUE THREAD

**Issue by Alvaro-MG31** [sabeechen/hassio-google-drive-backup#445] opened 2021-08-17 19:25 UTC
I've run into this error a few times now. It completely frozes my HA installation to the point that it dissapears on unraid and later on appears without doing anything. 

 Addon version: `0.104.3`
 Home Assistant Version: `2021.8.7`
 Supervisor Version: `2021.06.8`
 Supervisor Channel: `stable`
 Hassos Version: `6.2`
 Docker Version: `20.10.6`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2021-08-17T19:21:46.831393+00:00`
 Timezone: `Europe/Madrid`
 Failure Time: `2021-08-17T19:12:40.089476+00:00`
 Last Good Sync: `2021-08-17T19:12:39.088038+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:210 (sync)
  addon/backup/util/data_cache.py:98 (saveIfDirty)
  addon/backup/util/data_cache.py:69 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 2,
        "retained": 0,
        "deletable": 2,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2021-07-26T18:38:20Z",
        "max": 1,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "1.7 MB",
        "ignored_size": "0.0 B",
        "free_space": "23.9 GB"
    },
    "GoogleDrive": {
        "snapshots": 6,
        "retained": 2,
        "deletable": 4,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2021-08-17T01:45:01Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "119.6 MB",
        "ignored_size": "0.0 B",
        "free_space": "3.5 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_HASSIO": 1,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 1.0,
    "Setting.SNAPSHOT_TIME_OF_DAY": "03:45",
    "Setting.DELETE_AFTER_UPLOAD": true,
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 08-17 18:29:55 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271NQfH4XqEchNT1s92rRKjZ8pcvjDCijRx%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-17 18:29:55 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:210 (sync)
  addon/backup/util/data_cache.py:98 (saveIfDirty)
  addon/backup/util/data_cache.py:69 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

08-17 18:29:55 INFO [backup.model.coordinator] I'll try again in 42(ish) minutes
08-17 19:12:35 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-17 19:12:35 INFO [backup.model.coordinator] Syncing Snapshots
08-17 19:12:35 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-17 19:12:35 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-17 19:12:35 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1NQfH4XqEchNT1s92rRKjZ8pcvjDCijRx/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
08-17 19:12:36 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
08-17 19:12:36 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271NQfH4XqEchNT1s92rRKjZ8pcvjDCijRx%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-17 19:12:36 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:210 (sync)
  addon/backup/util/data_cache.py:98 (saveIfDirty)
  addon/backup/util/data_cache.py:69 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

08-17 19:12:36 INFO [backup.model.coordinator] I'll try again in an hour
08-17 20:12:37 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-17 20:12:37 INFO [backup.model.coordinator] Syncing Snapshots
08-17 20:12:37 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-17 20:12:37 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-17 20:12:37 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1NQfH4XqEchNT1s92rRKjZ8pcvjDCijRx/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
08-17 20:12:37 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
08-17 20:12:38 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271NQfH4XqEchNT1s92rRKjZ8pcvjDCijRx%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-17 20:12:38 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:210 (sync)
  addon/backup/util/data_cache.py:98 (saveIfDirty)
  addon/backup/util/data_cache.py:69 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

08-17 20:12:38 INFO [backup.model.coordinator] I'll try again in an hour
08-17 21:12:39 DEBUG [backup.model.syncer] Sync requested by Coordinator
08-17 21:12:39 INFO [backup.model.coordinator] Syncing Snapshots
08-17 21:12:39 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
08-17 21:12:39 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
08-17 21:12:39 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1NQfH4XqEchNT1s92rRKjZ8pcvjDCijRx/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
08-17 21:12:39 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
08-17 21:12:39 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271NQfH4XqEchNT1s92rRKjZ8pcvjDCijRx%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
08-17 21:12:40 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:210 (sync)
  addon/backup/util/data_cache.py:98 (saveIfDirty)
  addon/backup/util/data_cache.py:69 (save)
OSError: [Errno 30] Read-only file system: '/data/data_cache.json'

08-17 21:12:40 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m21-08-17 16:39:15 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m21-08-17 16:39:15 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m21-08-17 16:41:13 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-08-17 16:47:14 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-17 17:11:13 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-08-17 17:39:15 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m21-08-17 17:39:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[32m21-08-17 17:39:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m21-08-17 17:39:15 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m21-08-17 17:39:15 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m21-08-17 17:39:15 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m21-08-17 17:39:15 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m21-08-17 17:39:15 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m21-08-17 17:39:15 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m21-08-17 17:40:44 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m21-08-17 17:41:13 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-08-17 17:41:20 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository[0m
[32m21-08-17 17:41:20 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository[0m
[32m21-08-17 17:41:20 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m21-08-17 17:41:23 INFO (MainThread) [supervisor.store] Loading add-ons from store: 63 all - 0 new - 0 remove[0m
[32m21-08-17 17:41:23 INFO (MainThread) [supervisor.store] Loading add-ons from store: 63 all - 0 new - 0 remove[0m
[32m21-08-17 17:47:16 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-17 17:47:17 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-17 17:47:28 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-17 17:47:48 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-17 17:48:29 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-17 17:49:50 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-17 17:52:31 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-08-17 17:57:52 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     self._target(*self._args, **self._kwargs)
Message: 'Error in database connectivity during commit: Error executing query: (sqlite3.OperationalError) disk I/O error\n(Background on this error at: http://sqlalche.me/e/14/e3q8). (retrying in 3 seconds)'
Arguments: None
[31m2021-08-17 18:07:19 ERROR (Recorder) [homeassistant.components.recorder] SQLAlchemyError error processing event <Event time_changed[L]: now=2021-08-17T16:07:16.000580+00:00>: This connection is on an inactive transaction.  Please rollback() fully before proceeding. (Background on this error at: http://sqlalche.me/e/14/8s2a)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 632, in _process_one_event_or_recover
    self._process_one_event(event)
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 752, in _process_one_event
    self._commit_event_session_or_retry()
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 815, in _commit_event_session_or_retry
    self._commit_event_session()
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 841, in _commit_event_session
    self.event_session.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 836, in commit
    trans.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2330, in commit
    self._do_commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2529, in _do_commit
    self.connection._invalid_transaction()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 544, in _invalid_transaction
    raise exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This connection is on an inactive transaction.  Please rollback() fully before proceeding. (Background on this error at: http://sqlalche.me/e/14/8s2a)[0m
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1087, in emit
    self.flush()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1067, in flush

 ```

**Comment by sabeechen** [comment] 2021-08-18 03:18
This is an unusual error.  I will be upfront in saying that I don't believe the addon is the cause, and instead is just sufferring from the underlying issue.  Regardless, here is everything that I can tell based on my experience as an addon developer and also a user of Home Assistant given the debug information you've provided me.

- Home assistant creates the environment that the addon runs in, especially the /data directory that its having trouble writing to.  An error writing in this directory indicates there is something wrong with either Home Assistant or the underlying file system.
- Your home assistant log also indicates that its having trouble writing to the filesystem (thats the disk I/O error).  I suspect that anything trying to write to the file system during this time is having trouble, and its likely the reason HA becomes unresponsive/unavailable.  Because the addon runs in its own isolated and low-permissions docker container, it shouldn't be capable of causing a problem this severe.
- I've seen this issue come up from a few users ([see this search](https://github.com/sabeechen/hassio-google-drive-backup/issues?q=%22Read-only+file+system%22)).  In the past it has been fixed by restarting the machine.  I have seen it caused by:
  - A faulty or unreliable usb hard drive
  - Sometimes the OS (linux) will switch a file system into read-only mode if it thinks there is a problem with it in order to prevent furthur damage.   What exactly is a problem could be any number of things (eg bad sectors).

I'm not familiar with un-raid, but if it keeps any logs of errors I'd start looking there.  [This looks promising](https://wiki.unraid.net/Manual/Troubleshooting#System_Diagnostics).  If you have access to the host file system it may be useful to look at the system's logs as well.

**Comment by sabeechen** [comment] 2021-09-07 19:17
I'm going to close this issue for now, but please feel free to re-open it if you think there is something else I can help with.

**Closed by sabeechen** 2021-09-07 19:17 UTC
