### ISSUE TITLE
googleapiclient.errors.ResumableUploadError: <HttpError 400 "Invalid value for: Invalid format: "2019-03-29T12:15:36" is too short">

### ISSUE THREAD

**Issue by M203** [sabeechen/hassio-google-drive-backup#7] opened 2019-03-29 11:18 UTC
Ran first backup. Below appeared. Backup seems to have gone through completely though.  Marked as backed up in add-on.

Traceback (most recent call last):
  File "/app/backup/engine.py", line 90, in doBackupWorkflow
    self._checkForBackup()
  File "/app/backup/engine.py", line 263, in _checkForBackup
    self.drive.saveSnapshot(to_backup, self.hassio.downloadUrl(to_backup), self.folder_id)
  File "/app/backup/drive.py", line 130, in saveSnapshot
    status2, response = self._retryDriveServiceCall(request, func = lambda a : a.next_chunk())
  File "/app/backup/drive.py", line 182, in _retryDriveServiceCall
    raise e
  File "/app/backup/drive.py", line 172, in _retryDriveServiceCall
    return func(request)
  File "/app/backup/drive.py", line 130, in <lambda>
    status2, response = self._retryDriveServiceCall(request, func = lambda a : a.next_chunk())
  File "/usr/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/googleapiclient/http.py", line 927, in next_chunk
    raise ResumableUploadError(resp, content)
googleapiclient.errors.ResumableUploadError: <HttpError 400 "Invalid value for: Invalid format: "2019-03-29T12:15:36" is too short">

**Comment by sabeechen** [comment] 2019-03-29 23:16
I'm unable to reproduce this on my Home Assistant, but I suspect either your system has a different date format or it truncates the milliseconds part of the date if you just so happen to make a snapshot when the milliseconds=0.  I'm surprised the upload went through.  If you're willign to answer a few questions:
* Does the error stick around after you click the "Sync Now" button on the right?
*  Are you sure the failed upload shows up in your Google Drive folder?

Regardless, I'll make a fix for this next.

**Comment by sabeechen** [comment] 2019-04-01 05:44
I just published a new release that should take care of this error (v0.52),

**Closed by sabeechen** 2019-04-01 05:44 UTC
Labels: bug
