### ISSUE TITLE
Ha Backup fails always sayin 'Can't Connect to Google Drive'

### ISSUE THREAD

**Issue by gbadis** [sabeechen/hassio-google-drive-backup#549] opened 2022-02-15 21:19 UTC
Copy the info from the previous page here

**Comment by sabeechen** [comment] 2022-03-24 15:59
Can you get me a copy of your logs while the problem is happening?  Its easiest if you go to "Actions" > "Report a bug" in the web-ui and copy the information from there.

**Comment by sabeechen** [comment] 2022-05-03 18:33
I'm closing this for now, but please let me know or reopen the issue if you think there is something else you think I can help with.

**Closed by sabeechen** 2022-05-03 18:33 UTC
