### ISSUE TITLE
Cannot delete references to old snapshots or create new snapshot

### ISSUE THREAD

**Issue by dwl99** [sabeechen/hassio-google-drive-backup#117] opened 2019-10-23 21:41 UTC
Similar to #100
I manually deleted some old snapshots but they still show up in the snapshot list with a filesize of zero. If I try to delete them with this add-on I get:
`Traceback (most recent call last):
  File "/app/backup/uiserver.py", line 518, in handleError
    return call()
  File "/app/backup/uiserver.py", line 193, in <lambda>
    return self.handleError(lambda: self._deleteSnapshot(slug, drive, ha))
  File "/app/backup/uiserver.py", line 202, in _deleteSnapshot
    self._coord.delete(sources, slug)
  File "/app/backup/coordinator.py", line 166, in delete
    self._withSoftLock(lambda: self._delete(sources, slug))
  File "/app/backup/coordinator.py", line 210, in _withSoftLock
    return callable()
  File "/app/backup/coordinator.py", line 166, in <lambda>
    self._withSoftLock(lambda: self._delete(sources, slug))
  File "/app/backup/coordinator.py", line 171, in _delete
    self._ensureSource(source).delete(snapshot)
  File "/app/backup/hasource.py", line 198, in delete
    self.harequests.delete(slug)
  File "/app/backup/harequests.py", line 49, in delete
    raise HomeAssistantDeleteError()
backup.exceptions.HomeAssistantDeleteError
`
If I try to create a new snapshot I get:
`Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 102, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 145, in sync
    upload.addSource(self.dest.save(upload, self.source.read(upload)))
  File "/app/backup/hasource.py", line 219, in read
    return self.harequests.download(item.slug())
  File "/app/backup/harequests.py", line 93, in download
    return SeekableRequest(url, self._getHassioHeaders()).prepare()
  File "/app/backup/seekablerequest.py", line 31, in prepare
    self.size()
  File "/app/backup/seekablerequest.py", line 36, in size
    self._size = self._getContentLength()
  File "/app/backup/seekablerequest.py", line 119, in _getContentLength
    f = urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.7/urllib/request.py", line 1320, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
`
Thanks

**Comment by sabeechen** [comment] 2019-10-23 22:50
What version of Hass.io/HA are you running?  I haven't had any success trying to reproduce this on any of my test machines but I'll give it another try if I can get the exact version.  If you still have the Supervisor log from when the snapshots were deleted ("Hass.io" > "System" > "System Log"), that might give some clue as to what caused it too.

I wish I had a better solution to this, but it means that either Hass.io or Home Assistant has gotten into a weird (probably broken) state and is giving the addon bad data.  I assume these "0 byte" snapshots don't appear on the Snapshots page in Hass.io anymore?  Users who previously had this problem had success by:
- Clicking the "refresh" icon at the top right of the "Hass.io" >  "Snapshots" page.  This forces Hass.io to rebuild its snapshot cache.
- Restarting the addon
- Restarting Hass.io
- Restarting the host machine (probably the best option)
- Installing the samba or ssh addon and deleting any 0 byte files (snapshots) in the "/backup" folder.

**Comment by dwl99** [comment] 2019-10-24 06:06
Sorry, I should have mentioned I'm on Hassio 191 running in a Docker container. I got rid of the corrupted snapshots by following your suggestion of refreshing the snapshot cache thanks. I have samba access to the HA folders and the /backup folder is empty. If I try to create a snapshot it runs for a few seconds and thinks it has created one but the files size is only 3.3MB. Will try rebooting my Synology NAS & see what happens.

**Comment by sabeechen** [comment] 2019-10-24 16:37
You might consider opening an issue for it on the [Hass.io issue tracker](https://github.com/home-assistant/hassio/issues).  Glancing at the tracker the only open issue that looks like it might be related to what you're seeing is [this one](https://github.com/home-assistant/hassio/issues/779), but I can't be sure.

I'm closing this issue now, but feel free to reopen it if you think there is more I can help with.

**Closed by sabeechen** 2019-10-24 16:37 UTC
