### ISSUE TITLE
UpdateSnapshotsSensor: Can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by VivantSenior** [sabeechen/hassio-google-drive-backup#87] opened 2019-08-03 11:00 UTC
After updating the addon to version 0.98.1 and having trouble like in [#83](https://github.com/sabeechen/hassio-google-drive-backup/issues/83) I have reinstalled the addon (made appropiate changes to settings as in [my comment](https://github.com/sabeechen/hassio-google-drive-backup/issues/83#issuecomment-517915635) but have found following log:

```
08-03 07:21:32 INFO Snapshot finished
08-03 07:32:36 INFO Backup directory changed
08-03 07:32:36 INFO Syncing Snapshots
08-03 07:32:39 ERROR Trouble updating Home Assistant sensors.
08-03 07:32:39 ERROR 
Traceback (most recent call last):
  File "/app/backup/haupdater.py", line 40, in update
    self._requests.updateSnapshotsSensor(self._state(), self._cache)
  File "/app/backup/harequests.py", line 169, in updateSnapshotsSensor
    last = max(snapshots, key=lambda s: s.date()).date().isoformat()
TypeError: can't compare offset-naive and offset-aware datetimes


08-03 07:33:04 ERROR Trouble updating Home Assistant sensors.
08-03 07:33:04 ERROR 
Traceback (most recent call last):
  File "/app/backup/haupdater.py", line 40, in update
    self._requests.updateSnapshotsSensor(self._state(), self._cache)
  File "/app/backup/harequests.py", line 169, in updateSnapshotsSensor
    last = max(snapshots, key=lambda s: s.date()).date().isoformat()
TypeError: can't compare offset-naive and offset-aware datetimes


08-03 07:33:49 ERROR Trouble updating Home Assistant sensors.
08-03 07:33:49 ERROR 
Traceback (most recent call last):
  File "/app/backup/haupdater.py", line 40, in update
    self._requests.updateSnapshotsSensor(self._state(), self._cache)
  File "/app/backup/harequests.py", line 169, in updateSnapshotsSensor
    last = max(snapshots, key=lambda s: s.date()).date().isoformat()
TypeError: can't compare offset-naive and offset-aware datetimes


08-03 07:35:15 ERROR Trouble updating Home Assistant sensors.
08-03 07:35:15 ERROR 
Traceback (most recent call last):
  File "/app/backup/haupdater.py", line 40, in update
    self._requests.updateSnapshotsSensor(self._state(), self._cache)
  File "/app/backup/harequests.py", line 169, in updateSnapshotsSensor
    last = max(snapshots, key=lambda s: s.date()).date().isoformat()
TypeError: can't compare offset-naive and offset-aware datetimes


08-03 08:35:20 INFO Syncing Snapshots
```

**Comment by sabeechen** [comment] 2019-08-04 01:41
While I'm not happy that you've run into this, I have been trying to track down what causes this issue literally for _months_.  So far, every time it comes up it also goes away by itself.  I saw it once during testing but could never reproduce it again.  Does it stick around if you restart the addon?

**Comment by sabeechen** [comment] 2019-08-04 03:58
Additionally, could you let me know what time-zone your home assistant instance runs in?

**Comment by VivantSenior** [comment] 2019-08-04 11:29
@sabeechen timezone set on my RPi is CEST +2 and in configuration.yaml: time_zone: Europe/Warsaw (which are the same).

**Comment by sabeechen** [comment] 2019-08-04 18:42
I've released what I hope is a fix for this, but being unable to reproduce this in testing I can't be sure.  Can you see if the issue still comes up in v0.98.2 (refresh the add-on store page to make sure Hass.io sees the update)?

**Comment by to4ko** [comment] 2019-08-05 07:51
same issue here - just installed addon this morning

08-05 10:33:54 ERROR Trouble updating Home Assistant sensors.
08-05 10:33:54 ERROR 
Traceback (most recent call last):
  File "/app/backup/haupdater.py", line 40, in update
    self._requests.updateSnapshotsSensor(self._state(), self._cache)
  File "/app/backup/harequests.py", line 169, in updateSnapshotsSensor
    last = max(snapshots, key=lambda s: s.date()).date().isoformat()
TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by sabeechen** [comment] 2019-08-05 15:19
@to4ko are you also running the latest version of the addon, v0.98.2?

**Comment by sabeechen** [comment] 2019-08-05 15:22
Oh, my mistale, I didn't notice you mentioned that you just installed this morning.  Back to the drawing board for me!

**Comment by to4ko** [comment] 2019-08-05 20:22
It might be usefull - looking at error 
08-05 23:14:04 ERROR Trouble updating Home Assistant sensors.
08-05 23:14:04 ERROR 
Traceback (most recent call last):
  File "/app/backup/haupdater.py", line 38, in update
    self._requests.updateSnapshotStaleSensor(self._stale())
  File "/app/backup/harequests.py", line 161, in updateSnapshotStaleSensor
    self._postHaData("states/binary_sensor.snapshots_stale", data)
  File "/app/backup/harequests.py", line 137, in _postHaData
    self._client.post(self.config.get(Setting.HOME_ASSISTANT_URL) + path, headers=self._getHaHeaders(), json=data).raise_for_status()
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://hassio/homeassistant/api/states/binary_sensor.snapshots_stale

Addon trying to open address **http://hassio/homeassistant**/api/states/binary_sensor.snapshots_stale
without success.

I'm also was not able to open this address in Chrome. But it's became accessible once i put it like

**192.168.1.14:8123**/api/states/binary_sensor.snapshots_stale

Maybe you can add server address parameter to config?

**Comment by sabeechen** [comment] 2019-08-07 16:59
@to4ko  http://hassio is an alias hass.io creates for the addon to communicate with Home Assistant ([reference](https://developers.home-assistant.io/docs/en/hassio_addon_communication.html#home-assistant)) and so it shouldn't be configurable.  Its expected to see errors reaching this address sometimes (eg while Home Assistant is restarting) but isn't a problem unless it keep getting printed continually for more than few minutes.

**Comment by sabeechen** [comment] 2019-08-07 17:01
I found what I think is the source of the `Can't compare offset-naive and offset-aware datetimes` message.  If I'm right, the issue should always correct itself after a few hours.  I'll release a fix soon that prevents it form happening in the first place.

**Comment by sabeechen** [comment] 2019-09-11 18:36
I've released the fix for this, it should be included in v0.98.3.  Please re-open the issue if you're still seeing this error.

**Comment by ahartman** [comment] 2019-10-18 14:21
I am seeing this issue in version 0.100.2

**Comment by ahartman** [comment] 2019-10-18 18:17
Please find attached the part that I still have.
I will save a more complete log when the issue occurs again.

[log.txt](https://github.com/sabeechen/hassio-google-drive-backup/files/3745180/log.txt)

**Comment by ahartman** [comment] 2019-10-18 18:49
Occurred again at restart, please find log attached.

[log1.txt](https://github.com/sabeechen/hassio-google-drive-backup/files/3745286/log1.txt)

**Comment by sabeechen** [comment] 2019-10-19 00:13
The first log file looks like its an error in Home Assistant (unrelated to the addon) and the second one is just logging into a shell somewhere.  Are you using [Hass.io Google Drive Backup](https://github.com/sabeechen/hassio-google-drive-backup)?  This issue tracker is for problems with that addon, if you're running into problems with Home Assistant, you might want to report it in their [issue tracker](https://github.com/home-assistant/home-assistant/issues).

**Comment by ahartman** [comment] 2019-10-19 06:25
Please find attached the HA log file; it contains the same output as you found in my saved terminal output. The issue seems to go away with a few restarts.

[home-assistant.log](https://github.com/sabeechen/hassio-google-drive-backup/files/3746275/home-assistant.log)

**Comment by sabeechen** [comment] 2019-10-21 17:37
I'm going to need a little more convincing that this is actually a problem with my add-on.  This add-on doesn't do anything with calendars, and from the log you posted this seems to be a problem stemming from the [CalDav component](https://www.home-assistant.io/integrations/caldav/) of Home Assistant.  Are you saying Home Assistant only prints these error when you've installed [Hass.io Google Drive Backup](https://github.com/sabeechen/hassio-google-drive-backup)?

**Comment by ahartman** [comment] 2019-10-22 04:59
I think we have a confusion. I thought you were the author of the caldav component.
I do agree with you that this has nothing to with your Google drive backup as I do not use that.


Met vriendelijke groeten, Kind regards, Meilleures salutations,
André Hartman

**Closed** 2019-10-22 15:33 UTC
Labels: bug
