### ISSUE TITLE
Too may backups created overnight, possibly from DST transition

### ISSUE THREAD

**Issue by swtaarrs** [sabeechen/hassio-google-drive-backup#809] opened 2023-03-13 03:24 UTC
###### Description:
Home Assistant Google Drive Backup created way more backups than usual last night, one every every 1-2 minutes for a while (I think around an hour but the logs were truncated). Based on the timing, I'm guessing it's a daylight saving time issue (the switch from winter time to summer time was this morning in my area). I've attached two files:

- [A screenshot](https://user-images.githubusercontent.com/118219/224559890-becd3df0-12a9-4562-8237-2706f48fd85b.png) showing which backups were present in my drive when I woke up. You can see the one from 02:00 yesterday, then a bunch between 01:34 and 01:59 today, and finally one from 03:00 today. I'm assuming that there were more from before 01:34 that were deleted, since it was hitting my configured backup limit.
- [home-assistant-google-drive-backup.log](https://github.com/sabeechen/hassio-google-drive-backup/files/10951463/home-assistant-google-drive-backup.log) - the full log downloaded from the UI, which looks like it was truncated at 01:38 today.

Please let me know if you need any other information!

 Addon version: `0.110.1`
 Home Assistant Version: `2023.2.5`
 Supervisor Version: `2023.03.1`
 Supervisor Channel: `stable`
 Hassos Version: `9.5`
 Docker Version: `20.10.22`
 Architecture: `aarch64`
 Machine: `odroid-n2`
 Date: `2023-03-12T16:49:11.759555+00:00`
 Timezone: `America/Los_Angeles`
 Failure Time: `2023-03-12T10:00:26.529593+00:00`
 Last Good Sync: `2023-03-12T14:57:19.356448+00:00`
 Next Sync: `2023-03-12T16:59:43.464067+00:00`
 Next Backup: `2023-03-13T09:00:00+00:00`
 Next Cache Warm: `2259-09-18T18:57:29.697191+00:00`
 Time Offset: `0.0`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 10,
        "retained": 0,
        "deletable": 10,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2023-03-12T10:00:31Z",
        "max": 10,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 6,
        "detail": "",
        "size": "1.4 GB",
        "ignored_size": "272.7 MB",
        "free_space": "47.5 GB"
    },
    "GoogleDrive": {
        "backups": 32,
        "retained": 0,
        "deletable": 32,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2023-03-12T10:00:31Z",
        "max": 32,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "swtaarrs@gmail.com",
        "size": "4.4 GB",
        "ignored_size": "0.0 B",
        "free_space": "1.1 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 10,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 32,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.BACKUP_TIME_OF_DAY": "02:00",
    "Setting.GENERATIONAL_DAYS": 7,
    "Setting.GENERATIONAL_WEEKS": 4,
    "Setting.GENERATIONAL_MONTHS": 6,
    "Setting.GENERATIONAL_YEARS": 10
}
 ```
 ###### Addon Logs:
 ```
 03-12 03:02:21 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
03-12 03:02:25 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-03-12 03:00:30 44.13%
03-12 03:02:25 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
03-12 03:02:28 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-03-12 03:00:30 50.41%
03-12 03:02:29 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
03-12 03:02:32 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-03-12 03:00:30 56.69%
03-12 03:02:32 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
03-12 03:02:36 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-03-12 03:00:30 62.97%
03-12 03:02:36 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
03-12 03:02:40 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-03-12 03:00:30 69.25%
03-12 03:02:40 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
03-12 03:02:43 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-03-12 03:00:30 75.53%
03-12 03:02:43 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
03-12 03:02:47 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-03-12 03:00:30 81.82%
03-12 03:02:47 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
03-12 03:02:51 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-03-12 03:00:30 88.10%
03-12 03:02:51 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
03-12 03:02:55 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-03-12 03:00:30 94.38%
03-12 03:02:55 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
03-12 03:03:00 DEBUG [backup.drive.drivesource] Uploading Full Backup 2023-03-12 03:00:30 100.00%
03-12 03:03:00 INFO [backup.drive.drivesource] Deleting 'Full Backup 2023-03-12 01:33:07' From Google Drive
03-12 03:03:01 DEBUG [backup.watcher] Checking backup source for changes...
03-12 03:03:01 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
03-12 03:03:01 INFO [backup.model.coordinator] Syncing Backups
03-12 05:45:00 DEBUG [backup.model.syncer] Sync requested by Coordinator
03-12 05:45:00 INFO [backup.model.coordinator] Syncing Backups
03-12 05:45:00 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-12 07:57:19 DEBUG [backup.model.syncer] Sync requested by Coordinator
03-12 07:57:19 INFO [backup.model.coordinator] Syncing Backups
03-12 07:57:19 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
 ```
 ###### Supervisor Logs:
 ```
 [32m23-03-12 08:11:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER[0m
[32m23-03-12 08:11:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM[0m
[32m23-03-12 08:11:54 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m23-03-12 08:11:54 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m23-03-12 08:11:54 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m23-03-12 08:11:54 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m23-03-12 08:11:54 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m23-03-12 08:13:21 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-03-12 08:43:26 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-03-12 09:11:54 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m23-03-12 09:11:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.NO_CURRENT_BACKUP/ContextType.SYSTEM[0m
[32m23-03-12 09:11:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR[0m
[32m23-03-12 09:11:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[32m23-03-12 09:11:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER[0m
[32m23-03-12 09:11:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m23-03-12 09:11:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m23-03-12 09:11:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER[0m
[32m23-03-12 09:11:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.IPV4_CONNECTION_PROBLEM/ContextType.SYSTEM[0m
[32m23-03-12 09:11:54 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m23-03-12 09:11:54 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m23-03-12 09:11:54 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m23-03-12 09:11:54 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m23-03-12 09:11:54 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m23-03-12 09:13:30 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-03-12 09:36:34 INFO (MainThread) [supervisor.api.middleware.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-12 09:36:34 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-12 09:36:34 INFO (MainThread) [supervisor.api.middleware.security] /addons access from cebe7a76_hassio_google_drive_backup[0m
[32m23-03-12 09:43:36 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m23-03-12 09:49:11 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 [33m2023-03-11 18:12:18.331 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.back_christmas_lights, light.front_christmas_lights, light.inside_christmas_lights or it is/they are currently not available[0m
[32m2023-03-11 18:14:40.912 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7128356: switch.dining_room_keypad:1 pressed[0m
[33m2023-03-11 18:19:35.508 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.back_christmas_lights, light.front_christmas_lights, light.inside_christmas_lights or it is/they are currently not available[0m
[32m2023-03-11 20:21:22.974 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7178208: switch.kitchen_keypad:2 pressed[0m
[32m2023-03-11 20:21:24.233 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7178229: switch.kitchen_keypad:1 pressed[0m
[32m2023-03-11 20:21:25.454 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7178248: switch.kitchen_keypad:3 pressed[0m
[33m2023-03-11 20:36:51.425 WARNING (MainThread) [homeassistant.components.denonavr.media_player] Timeout connecting to Denon AVR receiver at host 10.1.10.114. Device is unavailable[0m
[33m2023-03-11 20:36:56.419 WARNING (MainThread) [homeassistant.components.media_player] Updating denonavr media_player took longer than the scheduled update interval 0:00:10[0m
[33m2023-03-11 20:36:56.432 WARNING (MainThread) [homeassistant.components.denonavr.media_player] Timeout connecting to Denon AVR receiver at host 10.1.10.114. Device is unavailable[0m
[31m2023-03-11 20:37:04.769 ERROR (MainThread) [homeassistant.components.heos] Unable to update sources: User not logged in (8)[0m
[32m2023-03-11 20:57:12.809 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7192167: switch.hallway_keypad:1 pressed[0m
[32m2023-03-11 22:44:08.139 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7233474: switch.kitchen_keypad:3 pressed[0m
[33m2023-03-11 23:00:00.364 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities light.back_christmas_lights, light.front_christmas_lights, light.inside_christmas_lights or it is/they are currently not available[0m
[32m2023-03-11 23:12:29.231 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7244308: switch.kitchen_keypad:2 pressed[0m
[32m2023-03-11 23:12:30.338 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7244330: switch.kitchen_keypad:1 pressed[0m
[32m2023-03-11 23:20:42.947 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7247424: switch.dining_room_keypad:1 pressed[0m
[32m2023-03-11 23:24:27.855 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7248882: switch.entry_keypad:1 pressed[0m
[32m2023-03-11 23:24:29.584 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7248924: switch.entry_keypad:1 pressed[0m
[32m2023-03-11 23:24:30.066 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7248942: switch.entry_keypad:2 pressed[0m
[32m2023-03-11 23:26:17.092 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7249625: switch.dining_room_keypad:1 pressed[0m
[32m2023-03-11 23:43:25.075 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7256215: switch.kitchen_keypad:1 pressed[0m
[32m2023-03-11 23:43:34.230 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7256283: switch.kitchen_keypad:3 pressed[0m
[32m2023-03-11 23:43:46.844 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7256368: switch.entry_keypad:1 pressed[0m
[32m2023-03-11 23:43:52.017 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7256463: switch.entry_keypad:2 pressed[0m
[32m2023-03-12 00:04:12.190 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7264491: switch.upstairs_keypad:1 pressed[0m
[33m2023-03-12 00:35:04.980 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.inside_christmas_lights or it is/they are currently not available[0m
[31m2023-03-12 00:35:30.490 ERROR (MainThread) [homeassistant.components.awair] Timeout fetching awair data[0m
[33m2023-03-12 08:37:36.762 WARNING (MainThread) [homeassistant.components.denonavr.media_player] Timeout connecting to Denon AVR receiver at host 10.1.10.114. Device is unavailable[0m
[32m2023-03-12 09:25:09.726 INFO (MainThread) [custom_components.pyscript.file.keypads.handle_zwave_event] Task-7455879: switch.hallway_keypad:2 pressed[0m

 ```

**Comment by sabeechen** [comment] 2023-03-13 17:52
Thank you for giving so much info, this paints a very clear picture.  Your explanation is likely correct, that this is caused by an error translating dates near the DST shift.  I suspect this will happen when all of the following are true:
- Generational backups are configured
- You're in a timezone that locally observes DST
- Creating the backup takes less than an hour
- Backups are configured to happen during (or very near) the DST shift

This is corroborated by Google's monitoring of the addon's global usage, note the spike in requests on the morning of Mar 12:
![image](https://user-images.githubusercontent.com/21026774/224781961-8953ec88-fc48-4200-af21-83d695536832.png)
Whoops!  It looks like the addon thinks from 1am to 3am (which is actually just one hour of real time) that any backup was created in the previous day even if its just a few seconds ago.

From the looks of your logs it seems like this bug probably cleared out your history of saved backups.  If thats the case, my apologies, I do my best to keep the addon from doing that but it happens sometimes.  Data loss is the greatest shame for a backup tool.

I'll see if I can get some test coverage for this error to prevent it from happening in the future.  Thankfully I don't think any timezone observes a DST shift any time soon, so I've got a while to sort it out.

Side note: I see a lot of snippets of Home Assistant logs posted from users because of how this bug generating tools works, and you'd be amazed how error saturated most of them are.  My complements on having a log thats largely error free.

**Comment by swtaarrs** [comment] 2023-03-15 00:55
Thanks for the quick response!

> it seems like this bug probably cleared out your history of saved backups

It looks like I didn't lose any preexisting backups, maybe because I started using the addon recently enough that I hadn't yet hit my configured maximum. Although I'm not sure why it preferentially deleted the backups it created shortly after 01:00 on March 12, rather than the daily backups from March 11 and earlier. Either way, it was a good reminder that when I do hit the limit naturally it'll almost fill up my Google Drive, so I'll have to change something before that happens :).

> I don't think any timezone observes a DST shift any time soon

From the lack of other bugs filed I may be one of the only people who noticed this, but Europe switches to summer time on March 26 this year.

**Comment by dlindnegm** [comment] 2023-03-23 13:35
11 days later....

I just realized that this happened to me as well.  42 backups were created on the morning of 3/12, wiping out all but 3 previous backups (no harm as I have other full backups that I made manually).  I wonder if this didn't affect many more people but they just never noticed it unless they either regularly monitor their backup folder or ran out of space?  

Time zone changes are a real pain to deal with.  I believe that Microsoft still has a bug in their Windows OS that fails to accurately get the workstation time for an exactly one week period after the time zone changes in Spring and Fall when using a WMI query.  They have known about it for years (I've reported it several times via my companies Premier Support account) but never fixed it!

Let me know if there's any additional information I can gather for you.

Home Assistant 2023.3.5
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230309.1
Google Drive Backup 0.110.1
Eastern Daylight Time (GMT-5)

max_backups_in_ha: 20
max_backups_in_google_drive: 40
days_between_backups: 1
ignore_other_backups: true
ignore_upgrade_backups: true
backup_time_of_day: "02:00"
backup_password: xxxxxxxxx
backup_name: "{type} Backup {year}-{month}-{day}_{hr24}_{min}"
specify_backup_folder: true
send_error_reports: false
generational_days: 1
generational_weeks: 4
generational_months: 12
generational_years: 1
exclude_addons: core_mariadb
stop_addons: core_mariadb

**Comment by sabeechen** [comment] 2023-03-23 15:05
Sorry you lost some of your backup history,  I wish I had a mechanism in place to detect that for logic errors like this (I'll think about that).

I also suspect many people are affected, though I can only speculate how many.  I have the spike in Drive usage globally to give an idea but the rate any individual uploads at during the problematic DST transition depends on how long it takes to create a backup, which varies wildly among users.  It looks like the problem happens even without generational backup.  Most probably won't notice unless they check, and even fewer would bother reporting.  Unfortunately its pretty common for users to schedule backups to happen in the wee hours of the morning during the affected time window. Anyone who's backup takes longer than an hour will pretty much avoid the problem.  Even an estimate of how many are affected is, I think, unknowable with the monitoring I have.

This has turned out to be more challenging to solve than I expected.  The default python datetime libraries are relatively DST naive, which is the ultimate source of the problem, so I've had to rewrite a lot of things to use a more feature-rich library.  I have it fixed in a checkin I'm cleaning up now, but I'm not 100% confident its going to be fully vetted before the next DST transition.  Even if I released it immediately,  its unlikely everyone would update in time to avoid the majority of problems.  I've had difficulty finding an exhaustive list of all transitions, but I was able to get this list out of GPT4:
```
It is difficult to provide an exhaustive list of all the time zones where DST begins in 2023, as countries and regions may change their DST rules. However, here are some known DST start dates for 2023 in various time zones:

1. United States, Canada, and Mexico (most regions):
- Eastern Daylight Time (EDT): March 12, 2023
- Central Daylight Time (CDT): March 12, 2023
- Mountain Daylight Time (MDT): March 12, 2023
- Pacific Daylight Time (PDT): March 12, 2023

2. European Union (including UK):
- Central European Summer Time (CEST): March 26, 2023
- British Summer Time (BST): March 26, 2023
- Eastern European Summer Time (EEST): March 26, 2023

3. Australia (some regions):
- Australian Eastern Daylight Time (AEDT): October 1, 2023
- Australian Central Daylight Time (ACDT): October 1, 2023

4. New Zealand:
- New Zealand Daylight Time (NZDT): September 24, 2023

Please note that these dates may be subject to change, and other countries or regions not mentioned may also observe DST. It's always a good idea to check local regulations for any updates on DST changes.
```

So next is the EU in 3 days, then the southern hemisphere many months later. I'll aim to release a fix in the next few days so at least those in the EU who auto update will get it.

**Comment by sabeechen** [comment] 2023-03-23 20:26
At this point it would take me longer to implement that feature (a new notification), so I think I'll just opt to get this out as soon as possible.  I normally like to let a new release, even fixes, sit around in my dev environment for a few days before making a release but I added such exhaustive test coverage for this while fixing it that I'm feeling more comfortable fast-tracking a fix release.  If nothing else goes wrong I'll release the fix tonight.

And you're right, once its out I should post in the forum recommending anyone in a DST observing european timezone upgrade.

**Closed** 2023-03-24 15:54 UTC
Labels: Do this next
