### ISSUE TITLE
change backup folder on google drive

### ISSUE THREAD

**Issue by tsolli** [sabeechen/hassio-google-drive-backup#104] opened 2019-10-01 08:10 UTC
Should be able to change the backup folder on google drive.
I have several hassio servers backup to the same google drive and would be nice to be able to have different folders for each server.

**Comment by sabeechen** [comment] 2019-10-01 18:48
I've got a [request](https://github.com/sabeechen/hassio-google-drive-backup/issues/75) open for this feature, Its in the works just a bit more complicated than I'd hoped to fully support so its taking me a while to do.  I've been surprised to see how often the feature is requested.

Just to make sure I'm getting the use case for this right, could you tell me how you use multiple Hass.io instances?  Eg why having multiple backup folders would be useful.

**Comment by djek123** [comment] 2019-10-12 06:53
Another use case example:
Two separate installations of hassio in two different locations. It would be great to have each hassio installation backup in it's own folder on the same gdrive.

**Comment by sabeechen** [comment] 2019-10-24 16:38
Duplicate of #75

**Closed by sabeechen** 2019-10-24 16:38 UTC
Labels: duplicate
