### ISSUE TITLE
Sync  issue  

### ISSUE THREAD

**Issue by ArielBaravalle** [sabeechen/hassio-google-drive-backup#295] opened 2020-10-29 15:02 UTC
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.101.3`
 Home Assistant Version: `0.116.4`
 Supervisor Version: `2020.10.0`
 Supervisor Channel: `stable`
 Hassos Version: `4.15`
 Docker Version: `19.03.11`
 Architecture: `armv7`
 Machine: `raspberrypi4`
 Date: `2020-10-29T15:00:27.987482+00:00`
 Timezone: `Europe/Madrid`
 Failure Time: `2020-10-29T15:00:17.247786+00:00`
 Last Good Sync: `2020-10-29T15:00:16.541819+00:00`
 ###### Exception:
 ```
 
  addon/backup/util/asynchttpgetter.py:133 (read)
  /site-packages/aiohttp/streams.py:416 (readexactly)
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
Whose handling caused:
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:162 (sync)
  addon/backup/drive/drivesource.py:150 (save)
  addon/backup/drive/driverequests.py:252 (create)
  addon/backup/util/asynchttpgetter.py:140 (read)
backup.exceptions.exceptions.SupervisorUnexpectedError

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 2,
        "retained": 0,
        "deletable": 2,
        "name": "HomeAssistant",
        "latest": "2020-10-27T15:59:00Z",
        "size": "6.1 GB"
    },
    "GoogleDrive": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "latest": null,
        "size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 6,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 7.0,
    "Setting.SNAPSHOT_TIME_OF_DAY": "05:00",
    "Setting.SNAPSHOT_PASSWORD": "REDACTED"
}
 ```
 ###### Addon Logs:
 ```
 10-29 15:23:36 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-29 15:23:36 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1SDnOd3g5pDOf2VOKiVVNsvVboJJPM3TL/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
10-29 15:23:37 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271SDnOd3g5pDOf2VOKiVVNsvVboJJPM3TL%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-29 15:23:37 INFO [backup.drive.drivesource] Uploading 'martes, 27 de oct. de 2020' to Google Drive
10-29 15:23:37 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
10-29 15:23:37 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-UwwrxAuicIvWYT2Gv4vr-PiLz9Bb0ih3ioq_Oa4qCWwsbxoEADJM8d497ogNd3ifCnUiv3POMiE_gnGAHtz9vR2hfR6nA
10-29 15:23:37 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 5892515840
10-29 15:23:37 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
10-29 15:23:37 INFO [backup.model.coordinator] I'll try again in an hour
10-29 15:23:53 INFO [backup.drive.drivesource] Saving new Google Drive credentials
10-29 15:23:53 DEBUG [backup.model.syncer] Sync requested by GoogleDrive
10-29 15:23:53 INFO [backup.model.coordinator] Syncing Snapshots
10-29 15:23:53 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-29 15:23:53 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271SDnOd3g5pDOf2VOKiVVNsvVboJJPM3TL%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-29 15:23:54 INFO [backup.drive.drivesource] Uploading 'martes, 27 de oct. de 2020' to Google Drive
10-29 15:23:54 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
10-29 15:23:54 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-UwwrxAuicIvWYT2Gv4vr-PiLz9Bb0ih3ioq_Oa4qCWwsbxoEADJM8d497ogNd3ifCnUiv3POMiE_gnGAHtz9vR2hfR6nA
10-29 15:23:54 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 5892515840
10-29 15:23:54 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
10-29 15:23:54 INFO [backup.model.coordinator] I'll try again in an hour
10-29 16:00:16 INFO [backup.model.coordinator] Syncing Snapshots
10-29 16:00:16 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-29 16:00:16 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1SDnOd3g5pDOf2VOKiVVNsvVboJJPM3TL/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
10-29 16:00:16 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271SDnOd3g5pDOf2VOKiVVNsvVboJJPM3TL%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-29 16:00:17 INFO [backup.drive.drivesource] Uploading 'martes, 27 de oct. de 2020' to Google Drive
10-29 16:00:17 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
10-29 16:00:17 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-UwwrxAuicIvWYT2Gv4vr-PiLz9Bb0ih3ioq_Oa4qCWwsbxoEADJM8d497ogNd3ifCnUiv3POMiE_gnGAHtz9vR2hfR6nA
10-29 16:00:17 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 5892515840
10-29 16:00:17 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
10-29 16:00:17 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m20-10-29 14:26:30 INFO (SyncWorker_7) [supervisor.docker.interface] Removing image hassioaddons/adguard-armv7 with latest and 2.5.1[0m
[32m20-10-29 14:26:31 INFO (MainThread) [supervisor.addons.addon] Removing add-on data folder /data/addons/data/a0d7b954_adguard[0m
[32m20-10-29 14:26:31 INFO (MainThread) [supervisor.discovery] Delete discovery to Home Assistant adguard from a0d7b954_adguard[0m
[32m20-10-29 14:26:31 INFO (MainThread) [supervisor.addons] Add-on 'a0d7b954_adguard' successfully removed[0m
[32m20-10-29 14:26:31 INFO (MainThread) [supervisor.discovery] Discovery ab710f413f5d4307aa86ff5f0a235cb5 message send[0m
[32m20-10-29 14:27:08 INFO (SyncWorker_0) [supervisor.docker.interface] Stopping addon_a0d7b954_influxdb application[0m
[32m20-10-29 14:27:17 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning addon_a0d7b954_influxdb application[0m
[32m20-10-29 14:27:17 INFO (SyncWorker_4) [supervisor.docker.interface] Cleanup images: ['hassioaddons/influxdb-armv7:3.7.7'][0m
[32m20-10-29 14:27:18 INFO (MainThread) [supervisor.addons] Add-on 'a0d7b954_influxdb' successfully updated[0m
[32m20-10-29 14:27:22 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on hassioaddons/influxdb-armv7 with version 3.7.8[0m
[32m20-10-29 14:27:23 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_influxdb[0m
[32m20-10-29 14:27:25 INFO (MainThread) [supervisor.api.security] /dns/info access from a0d7b954_influxdb[0m
[32m20-10-29 14:27:57 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m20-10-29 14:29:28 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 0.117.0[0m
[32m20-10-29 14:29:28 INFO (SyncWorker_0) [supervisor.docker.interface] Updating image homeassistant/raspberrypi4-homeassistant:0.116.4 to homeassistant/raspberrypi4-homeassistant:0.117.0[0m
[32m20-10-29 14:29:28 INFO (SyncWorker_0) [supervisor.docker.interface] Downloading docker image homeassistant/raspberrypi4-homeassistant with tag 0.117.0.[0m
[32m20-10-29 14:36:01 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-10-29 14:38:18 INFO (SyncWorker_0) [supervisor.docker.interface] Stopping homeassistant application[0m
[32m20-10-29 14:39:19 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning homeassistant application[0m
[32m20-10-29 14:39:19 INFO (MainThread) [supervisor.homeassistant] Update pulse/client.config: /data/tmp/homeassistant_pulse[0m
[32m20-10-29 14:39:21 INFO (SyncWorker_4) [supervisor.docker.homeassistant] Starting Home Assistant homeassistant/raspberrypi4-homeassistant with version 0.117.0[0m
[32m20-10-29 14:39:21 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready[0m
[32m20-10-29 14:40:26 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance[0m
[32m20-10-29 14:40:26 INFO (MainThread) [supervisor.homeassistant.core] Successful started Home Assistant 0.117.0[0m
[32m20-10-29 14:40:26 INFO (SyncWorker_5) [supervisor.docker.interface] Cleanup images: ['homeassistant/raspberrypi4-homeassistant:0.116.4'][0m
[32m20-10-29 15:00:16 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-29 15:00:17 INFO (MainThread) [supervisor.api.security] /snapshots/366401f7/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-29 15:00:17 INFO (MainThread) [supervisor.api.snapshots] Downloading snapshot 366401f7[0m
[32m20-10-29 15:00:28 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pygatt/backends/gatttool/gatttool.py", line 486, in disconnect
    if not self._receiver.is_set("disconnected"):
AttributeError: 'NoneType' object has no attribute 'is_set'
2020-10-29 15:40:30 WARNING (MainThread) [homeassistant.config_entries] Config entry for adguard not ready yet. Retrying in 40 seconds
2020-10-29 15:40:35 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.tomates_moisture is taking over 10 seconds
2020-10-29 15:40:37 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2020-10-29 15:40:51 WARNING (MainThread) [homeassistant.components.automation.airwick_2_perfuma] AIRWICK 2 - Perfuma: Already running
2020-10-29 15:40:59 WARNING (MainThread) [homeassistant.components.automation.airwick_2_perfuma] AIRWICK 2 - Perfuma: Already running
2020-10-29 15:41:01 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 404
2020-10-29 15:41:10 WARNING (MainThread) [homeassistant.config_entries] Config entry for adguard not ready yet. Retrying in 80 seconds
2020-10-29 15:41:23 WARNING (MainThread) [homeassistant.components.automation.airwick_2_perfuma] AIRWICK 2 - Perfuma: Already running
2020-10-29 15:41:40 WARNING (MainThread) [homeassistant.components.automation.airwick_2_perfuma] AIRWICK 2 - Perfuma: Already running
2020-10-29 15:42:30 WARNING (MainThread) [homeassistant.config_entries] Config entry for adguard not ready yet. Retrying in 80 seconds
2020-10-29 15:43:50 WARNING (MainThread) [homeassistant.config_entries] Config entry for adguard not ready yet. Retrying in 80 seconds
2020-10-29 15:45:10 WARNING (MainThread) [homeassistant.config_entries] Config entry for adguard not ready yet. Retrying in 80 seconds
2020-10-29 15:46:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2864085936] Client unable to keep up with pending messages. Stayed over 512 for 5 seconds
2020-10-29 15:46:30 WARNING (MainThread) [homeassistant.config_entries] Config entry for adguard not ready yet. Retrying in 80 seconds
2020-10-29 15:47:50 WARNING (MainThread) [homeassistant.config_entries] Config entry for adguard not ready yet. Retrying in 80 seconds
2020-10-29 15:48:59 WARNING (MainThread) [homeassistant.components.automation.airwick_2_perfuma] AIRWICK 2 - Perfuma: Already running
2020-10-29 15:49:10 WARNING (MainThread) [homeassistant.config_entries] Config entry for adguard not ready yet. Retrying in 80 seconds
2020-10-29 15:50:30 WARNING (MainThread) [homeassistant.config_entries] Config entry for adguard not ready yet. Retrying in 80 seconds
2020-10-29 15:51:50 WARNING (MainThread) [homeassistant.config_entries] Config entry for adguard not ready yet. Retrying in 80 seconds
2020-10-29 15:53:10 WARNING (MainThread) [homeassistant.config_entries] Config entry for adguard not ready yet. Retrying in 80 seconds
2020-10-29 15:54:30 WARNING (MainThread) [homeassistant.config_entries] Config entry for adguard not ready yet. Retrying in 80 seconds
2020-10-29 15:55:50 WARNING (MainThread) [homeassistant.config_entries] Config entry for adguard not ready yet. Retrying in 80 seconds
2020-10-29 15:57:10 WARNING (MainThread) [homeassistant.config_entries] Config entry for adguard not ready yet. Retrying in 80 seconds
2020-10-29 15:58:30 WARNING (MainThread) [homeassistant.config_entries] Config entry for adguard not ready yet. Retrying in 80 seconds
2020-10-29 15:59:50 WARNING (MainThread) [homeassistant.config_entries] Config entry for adguard not ready yet. Retrying in 80 seconds

 ```

**Comment by sabeechen** [comment] 2020-10-29 15:46
This is certainly another instance of #226. You'll see this if you are both:

  * Using the 32-bit arm verison of Home Assistant (you are)
  * Have a snapshot over 2GB in size (you do)

It is caused by a bug in the supervisor. You can verify this is the case by going to the supervisor's own snapshots page (Supervisor > Snapshots) and trying to download the large snapshot, which will fail. I've filed [an issue](https://github.com/home-assistant/supervisor/issues/2047) and they think they've resolved it, and will most likely be released as a supervisor update within a week.
If you want to fix it faster, the only workarounds until the fix is released are:

 * Install and run the 64 bit version of Home Assistant (Admittedly I don't know why the 32 bit versions are recommended).
 * Keep the snapshot below 2GB. Usually large snapshots are from storing the database or camera images, and usually the snapshot can do without them.

I'll update #266 when I have any new information on the issue.

Duplicate #226

**Closed by sabeechen** 2020-10-29 15:46 UTC

**Comment by ArielBaravalle** [comment] 2020-10-29 21:40
hello.  thanks Sabeechen  for your reply 

yes, my snapshot have 5Gb,  and I unknown why ! ,  all my previous snapshots have no more that 600Mb . 
I go to check this . 

best regards !
