### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by nuvolare12** [sabeechen/hassio-google-drive-backup#764] opened 2022-12-08 14:13 UTC
Hello, trying to install but i have some problem

Can't install sabeechen/hassio-google-drive-backup-armv7:0.109.2: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=0.109.2&fromImage=sabeechen%2Fhassio-google-drive-backup-armv7&platform=linux%2Farm%2Fv7: Internal Server Error ("Head "https://registry-1.docker.io/v2/sabeechen/hassio-google-drive-backup-armv7/manifests/0.109.2": Get "https://auth.docker.io/token?scope=repository%3Asabeechen%2Fhassio-google-drive-backup-armv7%3Apull&service=registry.docker.io": read tcp 192.168.1.131:54568->44.205.64.79:443: read: connection reset by peer")

**Comment by sabeechen** [comment] 2022-12-13 21:06
This could be caused by a lot of things, the error indicates that a connection was interrupted while downloading the addon's image from DockerHub.  Home Assistant downloads this image as part of the installation of the addon and it is outside of my ability (as the add-on developer) to do anything to fix whatever is causing this connection problem.  Please consider the following:

- Ensure you have a reliable internet connection.  The installation image is about ~150MB and needs to be downloaded in one go.  
- If you're using anything that interferes with your internet connection (eg a VPN, HTTP/S Proxy, network wide ad block, an aggressive firewall) consider disabling it before you try again.  Connections coming from VPN's in particular are often blocked from public services like DockerHub.

If all else fails, there is a possibility the problem is with Home Assistant itself.  You could try:
1. Uninstalling the add-on(if it shows up as installed)
2. Removing this add-on's repository.
3. Restart Home Assistant
4. Re-add the repository
5. Attempting installing again.

**Comment by nuvolare12** [comment] 2022-12-18 17:33
Hello, ok so, i tried to download again the addon, by a link directly from home assistant. First od all, my internet connection is perfect, i installed other addon's, and they are perfect working. Than i  unistall the add-on and i intalled again, than i followed all the point as you wrote me, but at the end i have same error. 
Is there any one that have same error?
Is this the only way to have a backup? 
Thank you for your help

**Comment by sabeechen** [comment] 2022-12-22 21:46
I haven't seen thsi specific error, but other have seen [similar errors](https://github.com/sabeechen/hassio-google-drive-backup/issues?q=%22Can%27t+install%22+) downloading the addon from GitHub and DockerHub.  Its possible there is something from in wrong Home Assistant, since thats whats performing the installation, but this really does look like a simple connection issue.  "Connection reset by peer" means the remote server (DockerHub in this case) closed the connection while you were trying to download from it.

You can still create backups using the Home Assistant web-ui, it just doens't manage uploading them to Google drive.

**Comment by nuvolare12** [comment] 2023-01-08 14:22
I'm using the backup on home assistant , so can i use this back up in case of some crash of the sistem?

**Comment by sabeechen** [comment] 2023-01-10 00:06
Yes, you can use Home Assistant by itself to create backups by going to:
"Settings" > "System" > "Backups" > "+ Create New Backup"

Once the backup is finished, you can then download it from the same UI.  You can also automate the creation of backups by calling the service ```hassio.backup_full```, eg:
```yaml
service: hassio.backup_full
data:
  name: My Backup
  password: Super Secret Password
```
Thats bascially what this addon does, aside from uploading the backup to Google Drive and deleting the oldest backup.

I'm not sure there is anything I can do further to help you, so I'm going to close this issue for now.  If you think I can assist further, please feel free to re-open it and let me know.

**Closed by sabeechen** 2023-01-10 00:06 UTC
