### ISSUE TITLE
Backups page won't load

### ISSUE THREAD

**Issue by Spiffo** [sabeechen/hassio-google-drive-backup#466] opened 2021-09-08 07:51 UTC
Backups are created, but the front end remains on "Waiting for backups to load". I assume small bug introduced while renaming from snapshots to backups?
Gear button to go to settings page also does not work.

**Comment by jvberlo** [comment] 2021-09-08 09:44
Same. When using chome on my computer it wont show info. But when i open it on my iphone then it works. Both using nabu.case link

**Comment by Mr-Groch** [comment] 2021-09-08 09:48
> Same here. When using chrome on my computer it wont show info. But when I open it on my iphone then it works. Both using nabu.case link

Same here

**Comment by mousediver** [comment] 2021-09-08 09:49
It does also work in the companion app on android but not in the browser

**Comment by NicolasRigo** [comment] 2021-09-08 10:15
Same here since upgraded to 0.105.01 HA last version running on RPI4 (supervised).

**Comment by Spiffo** [comment] 2021-09-08 11:00
> It does also work in the companion app on android but not in the browser

not for me...

**Comment by NicolasRigo** [comment] 2021-09-08 11:55
Working with Chrome and native iOS app but not with Safari (I'm using an intel based Macbook Pro)

**Comment by sabeechen** [comment] 2021-09-08 13:52
It sounds like there is a javascript error on the page, but only in some browsers.  I haven't been able to get this error to reproduce on any of the browser I have so I'll need some help to figure out where it is

Could I have one of you seeing the problem on Chrome:
* Open the addon Web-UI
* Press <kbd>CTRL</kbd> + <kbd>SHIFT</kbd>+ <kbd>J</kbd>, this will bring up the debugging console in your browser.
* Refresh the page ( <kbd>F5</kbd> )
* Make sure the web UI is still broken.
* Take a screenshot of whats in the console, or copy it here

**Comment by loomyr** [comment] 2021-09-08 14:41
same here... 
![image](https://user-images.githubusercontent.com/73883405/132530465-610ea59c-8d3b-4242-9c05-49232b96061b.png)
Not working on 
- Brave (chromium engine)
- Chrome

Working on
- Firefox
- Microsoft Edge

Please find my CTRL+SHIFT+J error warning on that page : 
![image](https://user-images.githubusercontent.com/73883405/132530900-b44a6db7-ef40-47c5-99bc-46363c49dba2.png)

**Comment by loomyr** [comment] 2021-09-08 14:52
same here... 
![image](https://user-images.githubusercontent.com/73883405/132530465-610ea59c-8d3b-4242-9c05-49232b96061b.png)
Not working on 
- Brave (chromium engine)
- Chrome

Working on
- Firefox
- Microsoft Edge

HA 
- core-2021.9.4
- supervisor-2021.09.0
- OS Version 6.3

Please find below my CTRL+SHIFT+J errors & warnings on that page, please let me know if you need further logs/output : 
![image](https://user-images.githubusercontent.com/73883405/132532832-a3b24378-56de-4d65-bee0-cc69f51822e3.png)

**Comment by loomyr** [comment] 2021-09-08 15:05
Sorry for my multiple post delete, but errors log was not all related to the dashboard page...

same here... 
![image](https://user-images.githubusercontent.com/73883405/132530465-610ea59c-8d3b-4242-9c05-49232b96061b.png)
Not working on 
- Brave (chromium engine)
- Chrome

Working on
- Firefox
- Microsoft Edge

HA 
- core-2021.9.4
- supervisor-2021.09.0
- OS Version 6.3

Please find below my CTRL+SHIFT+J errors & warnings on that page, please let me know if you need further logs/output:
- got this when I refresh the page :8123/cebe7a76_hassio_google_drive_backup/dashboard  :

```
  app.f08a72d3.js:5264 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.
  55704 @ app.f08a72d3.js:5264
  s @ app.f08a72d3.js:30632
  53918 @ app.f08a72d3.js:1290
  s @ app.f08a72d3.js:30632
  (anonymous) @ app.f08a72d3.js:30632
  (anonymous) @ app.f08a72d3.js:36741
  (anonymous) @ app.f08a72d3.js:36741
  6da8e7d0.js:1 [Violation] Avoid using document.write(). https://developers.google.com/web/updates/2016/08/removing-document-write
  value @ 6da8e7d0.js:1
  value @ 6da8e7d0.js:1
  performUpdate @ app.f08a72d3.js:1
  _$EC @ app.f08a72d3.js:1
  entrypoint.74ae643f.js:38051 The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'.
  5704 @ entrypoint.74ae643f.js:38051
  s @ entrypoint.74ae643f.js:73409
  4552 @ entrypoint.74ae643f.js:65226
  s @ entrypoint.74ae643f.js:73409
  1625 @ entrypoint.74ae643f.js:71607
  s @ entrypoint.74ae643f.js:73409
  7316 @ entrypoint.74ae643f.js:6216
  s @ entrypoint.74ae643f.js:73409
  (anonymous) @ entrypoint.74ae643f.js:73409
  (anonymous) @ entrypoint.74ae643f.js:73409
  myha.mydoain.local/:1 [DOM] Input elements should have autocomplete attributes (suggested: "username"): (More info: https://goo.gl/9p2vKq) <input type=​"text" id=​"backup_time_of_day" name=​"backup_time_of_day" pattern=​"^[0-2]​\d:​[0-5]​\d$" class=​"validate">​
  6[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
  materialize.js?version=0.105.1:5563 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
  _setupEventHandlers @ materialize.js?version=0.105.1:5563
  Sidenav @ materialize.js?version=0.105.1:5511
  init @ materialize.js?version=0.105.1:1049
  init @ materialize.js?version=0.105.1:6043
  jQuery.fn.<computed> @ materialize.js?version=0.105.1:1151
  (anonymous) @ init.js?version=0.105.1:4
  l @ jquery.js?version=0.105.1:2
  c @ jquery.js?version=0.105.1:2
  materialize.js?version=0.105.1:5565 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
  _setupEventHandlers @ materialize.js?version=0.105.1:5565
  Sidenav @ materialize.js?version=0.105.1:5511
  init @ materialize.js?version=0.105.1:1049
  init @ materialize.js?version=0.105.1:6043
  jQuery.fn.<computed> @ materialize.js?version=0.105.1:1151
  (anonymous) @ init.js?version=0.105.1:4
  l @ jquery.js?version=0.105.1:2
  c @ jquery.js?version=0.105.1:2
  materialize.js?version=0.105.1:5567 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
  _setupEventHandlers @ materialize.js?version=0.105.1:5567
  Sidenav @ materialize.js?version=0.105.1:5511
  init @ materialize.js?version=0.105.1:1049
  init @ materialize.js?version=0.105.1:6043
  jQuery.fn.<computed> @ materialize.js?version=0.105.1:1151
  (anonymous) @ init.js?version=0.105.1:4
  l @ jquery.js?version=0.105.1:2
  c @ jquery.js?version=0.105.1:2
  materialize.js?version=0.105.1:5563 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
  _setupEventHandlers @ materialize.js?version=0.105.1:5563
  Sidenav @ materialize.js?version=0.105.1:5511
  init @ materialize.js?version=0.105.1:1049
  init @ materialize.js?version=0.105.1:6043
  jQuery.fn.<computed> @ materialize.js?version=0.105.1:1151
  (anonymous) @ (index):1680
  l @ jquery.js?version=0.105.1:2
  c @ jquery.js?version=0.105.1:2
  materialize.js?version=0.105.1:5565 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
  _setupEventHandlers @ materialize.js?version=0.105.1:5565
  Sidenav @ materialize.js?version=0.105.1:5511
  init @ materialize.js?version=0.105.1:1049
  init @ materialize.js?version=0.105.1:6043
  jQuery.fn.<computed> @ materialize.js?version=0.105.1:1151
  (anonymous) @ (index):1680
  l @ jquery.js?version=0.105.1:2
  c @ jquery.js?version=0.105.1:2
  materialize.js?version=0.105.1:5567 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
  _setupEventHandlers @ materialize.js?version=0.105.1:5567
  Sidenav @ materialize.js?version=0.105.1:5511
  init @ materialize.js?version=0.105.1:1049
  init @ materialize.js?version=0.105.1:6043
  jQuery.fn.<computed> @ materialize.js?version=0.105.1:1151
  (anonymous) @ (index):1680
  l @ jquery.js?version=0.105.1:2
  c @ jquery.js?version=0.105.1:2
  onloadwff.js:71 [Violation] 'setTimeout' handler took 94ms
  
```
 - got this error when I click new backup button : 

```
  (index):1781 Uncaught ReferenceError: newBackupClick is not defined
    at HTMLAnchorElement.onclick ((index):1781)
  onclick @ (index):1781
```
- this one when i click settings button:

```
  scripts.js?version=0.105.1:831 Uncaught TypeError: Cannot set properties of undefined (setting '{type}')
      at exampleSnapshotName (scripts.js?version=0.105.1:831)
      at snapshotNameExample (settings.js?version=0.105.1:48)
      at handleSettingsDialog (settings.js?version=0.105.1:199)
      at Object.success (scripts.js?version=0.105.1:200)
      at u (jquery.js?version=0.105.1:2)
      at Object.fireWith [as resolveWith] (jquery.js?version=0.105.1:2)
      at k (jquery.js?version=0.105.1:2)
      at XMLHttpRequest.<anonymous> (jquery.js?version=0.105.1:2)
  exampleSnapshotName	@	scripts.js?version=0.105.1:831
  snapshotNameExample	@	settings.js?version=0.105.1:48
  handleSettingsDialog	@	settings.js?version=0.105.1:199
  success	@	scripts.js?version=0.105.1:200
  u	@	jquery.js?version=0.105.1:2
  fireWith	@	jquery.js?version=0.105.1:2
  k	@	jquery.js?version=0.105.1:2
  (anonymous)	@	jquery.js?version=0.105.1:2
  load (async)		
  send	@	jquery.js?version=0.105.1:2
  ajax	@	jquery.js?version=0.105.1:2
  w.<computed>	@	jquery.js?version=0.105.1:2
  postJson	@	scripts.js?version=0.105.1:184
  loadSettings	@	settings.js?version=0.105.1:118
  onclick	@	(index):1708
```

**Comment by sabeechen** [comment] 2021-09-08 15:11
I suspect that the browser cache is not getting invalidated for the UI in the new version.  I'll need to look into why.

I suspect if you press <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>R</kbd> in the web-ui, which makes Chrome refresh without using the cache, then this problem will go away.

**Comment by Mr-Groch** [comment] 2021-09-08 15:21
> I suspect that the browser cache is not getting invalidated for the UI in the new version. I'll need to look into why.
> 
> I suspect if you press CTRL+SHIFT+R in the web-ui, which makes Chrome refresh without using the cache, then this problem will go away.

Tried that key combination in Chrome and HA Chrome App - problem still there...

**Comment by loomyr** [comment] 2021-09-08 15:27
Also tried CTRL+SHIFT+R 

Still not working.

Maybe related to latest HA monthly update? Last time I was connected successfully was with the latest 2021.8 update. 

But unfortunately I could not say if the Brave browser was also updated in the meanwhile.

**Comment by loomyr** [comment] 2021-09-08 15:39
Browser version :
```
Brave is up to date
Version 1.29.77 Chromium: 93.0.4577.63 (Official Build) (64-bit)
```
```
Google Chrome is up to date
Version 93.0.4577.63 (Official Build) (64-bit)
```
Clearing complete Chrome cache (cookies, history etc.) => not working
After a complete uninstall/reinstall of my Chrome browser => the page is re-working again correctly. 

As Brave is my main browser, I did not yet clear complete cookies neither reinstall it. I need to be sure that I have all my settings backed up before testing.

**Comment by sabeechen** [comment] 2021-09-08 15:53
I'm 99% confident at this point that this is a browser cache issue.  Explains why it works in some browsers, works after reinstalling, etc.  I still don't know why chrome in particular is caching so aggressively.

If you clear the cache in chrome (or other browsers derived from chrome, eg brave)  make sure you select the time period "all time" and you should only need to delete "Cached images and files", eg:
![image](https://user-images.githubusercontent.com/21026774/132542526-6653c52e-1336-4680-82bf-9824d88781ce.png)


If that still doesn't work, try opening the web-ui in an incognito tab.

**Comment by loomyr** [comment] 2021-09-08 15:57
cleared as you mentionned :
![image](https://user-images.githubusercontent.com/73883405/132543571-af378f71-8f2a-447d-b301-2741c9fab220.png)
but still not working

**Comment by loomyr** [comment] 2021-09-08 16:05
Private window : 
![image](https://user-images.githubusercontent.com/73883405/132544595-e30619d5-2f89-40c5-9dbe-ea582c808592.png)

**Comment by sabeechen** [comment] 2021-09-08 16:08
Alright, last attempt before I have to accept that maybe this isn't a cache problem:
* <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>J</kbd> to open the console
* Go to the "Network" tab
* Select "Disable cache"
  ![image](https://user-images.githubusercontent.com/21026774/132544694-334bd9e7-8076-4f1b-ba30-47d7afb8568b.png)
* Refresh the page
* Profit?


Thanks for bearing with me!

**Comment by loomyr** [comment] 2021-09-08 16:10
Issue still exists :
![image](https://user-images.githubusercontent.com/73883405/132545483-12acc081-c941-4254-a60e-bcf06cf9d81d.png)

**Comment by loomyr** [comment] 2021-09-08 16:14
Issue still exists :
![image](https://user-images.githubusercontent.com/73883405/132546010-6fc63f73-b321-48ee-8ae5-ea3f8ae43163.png)

**Comment by sabeechen** [comment] 2021-09-08 16:14
Does the page still have the javascript errors from before, eg ```(index):1781 Uncaught ReferenceError: newBackupClick is not defined``` when you click the new backup button?

**Comment by loomyr** [comment] 2021-09-08 16:15
yes exactly the same warnings & errors that I have mentioned above.

**Comment by loomyr** [comment] 2021-09-08 16:35
well... same as for Chrome.
Brave : 
Clear data only => not working
Clear data, cookies and history => not working
Private windows after clearing everything => not working
Uninstall and Resinstall Brave browser => OK it works!

**Comment by sabeechen** [comment] 2021-09-08 16:42
This is very suprising.
* In that screenshot, its referencing javascript from a file ```scripts.js?version=0.104.3```, but using the latest version of the addon, it should only be *possible* for it to ask for files using the new version, eg ```scripts.js?version=0.105.1```.
* The website root page (eg the ```index``` page) clearly has the most recent changes, because its looking for the ```newBackupClick``` method, which only exists in v0.105.1.  All of these changes were made as part of the same [commit](https://github.com/sabeechen/hassio-google-drive-backup/commit/60f153d6ac82241069d588e387aeb527769e36ed#diff-e80ec33961f28ec3a0884ac596353c7ea19e75f938d8da90d92243f8b69ea7f4R847).  It shouldn't be possible for the ```index``` page to reference the *old* verison number.

I don't want to jump to this conclusion, but I'm having trouble understanding how this could be happening without a browser cache bug.  Reinstalling the browser shouldn't do anything to the cache that simply clearing the cache doesn't do.

I'm going to try to reproduce this bug myself in Brave and Chrome, but it will take me some time because I'll have to set up HA instances to do it.  If anyone else is seeing this issue and has any insight into it, please chime in.

**Comment by philclifford** [comment] 2021-09-08 16:47
Uninstall and reinstall worked for me today with Chrome. Saw nothing helpful in logs etc and updated core/restarted/rebooted. Only re-install fixed it right away.  Only had the problem on my VM instance not on my "bare-metal" RaspberryPi 

RasPi worked:
core-2021.10.0.dev20210908
supervisor-2021.09.dev0601
Home Assistant OS 7.0.dev20210904

VM Stuck until re-installed:
core-2021.9.4
supervisor-2021.09.0 (beta channel)
Home Assistant OS 6.3

I doubt it's browser cache because same browser, same cache, two tabs one with the eternal waiting message, one working fine.  I tried doing a backup on the stuck one in HA supervisor and that worked and synced to Google but didn't un-block things.

**Comment by loomyr** [comment] 2021-09-08 17:09
I had in the past the same behaviour with another custom HA component (browser_mod) when they changed their component on how were the popup windows action handled. Same as here, an old .js that were not called correctly on the browser side and that letting the developer thinking the issue came from a cache issue. 

All cache clearing and cookies (even private windows) actions didn't help to fix the issue. 

As private windows is a separated session container, where no cache should link with the regular session, and where the cache should be usually gone after closing the windows I was as well surprised that it does not help to resolve a simple cache issue, and share your thoughts as well. 

But the facts was that only uninstall/reinstall of the browser on the computer was able to fix the issue.

**Comment by Mr-Groch** [comment] 2021-09-08 21:10
Addon reinstall worked for me. I had to authentcate with Google Drive again and finish setup wizard, but after that addon web ui is displayed OK on all my browsers and in HA app

**Comment by sysrun** [comment] 2021-09-09 12:13
Can confirm: Reinstall worked. Looks like there is some problem with the migration

**Comment by sabeechen** [comment] 2021-09-09 14:45
Here is a summary of what users have reported resolves this.  Not everything works for everyone:

* Waiting a few hours
* Clearing the browser cache completely
* Uninstalling and reinstalling chrome
* Using a different browser
* Uninstalling and reinstalling the addon

This *appears* to be a caching problem in chrome and chromium based browsers, but its far from clear if its a bug in chrome or something the addon is doing wrong.  If you have any insight into what is going on here, please chime in while I try to figure it out.

**Comment by BertrumUK** [comment] 2021-09-09 15:08
I’m seeing the same issue on iOS safari. Same HA instance on the iPad works fine but not on my phone.

**Comment by sabeechen** [comment] 2021-09-09 16:19
I guess then its just firefox that doesn't show the problem.  Since both safari and chrome are affected, its probably not a bug in the browser.  Probably then its something the addon is doing.

I tried:

- Installing a clean version of chrome.
- Installing an old version of the addon (around 0.104)
- Using the website in chrome
- Updating the addon to 0.105
- Using the website with the new addon

And saw no problems, everything working as expected.  Nothing I've done to reproduce this has gotten me close.  Is it possible you guys have a browser extension that might be causing the problem?  I'm willing to try anything at this point, all the information I have about it is in this thread and its not getting me anywhere.

**Comment by BertrumUK** [comment] 2021-09-09 16:46
Here is a screen capture of my phone trying to log it. The addon seems to stutter when loading. 

https://user-images.githubusercontent.com/22644029/132727890-c1c88638-2c61-486a-9abb-8355339250f6.MP4

**Comment by mjmccans** [comment] 2021-09-09 16:59
I am not sure if this is a helpful data point, but I am seeing this same issue in the Home Assistant App on Android but not in Chrome on the same device. I do not have any plugins installed, but in any event I would expect that the app is using a webview component (although I could be totally wrong there as I have not looked at the source code).

**Comment by EpicLPer** [comment] 2021-09-10 17:30
This is happening on all my devices that I tried to load the page on. Additional to that if I click on the "Logs" button I'm being booted to a page saying "The page has been moved permanently".
![image](https://user-images.githubusercontent.com/8442196/132893940-ab87d634-a5c4-41b1-85e5-af35cac854a4.png)

**Comment by sabeechen** [comment] 2021-09-12 16:59
All of my attempts to reproduce this have failed.  Every combination of version upgrade and browser I've used fails to cause any problem.  That means that the only way I have to debug this is through you guys, unless I can find a way to reproduce it.  To summarize for those running into the problem, what appears to work best to resolve this is:

* Uninstall and reinstall the addon (save your setting somwhere, and you'll need to "reconnect" with Google Drive)
* Reinstall your browser

To anyone willing to help me dig into this, I'm writing the following questions assuming you know your way around Chromium's dev windows.  I think the only way I'm going to be able make any progress on figuring this out is to have one of you debug your installation for me.  Being able to answer the following might help:
1. What address is the web-ui using to fetch its scripts form Home Assistant?  You should see a request in chrome's network tab for an address similar to 
   ```
   http://<ha_ip>/api/hassio_ingress/<long_string_of_numbers_and_digits>/static/js/scripts.js?version=0.105.1
   ```
2. What tag is the web-ui using to load in that script?  If you right click -> "inspect" the addon web-ui, there should be a tag loading the script that looks similar to the following: 
   ```html
   <script src="static/js/scripts.js?version=0.105.1"></script>
   ```
   Note that the HA web interfaces loads the addon web-ui inside an <iframe>, so the script tags will probably toward the middle of the DOM.
3. Every 5 seconds, you should see the addon web-ui make a request to a ```/getstatus``` endpoint in the network tab.  Could you tell me if the field 'backups' is present in the reply json from that request?
4. Please double check there are no errors in the console tab comign from the addon web-ui (The HA web-ui almost always shows some warnings from their scripts).

**Comment by stigvig** [comment] 2021-09-16 20:12
So I've also ran into this problem after upgrading.

Does not work:

- Chrome on Mac
- Chrome on Windows

Works:

- Firefox on Windows
- Safari on Mac
- Safari on iOS
- Chrome on iOS
- Home Assistant App on iOS

One thing to note is that it's usually the first non working option that where I recently accessed the HA before upgrading. I'll refrain from doing anything with my installation just to see if magically will resolve it self.

**Comment by stigvig** [comment] 2021-09-16 20:33
1.  https://<hidden>:8123/api/hassio_ingress/l3kVgXFZaKnRm2UHxuU9o3TzIhQ5xfUfwvW1fqDSzes/static/js/scripts.js?version=0.105.1
2. <script src="static/js/scripts.js?version=0.105.1"></script>
3.  Yes, there is a list of backups

<img width="827" alt="drive" src="https://user-images.githubusercontent.com/917256/133681939-739da11f-4d98-4652-a87a-6fffa68dafde.PNG">

4.  I only get the following warning: The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'

**Comment by stigvig** [comment] 2021-09-16 21:24
So after some debugging I noticed the following. In the function processStatusUpdate in scripts.js the following code was present in my none working Chrome.

```javascript
  if (count == 0) {
    if (!data.firstSync) {
      $("#no_snapshots_block").show();
      $("#snapshots_loading").hide();
    } else {
      $("#snapshots_loading").show();
      $("#no_snapshots_block").hide();
    }
  } else {
    $("#no_snapshots_block").hide();
    $("#snapshots_loading").hide();
  }
```

In Firefox where everything is working the same code looks like this

```javascript
  if (count == 0) {
    if (!data.firstSync) {
      $("#no_backups_block").show();
      $("#backups_loading").hide();
    } else {
      $("#backups_loading").show();
      $("#no_backups_block").hide();
    }
  } else {
    $("#no_backups_block").hide();
    $("#backups_loading").hide();
  }
```
So the Chrome scripts.js seems to be the older version for some reason? So it's a caching issue?

**Comment by sabeechen** [comment] 2021-09-16 23:33
This ... has got to be caching!

thank you for digging into this as far as you have.  Your debugging verifies that the browser is seeing the scripts.js file that was served from a previous update (0.104.3 or earlier).  Most likely all of the resources being loaded are out of date.

I'm going to try to work through this methodically.  The complete path for how a file like this is served, as far as I'm aware, is as follows:
1. The browser loads the main Ha interface, which includes an iframe for the addon with an address like
   ```
   http://homeassistant.local:8123/api/hassio_ingress/XXXXX/
   ```
2. The response for that url is an html page has a script tag, which references an address like 
   ```
   http://ha.local/api/hassio_ingress/XXXXX/static/js/scripts.js?version=0.105.1
   ```
3. The request for the address is first handled by [this code](https://github.com/home-assistant/core/blob/519efd2723f81b7a18df7f1dd7f7a9a24a897df7/homeassistant/components/hassio/ingress.py#L47) in Home Assistant core's webserver.  That is a proxy that [instead requests an address](https://github.com/home-assistant/core/blob/519efd2723f81b7a18df7f1dd7f7a9a24a897df7/homeassistant/components/hassio/ingress.py#L43) like 
   ```
   http://localhost/ingress/XXXXX/js/scripts.ja?version=0.105.1
   ```
4. That request is [handled by the supervisor](https://github.com/home-assistant/supervisor/blob/f4c7f2cae16a1882a2868c12cd4ff2d773305014/supervisor/api/__init__.py#L392), which also [acts as a proxy](https://github.com/home-assistant/supervisor/blob/f4c7f2cae16a1882a2868c12cd4ff2d773305014/supervisor/api/ingress.py#L164) that instead requests the url:
   ```
   http://<internal_addon_ip>/static/js/scripts.js?version=0.105.1
   ```
5. This is finally handled by the addon's webserver [static file mappings](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/hassio-google-drive-backup/backup/ui/uiserver.py#L614), which reads the file bytes and returns them.  Those bytes then get passed up through all the various proxys described above and returned to your browser.

With every release of the addon, I bump the version number at the end of referenced static files to ensure that their contents never get cached between updates.  This is a common practice called cache busting.
- The fact that your browser is asking for ```scripts.js``` with ```version=0.105.1``` appended indicates that this mechanism and everything in (1) & (2) is working correctly.
- The proxy in HA and the supervisor use [aiohttp's websession](https://docs.aiohttp.org/en/stable/client_reference.html) to make their internal requests, which AFAIK has no mechanism to do any request content caching.  I also don't see an mechanism implemented in HA or the supervisor to do any caching, they just pass any request through and stream the results back.  This leads me to be confidant that (3) and (4) are not the problem.
- I've verified that the file /app/backup/static/js/scripts.js in my addon's docker container for the latest release published to docker hub (eg ```sabeechen/hassio-google-drive-backup-amd64:0.105.1```) has the updated file contents, so I'm also confident that my addon's webserver is not serving the old file in (5).

I'm left thinking that the browser is the _only freaking place_ this caching could be happening.  It would explain why:
- Reinstalling the the browser fixes it - because reinstalling destroys the browser's cache.
- Using a different browser fixes it - because presumably a different browser hasn't ever attempted to ask for the file before, so it isn't cached.
- Reinstalling the addon fixes it - because reinstalling will change the ```XXXX``` parameter part of the paths above, so the browser sees it as a new file that isn't in its cache.

What it doesn't explain is why clearing the browser cache doesn't work for everyone.  The only things I could think of to explain that are:
- There is a cache bug affecting multiple browsers made from completely independent code bases (Chromium and Safari)
- Browser caches simply don't work the way I think they do.

Both of which seem extremely unlikely.

**Comment by sabeechen** [comment] 2021-09-16 23:35
I think that something I can do is make a new release that renames the resource files the addon loads.  I'm not sure why the updated files are getting cached so aggressively, why it only happened with this release, or why it only affects some people.  It seems likely I'll never get to the bottom of it, and I should just rename the resources files in all subsequent releases to completely avoid the problem.

**Comment by sabeechen** [comment] 2021-09-17 07:56
I just published v0.105.2 of the addon, which includes logic that puts all the static resources behind URL's that include the addon version number in their path instead of in the query string they were using before.  I hope and believe this will mitigate any browser caching issues you guys have been having.

If anyone in this thread is still seeing this problem, please let me know if the new version resolves it without having to reinstall the addon or your browser.

If Home Assistant doesn't see the updated addon, make sure you reload the addon store (menu at the top right of the addon store page) to force a check for new versions.

**Comment by NicolasRigo** [comment] 2021-09-17 08:06
Hi there,

Upgrading to v0.105.2 solved the issue for me.

I am running on a Mac and accessing HA with Safari.

Thanks a lot for the good job.

Cheers

**Comment by sabeechen** [comment] 2021-09-17 08:13
That's great to hear, bugs like this weigh on me.  If it's working now for anyone else don't hesitate to chime in, the faster I get solid confirmations the sooner I can consider the issue closed.

**Comment by mjmccans** [comment] 2021-09-17 13:23
The new version has solved the issue for me as well in both the Android app and in Chrome on my desktop. The effort by all to solve this issue is greatly appreciated.

**Comment by stigvig** [comment] 2021-09-17 14:14
Great work @sabeechen.

One final update on my findings.

Changing the version number to the path seems like the correct way to solve this issue as Chrome seems to ignore the query string when caching. I looked in my cache and found that 104.3 was still used. I then deleted only scripts.js and then the page loaded correctly. See image below. This after deletion of scripts.js and a refresh. Other files are still cached to the old version.

<img width="1467" alt="cache" src="https://user-images.githubusercontent.com/917256/133796944-af4dd518-b927-4cad-af25-db22da722471.PNG">

**Comment by sabeechen** [comment] 2021-09-17 15:45
This could mean this has been a problem in every update I've ever made to the addon, and perhaps it was only so noticeable this time because changing all the addon's javascript to reference 'backup' instead of 'snapshot' broke the web UI enough between version that it wasn't useable.  Likely I've had users just quietly ignoring new features that didn't show up or work in new releases when their browser cached an old version of the web-ui.

I still don't think I have a handle on why I wasn't able to make this happen in any of my browsers, or why it only seemed to happen for some people, but I think this is as much of an explanation as I can hope for.

Thanks everyone who reported their findings.  Especially @stigvig and @loomyr for doing the digging you did, it would've taken a lot more time, guessing, and releases to fix this if I didn't have the details ya'll provided.

If anyone is still seeing this problem after updating to the latest version, please feel free to post here or reopen the issue and I'll take a look.

**Closed by sabeechen** 2021-09-17 15:45 UTC
Labels: bug
