### ISSUE TITLE
Please add a title

### ISSUE THREAD

**Issue by Master63** [sabeechen/hassio-google-drive-backup#721] opened 2022-09-21 12:42 UTC
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.108.4`
 Home Assistant Version: `2022.9.4`
 Supervisor Version: `2022.09.1`
 Supervisor Channel: `stable`
 Hassos Version: `8.4`
 Docker Version: `20.10.14`
 Architecture: `aarch64`
 Machine: `raspberrypi4-64`
 Date: `2022-09-21T12:40:52.670394+00:00`
 Timezone: `Europe/Berlin`
 Failure Time: `2022-09-21T12:22:12.441305+00:00`
 Last Good Sync: `2022-09-21T12:22:11.897950+00:00`
 ###### Exception:
 ```
 
  addon/backup/model/coordinator.py:177 (_sync)
  addon/backup/model/model.py:224 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:227 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:35 (_request)
  /site-packages/aiohttp/client.py:559 (_request)
  /site-packages/aiohttp/client_reqrep.py:898 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 3,
        "retained": 0,
        "deletable": 3,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2022-09-21T12:21:54Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "detail": "",
        "size": "2.7 MB",
        "ignored_size": "0.0 B",
        "free_space": "22.8 GB"
    },
    "GoogleDrive": {
        "backups": 2,
        "retained": 0,
        "deletable": 2,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2022-09-21T12:21:54Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "detail": "karoljasny59@gmail.com",
        "size": "5.3 MB",
        "ignored_size": "0.0 B",
        "free_space": "14.9 GB"
    }
}
 ```
 ###### Config:
 ```
 {}
 ```
 ###### Addon Logs:
 ```
 09-21 14:22:06 DEBUG [backup.worker.watcher] Backup directory modified event
09-21 14:22:06 INFO [backup.ha.hasource] Backup finished
09-21 14:22:06 DEBUG [backup.model.syncer] Sync requested by HomeAssistant
09-21 14:22:06 INFO [backup.model.coordinator] Syncing Backups
09-21 14:22:06 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
09-21 14:22:06 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
09-21 14:22:06 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups/521a3dc1/info
09-21 14:22:06 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota%2Cuser
09-21 14:22:07 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271jlc_FTnPEE9Usv7NIJgmxpOlTCCaLAf2%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
09-21 14:22:07 INFO [backup.drive.drivesource] Uploading 'Full Backup 2022-09-21 14:21:53' to Google Drive
09-21 14:22:07 DEBUG [backup.drive.driverequests] Starting a new upload session with Google Drive
09-21 14:22:07 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true
09-21 14:22:08 DEBUG [backup.drive.driverequests] Sending 262144 bytes to Google Drive
09-21 14:22:08 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdsfvmvdKhpT9FiafQc758MoPgRF3L6YGzzqpC3tVOqqMdDtrfUsqc9XN1tAQusfVSItflVhw4yfU9bd3J2WxD-p_qCoYvpw
09-21 14:22:08 DEBUG [backup.drive.drivesource] Uploading Full Backup 2022-09-21 14:21:53 9.18%
09-21 14:22:08 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
09-21 14:22:08 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdsfvmvdKhpT9FiafQc758MoPgRF3L6YGzzqpC3tVOqqMdDtrfUsqc9XN1tAQusfVSItflVhw4yfU9bd3J2WxD-p_qCoYvpw
09-21 14:22:11 DEBUG [backup.drive.drivesource] Uploading Full Backup 2022-09-21 14:21:53 100.00%
09-21 14:22:11 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1xffwe-Oxg4qmtxG_lSkqBpQWnc98QvaX/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
09-21 14:22:11 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:177 (_sync)
  addon/backup/model/model.py:224 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:227 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:35 (_request)
  /site-packages/aiohttp/client.py:559 (_request)
  /site-packages/aiohttp/client_reqrep.py:898 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

09-21 14:22:11 INFO [backup.model.coordinator] I'll try again in 21(ish) minutes
09-21 14:22:11 INFO [backup.worker.watcher] Backup directory changed
09-21 14:22:11 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
09-21 14:22:11 INFO [backup.model.coordinator] Syncing Backups
09-21 14:22:11 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
09-21 14:22:11 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
09-21 14:22:11 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota%2Cuser
09-21 14:22:12 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271jlc_FTnPEE9Usv7NIJgmxpOlTCCaLAf2%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
09-21 14:22:12 ERROR [backup.model.coordinator] 
  addon/backup/model/coordinator.py:177 (_sync)
  addon/backup/model/model.py:224 (sync)
  addon/backup/drive/drivesource.py:194 (save)
  addon/backup/util/asynchttpgetter.py:227 (__aenter__)
  addon/backup/util/asynchttpgetter.py:61 (setup)
  addon/backup/util/asynchttpgetter.py:167 (_startReadRemoteAt)
  addon/backup/tracing_session.py:35 (_request)
  /site-packages/aiohttp/client.py:559 (_request)
  /site-packages/aiohttp/client_reqrep.py:898 (start)
  /site-packages/aiohttp/streams.py:616 (read)
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

09-21 14:22:12 INFO [backup.model.coordinator] I'll try again in 42(ish) minutes
 ```
 ###### Supervisor Logs:
 ```
   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
FileNotFoundError: [Errno 2] No such file or directory: '/data/backup/9d8b6b73.tar'
[32m22-09-21 14:22:11 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-09-21 14:22:11 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-09-21 14:22:12 INFO (MainThread) [supervisor.api.middleware.security] /backups/9d8b6b73/download access from cebe7a76_hassio_google_drive_backup[0m
[32m22-09-21 14:22:12 INFO (MainThread) [supervisor.api.backups] Downloading backup 9d8b6b73[0m
[31m22-09-21 14:22:12 ERROR (MainThread) [aiohttp.server] Unhandled exception[0m
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 514, in start
    resp, reset = await task
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 460, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 613, in finish_response
    await prepare_meth(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_fileresponse.py", line 142, in prepare
    st: os.stat_result = await loop.run_in_executor(None, filepath.stat)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
FileNotFoundError: [Errno 2] No such file or directory: '/data/backup/9d8b6b73.tar'
[32m22-09-21 14:22:49 INFO (MainThread) [supervisor.backups.manager] Found 1 backup files[0m
[32m22-09-21 14:22:49 INFO (MainThread) [supervisor.backups.manager] Found 1 backup files[0m
[32m22-09-21 14:23:43 INFO (MainThread) [supervisor.backups.manager] Found 1 backup files[0m
[32m22-09-21 14:23:43 INFO (MainThread) [supervisor.backups.manager] Found 1 backup files[0m
[32m22-09-21 14:40:52 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 [31m2022-09-21 03:54:11.354 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"[0m
[33m2022-09-21 14:11:19.553 WARNING (MainThread) [homeassistant.components.http] The 'base_url' option near /config/configuration.yaml:13 is deprecated, please remove it from your configuration[0m
s6-rc: info: service legacy-services: stopping
[31m2022-09-21 14:11:28.664 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /homeassistant/restart request Server disconnected[0m
[12:11:30] INFO: [32mHome Assistant Core finish process exit code 0[0m
[12:11:30] INFO: [32mHome Assistant Core service shutdown[0m
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun home-assistant (no readiness notification)
s6-rc: info: service legacy-services successfully started
[33m2022-09-21 14:11:49.030 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant[0m
[33m2022-09-21 14:11:49.303 WARNING (MainThread) [homeassistant.components.http] The 'base_url' option near /config/configuration.yaml:13 is deprecated, please remove it from your configuration[0m

 ```

**Comment by sabeechen** [comment] 2022-09-28 11:33
Sorry it took me a while to get to you.

I think the cause of the error is this line in your supervisor logs:
```
FileNotFoundError: [Errno 2] No such file or directory: '/data/backup/9d8b6b73.tar'
```

For some reason, Home Assistant is expecting a backup file to be present but its gone when it attempts to read the file.  I'm not sure why this could happen, as I've never seen the error before, but I suspect you could resolve it by restarting the machine running Home assistant.  I'm seen times when the caches Home assistant keeps get messed up and a restart usually resolves it.

**Comment by sabeechen** [comment] 2022-11-08 06:12
Closing this for now, but feel free to reopen it if you think there is something else I can help with.

**Closed by sabeechen** 2022-11-08 06:12 UTC
