### ISSUE TITLE
Hassio system log full of pinging the binary sensor every 10 seconds.

### ISSUE THREAD

**Issue by x99percent** [sabeechen/hassio-google-drive-backup#13] opened 2019-04-03 05:22 UTC
Does it really need to be hitting the sensor so often? Can this be fixed, or can I disable the sensor?

`19-04-03 01:06:28 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:06:38 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:06:48 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:06:58 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:07:08 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:07:18 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:07:28 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:07:38 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:07:48 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:07:58 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:08:08 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:08:18 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:08:28 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:08:38 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:08:48 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:08:58 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:09:08 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:09:18 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:09:28 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:09:38 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:09:48 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:09:58 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:10:08 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:10:18 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:10:28 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup
19-04-03 01:10:38 INFO (MainThread) [hassio.api.proxy] /homeassistant/api/states/binary_sensor.snapshots_stale access from cebe7a76_hassio_google_drive_backup`

**Comment by sabeechen** [comment] 2019-04-03 06:17
This has been an [issue with Hassio](https://github.com/home-assistant/hassio/issues/865) for some time but doesn't seem to have gotten their attention.  I've offered to make a PR with the Hassio folks to downgrade the logging to DEBUG, so I'll wait to see what they say.

If they don't get back, I'll ... do something.  The issue is that the add-on doesn't know if Home Assistant has been restarted, which wipes out the sensor state.  I haven't found a mechanism to persist a binary_sensor across restarts, so instead I just publish the state often.  Unfortunately any mechanism I use to *check* if the sensor was already created would suffer from the same API logging problem.  If I can't sort it out with them I'll probably just make a PR and see if someone gets back.  Failing that, I'll make the interval it publishes at configurable for you.

**Comment by sabeechen** [comment] 2019-04-05 17:05
I made a [PR](https://github.com/home-assistant/hassio/pull/992) for this with Hassio and it got approved last night, so it should be included with the next version of Hassio.  I'll keep this open until I can verify it's in.

**Comment by x99percent** [comment] 2019-04-05 22:48
Thank you for following up!

**Comment by sabeechen** [comment] 2019-04-16 18:01
The PR seems to be in the latest Hass.io release, so I'll close this issue out now.

**Closed by sabeechen** 2019-04-16 18:01 UTC
