### ISSUE TITLE
Unable to connect to www.googleapis.com

### ISSUE THREAD

**Issue by AleksandrBraun** [sabeechen/hassio-google-drive-backup#414] opened 2021-06-15 06:12 UTC
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.104.3`
 Home Assistant Version: `2021.6.4`
 Supervisor Version: `2021.06.0`
 Supervisor Channel: `stable`
 Hassos Version: `None`
 Docker Version: `20.10.7`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2021-06-15T06:09:19.946171+00:00`
 Timezone: `Europe/Kiev`
 Failure Time: `2021-06-15T06:07:15.789669+00:00`
 Last Good Sync: `2021-06-15T06:07:35.840190+00:00`
 ###### Exception:
 ```
 
  addon/backup/creds/driverequester.py:30 (request)
  addon/backup/tracing_session.py:20 (_request)
  /site-packages/aiohttp/client.py:520 (_request)
  [4 hidden frames]
  /site-packages/aiohttp/connector.py:975 (_wrap_create_connection)
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.googleapis.com:443 ssl:default [Connect call failed ('142.250.180.234', 443)]
Whose handling caused:
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:261 (_syncSnapshots)
  addon/backup/drive/drivesource.py:101 (get)
  addon/backup/drive/drivesource.py:220 (getFolderId)
  addon/backup/drive/folderfinder.py:65 (get)
  addon/backup/drive/folderfinder.py:117 (_readFolderId)
  addon/backup/drive/folderfinder.py:158 (_verify)
  addon/backup/drive/driverequests.py:150 (get)
  addon/backup/drive/driverequests.py:351 (retryRequest)
  addon/backup/creds/driverequester.py:49 (request)
backup.exceptions.exceptions.GoogleCantConnect

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 1,
        "retained": 0,
        "deletable": 1,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2021-06-12T23:01:01Z",
        "max": 2,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "299.0 MB",
        "ignored_size": "0.0 B",
        "free_space": "73.0 GB"
    },
    "GoogleDrive": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 12,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "0.0 B",
        "ignored_size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_HASSIO": 2,
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 12,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 1.0,
    "Setting.SNAPSHOT_TIME_OF_DAY": "02:01",
    "Setting.SPECIFY_SNAPSHOT_FOLDER": true,
    "Setting.BACKGROUND_COLOR": "#1a181a",
    "Setting.ACCENT_COLOR": "#1f1f1f"
}
 ```
 ###### Addon Logs:
 ```
 06-15 09:03:44 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
06-15 09:03:44 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
06-15 09:03:44 INFO [backup.ui.uiserver] Starting server on port 8099
06-15 09:03:44 INFO [backup.ui.uiserver] Server started
06-15 09:03:44 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-15 09:03:44 INFO [backup.model.coordinator] Syncing Snapshots
06-15 09:03:44 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
06-15 09:03:44 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/90a16c89/info
06-15 09:03:44 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1RhnQumAws9bvakrDlljnjn6FjpMcDEoH/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
06-15 09:04:13 DEBUG [backup.creds.driverequester] Ran into trouble reaching Google Drive's servers.  We'll use alternate DNS servers on the next attempt.
06-15 09:04:13 ERROR [backup.model.coordinator] Unable to connect to www.googleapis.com
06-15 09:04:13 INFO [backup.model.coordinator] I'll try again right now
06-15 09:04:14 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-15 09:04:14 INFO [backup.model.coordinator] Syncing Snapshots
06-15 09:04:14 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
06-15 09:04:14 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1RhnQumAws9bvakrDlljnjn6FjpMcDEoH/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
06-15 09:06:44 DEBUG [backup.creds.driverequester] Ran into trouble reaching Google Drive's servers.  We'll use alternate DNS servers on the next attempt.
06-15 09:06:44 ERROR [backup.model.coordinator] Unable to connect to www.googleapis.com
06-15 09:06:44 INFO [backup.model.coordinator] I'll try again in 10 seconds
06-15 09:06:54 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-15 09:06:54 INFO [backup.model.coordinator] Syncing Snapshots
06-15 09:06:54 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
06-15 09:06:54 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1RhnQumAws9bvakrDlljnjn6FjpMcDEoH/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
06-15 09:07:15 DEBUG [backup.creds.driverequester] Ran into trouble reaching Google Drive's servers.  We'll use alternate DNS servers on the next attempt.
06-15 09:07:15 ERROR [backup.model.coordinator] Unable to connect to www.googleapis.com
06-15 09:07:15 INFO [backup.model.coordinator] I'll try again in 20 seconds
06-15 09:07:35 DEBUG [backup.model.syncer] Sync requested by Coordinator
06-15 09:07:35 INFO [backup.model.coordinator] Syncing Snapshots
06-15 09:07:35 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
06-15 09:07:35 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1RhnQumAws9bvakrDlljnjn6FjpMcDEoH/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
 ```
 ###### Supervisor Logs:
 ```
 [32m21-06-15 06:03:43 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on sabeechen/hassio-google-drive-backup-amd64 with version 0.104.3[0m
[32m21-06-15 06:03:44 INFO (MainThread) [supervisor.api.middleware_security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-06-15 06:03:44 INFO (MainThread) [supervisor.api.middleware_security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-06-15 06:03:44 INFO (MainThread) [supervisor.api.middleware_security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-06-15 06:03:44 INFO (MainThread) [supervisor.api.middleware_security] /snapshots/90a16c89/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-06-15 06:04:14 INFO (MainThread) [supervisor.api.middleware_security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[33m21-06-15 06:04:41 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with Multicast plugin![0m
[32m21-06-15 06:04:41 INFO (MainThread) [supervisor.plugins.multicast] Starting Multicast plugin[0m
[32m21-06-15 06:04:41 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning hassio_multicast application[0m
[32m21-06-15 06:04:42 INFO (SyncWorker_6) [supervisor.docker.multicast] Starting Multicast homeassistant/amd64-hassio-multicast with version 2021.04.0 - Host[0m
[33m21-06-15 06:05:42 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with Multicast plugin![0m
[32m21-06-15 06:05:42 INFO (MainThread) [supervisor.plugins.multicast] Starting Multicast plugin[0m
[32m21-06-15 06:05:42 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning hassio_multicast application[0m
[32m21-06-15 06:05:42 INFO (SyncWorker_1) [supervisor.docker.multicast] Starting Multicast homeassistant/amd64-hassio-multicast with version 2021.04.0 - Host[0m
[33m21-06-15 06:06:42 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with Multicast plugin![0m
[32m21-06-15 06:06:42 INFO (MainThread) [supervisor.plugins.multicast] Starting Multicast plugin[0m
[32m21-06-15 06:06:42 INFO (SyncWorker_3) [supervisor.docker.interface] Cleaning hassio_multicast application[0m
[32m21-06-15 06:06:42 INFO (SyncWorker_3) [supervisor.docker.multicast] Starting Multicast homeassistant/amd64-hassio-multicast with version 2021.04.0 - Host[0m
[32m21-06-15 06:06:54 INFO (MainThread) [supervisor.api.middleware_security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-06-15 06:07:35 INFO (MainThread) [supervisor.api.middleware_security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[33m21-06-15 06:07:42 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with Multicast plugin![0m
[32m21-06-15 06:07:42 INFO (MainThread) [supervisor.plugins.multicast] Starting Multicast plugin[0m
[32m21-06-15 06:07:42 INFO (SyncWorker_7) [supervisor.docker.interface] Cleaning hassio_multicast application[0m
[32m21-06-15 06:07:43 INFO (SyncWorker_7) [supervisor.docker.multicast] Starting Multicast homeassistant/amd64-hassio-multicast with version 2021.04.0 - Host[0m
[33m21-06-15 06:08:43 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with Multicast plugin![0m
[32m21-06-15 06:08:43 INFO (MainThread) [supervisor.plugins.multicast] Starting Multicast plugin[0m
[32m21-06-15 06:08:43 INFO (SyncWorker_0) [supervisor.docker.interface] Cleaning hassio_multicast application[0m
[32m21-06-15 06:08:43 INFO (SyncWorker_0) [supervisor.docker.multicast] Starting Multicast homeassistant/amd64-hassio-multicast with version 2021.04.0 - Host[0m
[32m21-06-15 06:09:19 INFO (MainThread) [supervisor.api.middleware_security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to MySQL server on 'core-mariadb' (115)")
(Background on this error at: http://sqlalche.me/e/14/e3q8)[0m
[31m2021-06-15 09:09:13 ERROR (Recorder) [homeassistant.components.recorder] Error in database connectivity during commit: Error executing query: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to MySQL server on 'core-mariadb' (115)")
(Background on this error at: http://sqlalche.me/e/14/e3q8). (retrying in 3 seconds)[0m
[31m2021-06-15 09:09:13 ERROR (SyncWorker_0) [homeassistant.components.sql.sensor] Error executing query SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema LIMIT 1;: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to MySQL server on 'core-mariadb' (115)")
(Background on this error at: http://sqlalche.me/e/14/e3q8)[0m
[31m2021-06-15 09:09:16 ERROR (Recorder) [homeassistant.components.recorder] SQLAlchemyError error processing event <Event time_changed[L]: now=2021-06-15T09:09:13.000449+03:00>: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to MySQL server on 'core-mariadb' (115)")
(Background on this error at: http://sqlalche.me/e/14/e3q8) (Background on this error at: http://sqlalche.me/e/14/7s2a)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 630, in _process_one_event_or_recover
    self._process_one_event(event)
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 750, in _process_one_event
    self._commit_event_session_or_retry()
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 813, in _commit_event_session_or_retry
    self._commit_event_session()
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 839, in _commit_event_session
    self.event_session.commit()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 824, in commit
    self._assert_active(prepared_ok=True)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 598, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to MySQL server on 'core-mariadb' (115)")
(Background on this error at: http://sqlalche.me/e/14/e3q8) (Background on this error at: http://sqlalche.me/e/14/7s2a)[0m

 ```

**Comment by sabeechen** [comment] 2021-06-16 18:25
Your addon is having trouble reaching Google Drive over the internet.  Based on your logs, it just looks like Google is not responding and the connection is timing out.   Many things can cause this:

- You're internet has gone down temporarily.
- Something on your network is blocking connections to www.googleapis.com (eg your router or an ad blocking DNS server)
- Home Assistant's Supervisor has a corrupted internal network.

I've seen others have this problem, and it is very difficult to find a root cause.  For most the problem eventually goes away and we've never figured out what caused it.  As a first step I'd recommend restarting Home Assistant's host machine, since its possible the internal network Home Assistant creates for the addon has gotten into a bad state.

**Comment by sabeechen** [comment] 2021-09-17 16:09
I'm going to close this for now, but please feel free to reopen it if you think there is something else I can help with.

**Closed by sabeechen** 2021-09-17 16:09 UTC

**Comment by AleksandrBraun** [comment] 2021-09-22 05:37
Thank you.
All work now. HA problem resolved.
