### ISSUE TITLE
Unable to delete a snapshot

### ISSUE THREAD

**Issue by drmaq** [sabeechen/hassio-google-drive-backup#413] opened 2021-06-15 01:17 UTC
Copy the info from the previous page here
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.104.3`
 Home Assistant Version: `2021.6.3`
 Supervisor Version: `2021.06.0`
 Supervisor Channel: `stable`
 Hassos Version: `6.0`
 Docker Version: `20.10.6`
 Architecture: `aarch64`
 Machine: `raspberrypi4-64`
 Date: `2021-06-15T01:13:34.658930+00:00`
 Timezone: `America/New_York`
 Failure Time: `2021-06-15T01:11:42.997717+00:00`
 Last Good Sync: `2021-06-15T01:11:42.548517+00:00`
 ###### Exception:
 ```
 
  addon/backup/ha/harequests.py:79 (delete)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:226 (_postHassioData)
  addon/backup/ha/harequests.py:181 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://hassio/snapshots/e40be092/remove')
Whose handling caused:
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:174 (sync)
  addon/backup/model/model.py:320 (_purge)
  addon/backup/model/model.py:229 (deleteSnapshot)
  addon/backup/ha/hasource.py:303 (delete)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
  addon/backup/ha/harequests.py:82 (delete)
backup.exceptions.exceptions.HomeAssistantDeleteError

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 5,
        "retained": 0,
        "deletable": 5,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2021-06-15T01:11:57Z",
        "max": 4,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "0.0 B",
        "ignored_size": "0.0 B",
        "free_space": "6.1 GB"
    },
    "GoogleDrive": {
        "snapshots": 30,
        "retained": 0,
        "deletable": 30,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2021-06-14T04:02:32Z",
        "max": 30,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "24.2 GB",
        "ignored_size": "0.0 B",
        "free_space": "82.5 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 30,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 1.0,
    "Setting.SNAPSHOT_TIME_OF_DAY": "00:00",
    "Setting.DELETE_AFTER_UPLOAD": true,
    "Setting.GENERATIONAL_DAYS": 1,
    "Setting.GENERATIONAL_WEEKS": 1,
    "Setting.GENERATIONAL_MONTHS": 4,
    "Setting.GENERATIONAL_YEARS": 52,
    "Setting.BACKGROUND_COLOR": "#000000",
    "Setting.ACCENT_COLOR": "#02f580",
    "Setting.ALTERNATE_DNS_SERVERS": "192.168.1.2"
}
 ```
 ###### Addon Logs:
 ```
 06-14 21:09:50 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
06-14 21:09:50 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1eqqaECodD-0fMh4rzOFdLmaOX1-cfddT/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
06-14 21:09:51 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
06-14 21:09:51 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271eqqaECodD-0fMh4rzOFdLmaOX1-cfddT%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
06-14 21:09:51 ERROR [backup.model.coordinator] The add-on has been configured to delete more than one older snapshots.  Please confirm this by visiting the add-on's web UI or by setting the config option 'confirm_multiple_deletes'=false in your add-on configuration.
06-14 21:09:51 INFO [backup.model.coordinator] I'll try again in an hour
06-14 21:11:29 INFO [backup.model.coordinator] Syncing Snapshots
06-14 21:11:29 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
06-14 21:11:29 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1eqqaECodD-0fMh4rzOFdLmaOX1-cfddT/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
06-14 21:11:29 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
06-14 21:11:29 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271eqqaECodD-0fMh4rzOFdLmaOX1-cfddT%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
06-14 21:11:29 INFO [backup.ha.hasource] Deleting 'core_2021.5.5' from Home Assistant
06-14 21:11:29 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/e40be092/remove
06-14 21:11:30 ERROR [backup.model.coordinator] Home Assistant refused to delete the snapshot.
06-14 21:11:30 INFO [backup.model.coordinator] I'll try again in an hour
06-14 21:11:42 INFO [backup.model.coordinator] Syncing Snapshots
06-14 21:11:42 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
06-14 21:11:42 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/e40be092/info
06-14 21:11:42 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
06-14 21:11:42 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271eqqaECodD-0fMh4rzOFdLmaOX1-cfddT%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
06-14 21:11:42 INFO [backup.ha.hasource] Deleting 'core_2021.5.5' from Home Assistant
06-14 21:11:42 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/e40be092/remove
06-14 21:11:42 ERROR [backup.model.coordinator] Home Assistant refused to delete the snapshot.
06-14 21:11:42 INFO [backup.model.coordinator] I'll try again in an hour
06-14 21:11:57 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
06-14 21:11:57 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/info
06-14 21:11:57 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/core/info
06-14 21:11:57 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/supervisor/info
06-14 21:11:58 INFO [backup.ha.hasource] Requesting a new snapshot
06-14 21:11:58 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots/new/full
 ```
 ###### Supervisor Logs:
 ```
 [32m21-06-15 01:12:02 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_ssh[0m
[32m21-06-15 01:12:04 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_letsencrypt[0m
[32m21-06-15 01:12:05 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_letsencrypt[0m
[32m21-06-15 01:12:06 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_sonweb[0m
[32m21-06-15 01:12:06 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_sonweb[0m
[32m21-06-15 01:12:08 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_nodered[0m
[32m21-06-15 01:12:18 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_nodered[0m
[32m21-06-15 01:12:22 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mosquitto[0m
[32m21-06-15 01:12:22 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mosquitto[0m
[32m21-06-15 01:12:23 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_ftp[0m
[32m21-06-15 01:12:23 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_ftp[0m
[32m21-06-15 01:12:27 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_chrony[0m
[32m21-06-15 01:12:27 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_chrony[0m
[32m21-06-15 01:12:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_logviewer[0m
[32m21-06-15 01:12:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_logviewer[0m
[32m21-06-15 01:12:28 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_samba[0m
[32m21-06-15 01:12:28 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_samba[0m
[32m21-06-15 01:12:29 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on cebe7a76_hassio_google_drive_backup[0m
[32m21-06-15 01:12:29 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon cebe7a76_hassio_google_drive_backup[0m
[32m21-06-15 01:12:29 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_zwavejs2mqtt[0m
[31m21-06-15 01:13:07 ERROR (MainThread) [supervisor.api.ingress] Ingress error: [Errno 104] Connection reset by peer[0m
[31m21-06-15 01:13:17 ERROR (MainThread) [supervisor.api.ingress] Ingress error: [Errno 104] Connection reset by peer[0m
[31m21-06-15 01:13:19 ERROR (MainThread) [supervisor.api.ingress] Ingress error: [Errno 104] Connection reset by peer[0m
[31m21-06-15 01:13:23 ERROR (MainThread) [supervisor.api.ingress] Ingress error: [Errno 104] Connection reset by peer[0m
[31m21-06-15 01:13:27 ERROR (MainThread) [supervisor.api.ingress] Ingress error: [Errno 104] Connection reset by peer[0m
[31m21-06-15 01:13:29 ERROR (MainThread) [supervisor.api.ingress] Ingress error: [Errno 104] Connection reset by peer[0m
[31m21-06-15 01:13:31 ERROR (MainThread) [supervisor.api.ingress] Ingress error: [Errno 104] Connection reset by peer[0m
[31m21-06-15 01:13:33 ERROR (MainThread) [supervisor.api.ingress] Ingress error: [Errno 104] Connection reset by peer[0m
[32m21-06-15 01:13:34 INFO (MainThread) [supervisor.api.middleware_security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     color_mode = values["color_mode"]
KeyError: 'color_mode'
[0m
[31m2021-06-14 20:51:54 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /info request[0m
[31m2021-06-14 20:51:54 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /info - [0m
[31m2021-06-14 20:51:54 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /core/info request[0m
[31m2021-06-14 20:51:54 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /core/info - [0m
[31m2021-06-14 20:51:54 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /network/info request[0m
[31m2021-06-14 20:51:54 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /network/info - [0m
[31m2021-06-14 20:51:54 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /resolution/info request[0m
[31m2021-06-14 20:51:54 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /resolution/info - [0m
[31m2021-06-14 20:51:54 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /os/info request[0m
[31m2021-06-14 20:51:54 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /os/info - [0m
[31m2021-06-14 20:51:54 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons request[0m
[31m2021-06-14 20:51:54 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons - [0m
[31m2021-06-14 20:51:54 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /store request[0m
[31m2021-06-14 20:51:54 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /store - [0m
[31m2021-06-14 20:51:54 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /host/info request[0m
[31m2021-06-14 20:51:54 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /host/info - [0m
[31m2021-06-14 20:56:28 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Timeout occurred while connecting to IPP server.[0m
[33m2021-06-14 20:57:16 WARNING (Thread-3) [homeassistant.components.mqtt] Disconnected from MQTT server core-mosquitto:1883 (1)[0m
[31m2021-06-14 20:58:16 ERROR (MainThread) [aiohttp.server] Error handling request[0m
[31m2021-06-14 21:05:28 ERROR (MainThread) [homeassistant.components.zwave_js] Failed to connect: Cannot connect to host a0d7b954-zwavejs2mqtt:3000 ssl:default [Connect call failed ('172.30.33.3', 3000)][0m
[33m2021-06-14 21:05:28 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Z-Wave JS' for zwave_js integration not ready yet: Cannot connect to host a0d7b954-zwavejs2mqtt:3000 ssl:default [Connect call failed ('172.30.33.3', 3000)]; Retrying in background[0m
[31m2021-06-14 21:06:05 ERROR (MainThread) [aiohttp.server] Error handling request[0m
[31m2021-06-14 21:09:56 ERROR (MainThread) [homeassistant.components.recorder] The recorder queue reached the maximum size of 30000; Events are no longer being recorded[0m
[31m2021-06-14 21:10:30 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/cebe7a76_hassio_google_drive_backup/options - not a valid value for dictionary value @ data['options']. Got {'max_snapshots_in_hassio': 4, 'max_snapshots_in_google_drive': 30, 'days_between_snapshots': 1, 'delete_after_upload': True, 'snapshot_time_of_day': '00:00', 'send_error_reports': True, 'generational_days': 1, 'generational_weeks': 1, 'generational_months': 4, 'generational_years': 52, 'alternate_dns_servers': '192.168.1.2', 'background_color': '#000000', 'accent_color': '#02f580', 'use_ssl': False, 'drive_ipv4': '', 'warn_for_low_space': True, 'specify_snapshot_folder': True, 'enable_snapsh...[0m
[31m2021-06-14 21:10:49 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/cebe7a76_hassio_google_drive_backup/options - not a valid value for dictionary value @ data['options']. Got {'max_snapshots_in_hassio': 4, 'max_snapshots_in_google_drive': 30, 'days_between_snapshots': 1, 'delete_after_upload': True, 'snapshot_time_of_day': '00:00', 'send_error_reports': True, 'generational_days': 1, 'generational_weeks': 1, 'generational_months': 4, 'generational_years': 52, 'alternate_dns_servers': '192.168.1.2', 'background_color': '#000000', 'accent_color': '#02f580', 'use_ssl': False, 'drive_ipv4': '', 'warn_for_low_space': True, 'specify_snapshot_folder': True, 'enable_snapsh...[0m
[31m2021-06-14 21:11:11 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/cebe7a76_hassio_google_drive_backup/options - not a valid value for dictionary value @ data['options']. Got {'max_snapshots_in_hassio': 4, 'max_snapshots_in_google_drive': 30, 'days_between_snapshots': 1, 'delete_after_upload': True, 'snapshot_time_of_day': '00:00', 'send_error_reports': False, 'generational_days': 1, 'generational_weeks': 1, 'generational_months': 4, 'generational_years': 52, 'alternate_dns_servers': '192.168.1.2', 'background_color': '#000000', 'accent_color': '#02f580', 'use_ssl': False, 'drive_ipv4': '', 'warn_for_low_space': True}[0m

 ```

**Comment by sabeechen** [comment] 2021-06-16 18:42
I haven't seen this bug come up in a while, in the past I have never been able to figure out why it happens.  The problem is that sometimes, very rarely, Home Assistant just refuses to delete a snapshot and sends the addon back an error.  There are a few different ways you can try to work around this:
- *Delete the snapshot though Home Assistant*: In the Home Assistant Web-UI go to "Supervisor" > "Snapshots" > find the snapshot named "core_2021.5.5" > Click it > open the "..." menu > Choose "DELETE".  Then tell the addon to sync again and see if it still runs into trouble.
- *Delete the snapshot manually*:  If you have some way to get to home Assistant's filesystem (eg the Samba Add, visual Studio Addon, SSH addon, etc)  you can try deleting the snapshot manually.  The problematic one should be the one with the oldest file modified time.  Once you do the addon should try to sync again automatically.

You coudl also try restarting the host machine that runs Home Assistant.  That solves 90% of problems with Home Assistant and the Supervisor.

**Comment by sabeechen** [comment] 2021-09-17 16:08
I'm going to close this for now, but please feel free to reopen it if you think there is something else I can help with.

**Closed by sabeechen** 2021-09-17 16:08 UTC
