### ISSUE TITLE
Google drive backup

### ISSUE THREAD

**Issue by gigideveloper** [sabeechen/hassio-google-drive-backup#514] opened 2021-10-25 21:31 UTC
Hi, I have a problem with this component. Is there anyone that can help me?

Copy the info from the previo
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.105.2`
 Home Assistant Version: `2021.10.6`
 Supervisor Version: `2021.10.0`
 Supervisor Channel: `stable`
 Hassos Version: `6.5`
 Docker Version: `20.10.7`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2021-10-25T21:27:23.799259+00:00`
 Timezone: `Europe/Rome`
 Failure Time: `2021-10-25T21:27:09.749774+00:00`
 Last Good Sync: `2021-10-25T21:27:08.816183+00:00`
 ###### Exception:
 ```
 
  addon/backup/creds/driverequester.py:30 (request)
  addon/backup/tracing_session.py:35 (_request)
  /site-packages/aiohttp/client.py:544 (_request)
  /site-packages/aiohttp/client_reqrep.py:890 (start)
  /site-packages/aiohttp/streams.py:604 (read)
aiohttp.client_exceptions.ClientOSError: [Errno 1] [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2633)
Whose handling caused:
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:204 (sync)
  addon/backup/drive/drivesource.py:179 (save)
  addon/backup/drive/driverequests.py:280 (create)
  addon/backup/drive/driverequests.py:349 (retryRequest)
  addon/backup/creds/driverequester.py:65 (request)
backup.exceptions.exceptions.GoogleUnexpectedError

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 3,
        "retained": 0,
        "deletable": 3,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2021-10-25T01:22:39Z",
        "max": 3,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 8,
        "size": "613.5 MB",
        "ignored_size": "1.4 GB",
        "free_space": "108.6 GB"
    },
    "GoogleDrive": {
        "backups": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 7,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "0.0 B",
        "ignored_size": "0.0 B",
        "free_space": "10.7 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 3,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 7,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0,
    "Setting.IGNORE_OTHER_BACKUPS": true,
    "Setting.BACKUP_TIME_OF_DAY": "03:00"
}
 ```
 ###### Addon Logs:
 ```
 10-25 23:26:53 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/197WlbtsfiHU7VPZKyf8-yok4w6LE1ItI/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
10-25 23:26:54 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
10-25 23:26:54 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%27197WlbtsfiHU7VPZKyf8-yok4w6LE1ItI%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-25 23:26:54 INFO [backup.drive.drivesource] Uploading 'Full Backup 2021-10-25 03:22:37' to Google Drive
10-25 23:26:54 DEBUG [backup.drive.driverequests] Attempting to resume a previously failed upload where we left off
10-25 23:26:54 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdswn4o7cEdr3IVXNXssruVoEI-SDx4yF_TMphNHTP_TIbKF4wlVHyozDiR_I-vWtu6jr53Xy5yh0VExrCVSFyg2rrhtxA
10-25 23:26:54 DEBUG [backup.drive.driverequests] Resuming upload at byte 62914560 of 213729280
10-25 23:26:54 DEBUG [backup.drive.driverequests] Sending 262144 bytes to Google Drive
10-25 23:26:54 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdswn4o7cEdr3IVXNXssruVoEI-SDx4yF_TMphNHTP_TIbKF4wlVHyozDiR_I-vWtu6jr53Xy5yh0VExrCVSFyg2rrhtxA
10-25 23:26:54 DEBUG [backup.drive.drivesource] Uploading Full Backup 2021-10-25 03:22:37 29.56%
10-25 23:26:54 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
10-25 23:26:54 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdswn4o7cEdr3IVXNXssruVoEI-SDx4yF_TMphNHTP_TIbKF4wlVHyozDiR_I-vWtu6jr53Xy5yh0VExrCVSFyg2rrhtxA
10-25 23:26:55 ERROR [backup.model.coordinator] Google gave an unexpected response
10-25 23:26:55 INFO [backup.model.coordinator] I'll try again in an hour
10-25 23:27:08 INFO [backup.model.coordinator] Syncing Backups
10-25 23:27:08 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
10-25 23:27:08 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
10-25 23:27:08 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
10-25 23:27:09 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%27197WlbtsfiHU7VPZKyf8-yok4w6LE1ItI%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-25 23:27:09 INFO [backup.drive.drivesource] Uploading 'Full Backup 2021-10-25 03:22:37' to Google Drive
10-25 23:27:09 DEBUG [backup.drive.driverequests] Attempting to resume a previously failed upload where we left off
10-25 23:27:09 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdswn4o7cEdr3IVXNXssruVoEI-SDx4yF_TMphNHTP_TIbKF4wlVHyozDiR_I-vWtu6jr53Xy5yh0VExrCVSFyg2rrhtxA
10-25 23:27:09 DEBUG [backup.drive.driverequests] Resuming upload at byte 63438848 of 213729280
10-25 23:27:09 DEBUG [backup.drive.driverequests] Sending 262144 bytes to Google Drive
10-25 23:27:09 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdswn4o7cEdr3IVXNXssruVoEI-SDx4yF_TMphNHTP_TIbKF4wlVHyozDiR_I-vWtu6jr53Xy5yh0VExrCVSFyg2rrhtxA
10-25 23:27:09 DEBUG [backup.drive.drivesource] Uploading Full Backup 2021-10-25 03:22:37 29.80%
10-25 23:27:09 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
10-25 23:27:09 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdswn4o7cEdr3IVXNXssruVoEI-SDx4yF_TMphNHTP_TIbKF4wlVHyozDiR_I-vWtu6jr53Xy5yh0VExrCVSFyg2rrhtxA
10-25 23:27:09 ERROR [backup.model.coordinator] Google gave an unexpected response
10-25 23:27:09 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m21-10-25 22:45:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m21-10-25 22:45:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR[0m
[32m21-10-25 22:45:37 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[33m21-10-25 22:45:37 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)[0m
[32m21-10-25 22:45:37 INFO (MainThread) [supervisor.host.manager] Host information reload completed[0m
[32m21-10-25 22:45:38 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE[0m
[32m21-10-25 22:45:38 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m21-10-25 22:45:38 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m21-10-25 22:45:38 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m21-10-25 22:45:38 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m21-10-25 22:45:38 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m21-10-25 22:46:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request initialize[0m
[32m21-10-25 22:46:00 INFO (MainThread) [supervisor.api.proxy] WebSocket access from f4f71350_ewelink_smart_home_slug[0m
[32m21-10-25 22:46:00 INFO (MainThread) [supervisor.api.proxy] Home Assistant WebSocket API request running[0m
[32m21-10-25 23:15:30 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-10-25 23:26:53 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-10-25 23:26:53 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m21-10-25 23:26:54 INFO (MainThread) [supervisor.api.middleware.security] /backups/fe1f53df/download access from cebe7a76_hassio_google_drive_backup[0m
[32m21-10-25 23:26:54 INFO (MainThread) [supervisor.api.backups] Downloading backup fe1f53df[0m
[32m21-10-25 23:26:54 INFO (MainThread) [supervisor.api.middleware.security] /backups/fe1f53df/download access from cebe7a76_hassio_google_drive_backup[0m
[32m21-10-25 23:26:54 INFO (MainThread) [supervisor.api.backups] Downloading backup fe1f53df[0m
[32m21-10-25 23:27:08 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m21-10-25 23:27:08 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m21-10-25 23:27:09 INFO (MainThread) [supervisor.api.middleware.security] /backups/fe1f53df/download access from cebe7a76_hassio_google_drive_backup[0m
[32m21-10-25 23:27:09 INFO (MainThread) [supervisor.api.backups] Downloading backup fe1f53df[0m
[32m21-10-25 23:27:09 INFO (MainThread) [supervisor.api.middleware.security] /backups/fe1f53df/download access from cebe7a76_hassio_google_drive_backup[0m
[32m21-10-25 23:27:09 INFO (MainThread) [supervisor.api.backups] Downloading backup fe1f53df[0m
[32m21-10-25 23:27:23 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m
[32m21-10-25 23:27:24 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
   warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.87'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.87'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.87'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.87'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.87'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.87'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.87'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.87'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.87'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.87'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.87'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.87'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.87'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.1.87'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

 ```
 us page here

**Comment by gigideveloper** [comment] 2021-11-03 22:03
> I had another user run into this problem a little while ago, and I gave some advice [here](https://github.com/sabeechen/hassio-google-drive-backup/issues/503#issuecomment-942633986).  tl;dr is that something is most likely wrong with your computer or the network.  It could be as simple as the clock on your Home Assistant machine being off a few hours, or as severe as malicious software trying to intercept your network traffic with Google.  Its probably the clock.

Hi, I tried all the options you wrote to me, but i haven't solved the problem.
Please, help me because i don't understand what is the cause.

**Comment by sabeechen** [comment] 2021-11-03 22:57
There isn't much else I can do about this.  The logs you posted in your original bug indicate that Home Assistant also seems to be having trouble making SSL connections somewhere.  It looks like this isn't a problem with the addon, its affecting your whole machine.

Usually SSL errors are caused by clock drift.  You can see what time Home Assistant thinks it is by going to "Developer Tools" > "Templates" and using this template:
```
Local time: {{ now() }}
UTC Time: {{ utcnow() }}
```
It should be within a few seconds of the correct time.  Because you're running Home Assistant in a VM, I'd make sure your VM host software is configured to give its client VM's the correct time (depends on the software you're using).  I was able to find [this issue](https://github.com/home-assistant/operating-system/issues/1540) in HA that seems to be related to clock drift, but I can't be confident the fix they recommend is a good idea as I'm unfamiliar with the software.

If you're certain time isn't the problem, then something somewhere between your computer and the internet is interfering with the traffic your home Assistant machine is sending out.  That could be because your computer, router, or ISP has something misconfigured.  It could even be because your machine has malware.  I found [this website](https://techinfluence.net/err_ssl_bad_record_mac_alert-error/) which has some suggestions but honestly, they all kind of seem like a stretch.

**Comment by sabeechen** [comment] 2022-03-22 16:49
I'm closing this issue for now, but please feel free to re-open it if you think there is more I can help with.

**Closed as completed by sabeechen** 2022-03-22 16:49 UTC
