### ISSUE TITLE
Problems logging

### ISSUE THREAD

**Issue by Ender3Pro** [sabeechen/hassio-google-drive-backup#376] opened 2021-04-04 08:25 UTC
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.103.1`
 Home Assistant Version: `Uninitialized`
 Supervisor Version: `Uninitialized`
 Supervisor Channel: `{supervisor_channel}`
 Hassos Version: `{hassos_version}`
 Docker Version: `{docker_version}`
 Architecture: `Uninitialized`
 Machine: `{machine}`
 Date: `2021-04-04T08:24:48.381507+00:00`
 Timezone: `Uninitialized`
 Failure Time: `2021-04-04T08:24:43.063392+00:00`
 Last Good Sync: `2021-04-04T08:24:43.022811+00:00`
 ###### Exception:
 ```
 
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/tracing_session.py:20 (_request)
  /site-packages/aiohttp/client.py:520 (_request)
  [2 hidden frames]
  /site-packages/aiohttp/connector.py:1011 (_create_direct_connection)
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio:80 ssl:default [None]
Whose handling caused:
  addon/backup/model/coordinator.py:156 (_sync)
  addon/backup/model/model.py:149 (sync)
  addon/backup/model/model.py:236 (_syncSnapshots)
  addon/backup/ha/hasource.py:220 (get)
  addon/backup/ha/hasource.py:292 (init)
  addon/backup/ha/hasource.py:324 (_refreshInfo)
  addon/backup/ha/hasource.py:300 (_refreshInfo)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:112 (selfInfo)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:116 (getAddonInfo)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
backup.exceptions.exceptions.SupervisorConnectionError

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": null,
        "max": 4,
        "enabled": true,
        "size": "0.0 B",
        "free_space": "10.1 TB"
    },
    "GoogleDrive": {
        "snapshots": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 4,
        "enabled": true,
        "size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {}
 ```
 ###### Addon Logs:
 ```
 04-04 09:05:12 ERROR [backup.ha.haupdater] 
  addon/backup/ha/haupdater.py:53 (update)
  addon/backup/ha/harequests.py:256 (updateSnapshotStaleSensor)
  addon/backup/ha/harequests.py:215 (_postHaData)
  /site-packages/aiohttp/client.py:1117 (__aenter__)
  addon/backup/tracing_session.py:20 (_request)
  /site-packages/aiohttp/client.py:520 (_request)
  [2 hidden frames]
  /site-packages/aiohttp/connector.py:1011 (_create_direct_connection)
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio:80 ssl:default [None]

04-04 09:10:22 ERROR [backup.ha.haupdater] Trouble updating Home Assistant sensors.
04-04 09:10:22 ERROR [backup.ha.haupdater] 
  addon/backup/ha/haupdater.py:53 (update)
  addon/backup/ha/harequests.py:256 (updateSnapshotStaleSensor)
  addon/backup/ha/harequests.py:215 (_postHaData)
  /site-packages/aiohttp/client.py:1117 (__aenter__)
  addon/backup/tracing_session.py:20 (_request)
  /site-packages/aiohttp/client.py:520 (_request)
  [2 hidden frames]
  /site-packages/aiohttp/connector.py:1011 (_create_direct_connection)
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio:80 ssl:default [None]

04-04 09:15:33 ERROR [backup.ha.haupdater] Trouble updating Home Assistant sensors.
04-04 09:15:33 ERROR [backup.ha.haupdater] 
  addon/backup/ha/haupdater.py:53 (update)
  addon/backup/ha/harequests.py:256 (updateSnapshotStaleSensor)
  addon/backup/ha/harequests.py:215 (_postHaData)
  /site-packages/aiohttp/client.py:1117 (__aenter__)
  addon/backup/tracing_session.py:20 (_request)
  /site-packages/aiohttp/client.py:520 (_request)
  [2 hidden frames]
  /site-packages/aiohttp/connector.py:1011 (_create_direct_connection)
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio:80 ssl:default [None]

04-04 09:20:43 ERROR [backup.ha.haupdater] Trouble updating Home Assistant sensors.
04-04 09:20:43 ERROR [backup.ha.haupdater] 
  addon/backup/ha/haupdater.py:53 (update)
  addon/backup/ha/harequests.py:256 (updateSnapshotStaleSensor)
  addon/backup/ha/harequests.py:215 (_postHaData)
  /site-packages/aiohttp/client.py:1117 (__aenter__)
  addon/backup/tracing_session.py:20 (_request)
  /site-packages/aiohttp/client.py:520 (_request)
  [2 hidden frames]
  /site-packages/aiohttp/connector.py:1011 (_create_direct_connection)
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio:80 ssl:default [None]

04-04 09:21:50 DEBUG [backup.model.syncer] Sync requested by Coordinator
04-04 09:21:50 INFO [backup.model.coordinator] Syncing Snapshots
04-04 09:21:50 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
04-04 09:21:50 DEBUG [backup.ha.hasource] Failed to connect to supervisor
04-04 09:21:50 DEBUG [backup.ha.hasource] 
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/tracing_session.py:20 (_request)
  /site-packages/aiohttp/client.py:520 (_request)
  [2 hidden frames]
  /site-packages/aiohttp/connector.py:1011 (_create_direct_connection)
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio:80 ssl:default [None]
Whose handling caused:
  addon/backup/ha/hasource.py:300 (_refreshInfo)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:112 (selfInfo)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:116 (getAddonInfo)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
backup.exceptions.exceptions.SupervisorConnectionError

04-04 09:21:50 ERROR [backup.model.coordinator] The addon couldn't connect to the supervisor.  Backups can't continue until the supervisor is responding.
04-04 09:21:50 INFO [backup.model.coordinator] I'll try again in 42(ish) minutes
04-04 09:24:36 INFO [backup.drive.drivesource] Saving new Google Drive credentials
04-04 09:24:36 DEBUG [backup.model.syncer] Sync requested by GoogleDrive
04-04 09:24:36 INFO [backup.model.coordinator] Syncing Snapshots
04-04 09:24:36 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
04-04 09:24:36 DEBUG [backup.ha.hasource] Failed to connect to supervisor
04-04 09:24:36 DEBUG [backup.ha.hasource] 
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/tracing_session.py:20 (_request)
  /site-packages/aiohttp/client.py:520 (_request)
  [2 hidden frames]
  /site-packages/aiohttp/connector.py:1011 (_create_direct_connection)
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio:80 ssl:default [None]
Whose handling caused:
  addon/backup/ha/hasource.py:300 (_refreshInfo)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:112 (selfInfo)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:116 (getAddonInfo)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
backup.exceptions.exceptions.SupervisorConnectionError

04-04 09:24:36 ERROR [backup.model.coordinator] The addon couldn't connect to the supervisor.  Backups can't continue until the supervisor is responding.
04-04 09:24:36 INFO [backup.model.coordinator] I'll try again in an hour
04-04 09:24:41 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/options
04-04 09:24:43 INFO [backup.model.coordinator] Syncing Snapshots
04-04 09:24:43 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/info
04-04 09:24:43 DEBUG [backup.ha.hasource] Failed to connect to supervisor
04-04 09:24:43 DEBUG [backup.ha.hasource] 
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:207 (_getHassioData)
  addon/backup/tracing_session.py:20 (_request)
  /site-packages/aiohttp/client.py:520 (_request)
  [2 hidden frames]
  /site-packages/aiohttp/connector.py:1011 (_create_direct_connection)
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio:80 ssl:default [None]
Whose handling caused:
  addon/backup/ha/hasource.py:300 (_refreshInfo)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:112 (selfInfo)
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:116 (getAddonInfo)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
backup.exceptions.exceptions.SupervisorConnectionError

04-04 09:24:43 ERROR [backup.model.coordinator] The addon couldn't connect to the supervisor.  Backups can't continue until the supervisor is responding.
04-04 09:24:43 INFO [backup.model.coordinator] I'll try again in an hour
04-04 09:24:44 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/options
 ```
 ###### Supervisor Logs:
 ```
 
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:161 (getSuperLogs)
  /site-packages/aiohttp/client.py:1117 (__aenter__)
  addon/backup/tracing_session.py:20 (_request)
  /site-packages/aiohttp/client.py:520 (_request)
  [2 hidden frames]
  /site-packages/aiohttp/connector.py:1011 (_create_direct_connection)
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio:80 ssl:default [None]
Whose handling caused:
  addon/backup/debugworker.py:133 (buildBugReportData)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
backup.exceptions.exceptions.SupervisorConnectionError

 ```
 ###### Home Assistant Core Logs:
 ```
 
  addon/backup/ha/harequests.py:26 (wrap_and_call)
  addon/backup/ha/harequests.py:168 (getCoreLogs)
  /site-packages/aiohttp/client.py:1117 (__aenter__)
  addon/backup/tracing_session.py:20 (_request)
  /site-packages/aiohttp/client.py:520 (_request)
  [2 hidden frames]
  /site-packages/aiohttp/connector.py:1011 (_create_direct_connection)
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host hassio:80 ssl:default [None]
Whose handling caused:
  addon/backup/debugworker.py:137 (buildBugReportData)
  addon/backup/ha/harequests.py:28 (wrap_and_call)
backup.exceptions.exceptions.SupervisorConnectionError

 ```

**Comment by sabeechen** [comment] 2021-04-22 01:51
Sorry it took so long for me to get back to you, I've been overloaded making a new release.

This error is very strange, because the supervisor should always be available.  It creates the environment the addon runs in.  I see a lot errors similar to this come up from users when the supervisor gets into some kind of bad state but I rarely hear back about what caused it.  I've seen the following be the cause:
- A transient bug that went away after restarting the host machine.
- The system was out of disk space
- The supervisor lost permission to run on the host machine (the user was managing their own docker environment)
- Disk corruption (bad SD card).

Does this error persist after restarting the host machine?

**Comment by sabeechen** [comment] 2021-05-08 18:31
I'm going to close this for now, but please feel free to reopen it if you think there is something else I can help with.

**Closed by sabeechen** 2021-05-08 18:31 UTC
