### ISSUE TITLE
High swap usage when running add on in Home assistant?

### ISSUE THREAD

**Issue by fjplarsson** [sabeechen/hassio-google-drive-backup#306] opened 2020-11-12 08:22 UTC
When running HassOS 4.15 swap memory usage increase rather quick when running the addon. Within an hour it is above 90%. 
If addon is stopped it is down and stable around 40%. If host is restarted the stable condition is below 20% over days until addon is started again. Swap usage is measured by Glance addon 0.9.1

**Comment by sabeechen** [comment] 2020-11-13 18:05
The addon itself is usually pretty lightweight and there are a lot of things, some of them normal, than could cause high swap usage.  The addon doesn't do anything in particular that should make heavy use of the swap.  What I mean to say is that this may be your system working normally, but here are a few things you can check to see why you might be eating more into your swap.
- 90% swap usage suggests that your system has run out of RAM and is writing to disk to free up space to let things run, but again it could also just be things working normally.  I'd tell you to use Galnces to to look at this, but having just installed it on my machine the system RAM usage numbers its reporting to me seem to be inaccurate.   Not sure if this is the case for the swap too.
-  The addon should usually use about ~50M RAM and <2% CPU.  You should be able to see the addon's performance stats in Glances under "Containers" > "addon_cebe7a76_hassio_google_drive_backup"
- When the addon is uploading a snapshot to Google Drive CPU usage will spike up, higher if your internet is faster.
- When the addon asks the supervisor to create a snapshot you should see CPU and RAM usage in the supervisor spike up while its being created.  How much depends on what you have configured in Home Assistant.  On my system its typical for for the supervisor to use ~100% of a core and a whopping 3G of RAM while the snapshot is being made.

Take the RAM usage numbers with a grain of salt, since you can never know how much is actually being used and how much python is just holding on until it needs to be freed up for someone else since my machine has a lot of extra RAM.

**Comment by fjplarsson** [comment] 2020-11-15 10:35
Hi
The problem is not amount of RAM, it is that the RAM usage change,
increasing from a steady state level when addon is started.  Level is
corresponding to number of active add-ons but when having backup addon
running it increase. A couple of tests shows about 1% per minute and when
reaching 100% the raspberry stalls and get unreachable. Only way is a power
reset.  But without the addon running i can run för weeks with same level
of swap used. Should be zero according to me because the RAM is less than
50% used. I am a newbie on this so maybe something i have missed but the
easy way out is to start the addon run the backup and then stop the service
after finished. Then is swap slowly coming back down again.
Best regards
Fredrik

Den fre 13 nov. 2020 19:05Stephen Beechen <notifications@github.com> skrev:

**Comment by sabeechen** [comment] 2020-11-17 20:07
I'm having trouble understanding the symptoms of the problem you describe.  High swap usage _can_ be a problem but can be caused by a lot of things (many of which aren't a problem) and high RAM usage is almost always a problem.  Are you seeing both?

- Can you verify that the addon is actually using a lot of RAM, and if so how much RAM is it using?    You should be able to see its RAM usage in Glances under "Containers" > "addon_cebe7a76_hassio_google_drive_backup".
- I suspect whats actually happening is your system is struggling to create a snapshot, which could be because of not enough RAM, disk space, etc.  You should be able to see in Glances which process is using a lot of RAM if thats the problem.
- You should see if the logs say anything useful when your system runs into problems.  You can go to "Actions" > "Make a Bug Report" in the addon's web-ui to have the logs formatted in a way you can paste here.  Alternatively you can check the addon's "Logs" page within Home assistant and the supervisor's logs at "Supervisor" > "system" > "Logs".

**Comment by sabeechen** [comment] 2021-02-21 16:50
I'm closing this issue for now, but feel free to reopen it or ping me if you there there is anything else I can do to help.

**Closed by sabeechen** 2021-02-21 16:50 UTC
