### ISSUE TITLE
Failed to start Addon - 500 Server Error

### ISSUE THREAD

**Issue by vk2him** [sabeechen/hassio-google-drive-backup#339] opened 2021-02-03 03:11 UTC
I get this error when trying to start. Was working for a long time without issue but now fails. I tried removing/reinstalling but same each time.

500 Server Error for http+docker://localhost/v1.39/containers/a1c6a28bbc24a38e07b30ec6831d42dc7894bc986d2d6f0bc1b01e850cf50df1/start: Internal Server Error ("OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/dev/init\": stat /dev/init: no such file or directory": unknown")

**Comment by sabeechen** [comment] 2021-02-04 18:15
This is a tricky issue for me to solve, as I don't oversee anything in the supervisor's environment that starts the container where this error is happening.  Where I'd start is that if you manage your own docker environment, make sure it is up to date and you satisfy the requirements[ described here](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) on the host system.  While you're at it it make sure you don't have any pending Supervisor/Home Asisstant/Addon updates pending.

If not, check the supervisor's logs when starting the addon to see if it prints out any error messages that might be useful for debugging.  I'd bet something helpful is printed there.

**Comment by DivanX10** [comment] 2021-02-10 13:45
I have a similar problem. Hassio is installed in docker on Synology
![hassio backup](https://user-images.githubusercontent.com/64090632/107515232-cc905700-6bbb-11eb-9d70-43e9c8170d59.JPG)
500 Server Error for http+docker://localhost/v1.39/containers/95ea3ac5157b5d777f5d2b75875b61cef6876c86d39e0af8bdad391106543b89/start: Internal Server Error ("OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/dev/init\": stat /dev/init: no such file or directory": unknown")

I checked on Hassio OS, there are no problems, Home Assistant Google Drive Backup was installed and started successfully.

I assume that the problem is related to the fact that Home Assistant Google Drive Backup creates a config folder with read permissions. This folder is visible through the network folder. The folder can't be opened in Windows, it can't be seen in Synology, but I can open it via Midnight Commander. I deleted the folder and created it myself, rebooted docker, but the problem was not solved.
![config](https://user-images.githubusercontent.com/64090632/107515342-f0ec3380-6bbb-11eb-9bf7-a6b9d3860eee.jpg)

There is no config folder in the Synology file manager
![no config folder](https://user-images.githubusercontent.com/64090632/107515430-09f4e480-6bbc-11eb-8bb3-0c8253e17026.jpg)

These parameters are specified in the docker by default
![container_buckup](https://user-images.githubusercontent.com/64090632/107515437-0e210200-6bbc-11eb-9af3-0ae1fdd95577.jpg)

I looked as specified in other containers, then I saw the record parameter
![container_buckup_02](https://user-images.githubusercontent.com/64090632/107516761-ecc11580-6bbd-11eb-8d14-222ee9e87ffb.JPG)

In the docker logs, there is a message that there is no such config folder
Start container addon_cebe7a76_hassio_google_drive_backup failed: {"message":"OCI runtime create failed: container_linux.go:345: starting container process caused \"exec: \\\"/dev/init\\\": stat /dev/init: no such file or directory\": unknown"} 

I went through the console and launched Midnight Commander
![mc](https://user-images.githubusercontent.com/64090632/107517281-9e604680-6bbe-11eb-9cad-6aa28c5abfaf.JPG)


_______
У меня аналогичная проблема. Hassio установлен в docker на Synology
![hassio backup](https://user-images.githubusercontent.com/64090632/107515232-cc905700-6bbb-11eb-9d70-43e9c8170d59.JPG)
500 Server Error for http+docker://localhost/v1.39/containers/95ea3ac5157b5d777f5d2b75875b61cef6876c86d39e0af8bdad391106543b89/start: Internal Server Error ("OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/dev/init\": stat /dev/init: no such file or directory": unknown")

Проверил на ОС Hassio OS, там проблем нет, Home Assistant Google Drive Backup установился и запустился успешно.

Я предполагаю, что проблема связана с тем, что Home Assistant Google Drive Backup создает папку config с правами чтение. Эту папку видно через сетевую папку. Папку не открыть в Windows, в Synology ее не видно, но могу открыть через Midnight Commander. Папку удалил и создал сам, перезагрузил docker, но проблема не решилась.
![config](https://user-images.githubusercontent.com/64090632/107515342-f0ec3380-6bbb-11eb-9bf7-a6b9d3860eee.jpg)

В файловом менеджере Synology папки config нет
![no config folder](https://user-images.githubusercontent.com/64090632/107515430-09f4e480-6bbc-11eb-8bb3-0c8253e17026.jpg)

Такие параметры указаны в докере по умолчанию
![container_buckup](https://user-images.githubusercontent.com/64090632/107515437-0e210200-6bbc-11eb-9af3-0ae1fdd95577.jpg)

Посмотрел как указано в других контейнерах, то увидел параметр запись
![container_buckup_02](https://user-images.githubusercontent.com/64090632/107516761-ecc11580-6bbd-11eb-8d14-222ee9e87ffb.JPG)

В логах докера такое сообщение, что нет такой папки config
Start container addon_cebe7a76_hassio_google_drive_backup failed: {"message":"OCI runtime create failed: container_linux.go:345: starting container process caused \"exec: \\\"/dev/init\\\": stat /dev/init: no such file or directory\": unknown"} 

Зашел через консоль и запустил Midnight Commander
![mc](https://user-images.githubusercontent.com/64090632/107517281-9e604680-6bbe-11eb-9cad-6aa28c5abfaf.JPG)

**Comment by vk2him** [comment] 2021-02-10 18:29
I can confirm my issue is identical, I am also running a Synology NAS.

**Comment by sherkan-666** [comment] 2021-02-11 13:52
Same here, I am also running a Synology NAS.
Version supervisor-2021.02.6

**Comment by sabeechen** [comment] 2021-02-20 17:53
I have trouble diagnosing this, because I don't have any Synology hardware to test this on and I'm not really sure how the environment is set up.  Here is what I know:

- The supervisor/HA is officially not supported on Synology, which may be the root of the problem.  That being said I've heard from some that they've been able to migrate to a VM running HA on Synology and get things working.  I'm not sure what that actually means.
- The supervisor requires an up-to-date docker.  On my machines I can say that docker version 20.10.1 works, but anything before 19.x gives me problems.  Can you update docker on Synology?

**Comment by DivanX10** [comment] 2021-02-20 19:24
Да, к сожалению эта проблема коснулась только HA в Docker на Synology. Официально в Synology установлен Docker версии 18.09. Можно обновиться до версии 20.10, но это не официальное обновление и после обновления есть проблемы с запуском HA и не только проблемы с HA, но и с другими контейнерами. Многие уже пострадали после обновления docker до версии 20. Единственное решение проблемы, это установить Hass OS на virtual machine manager Synology.

Yes, unfortunately, this problem only affected the Russian Federation in Docker on Synology. Officially, Synology has Docker version 18.09 installed. You can upgrade to version 20.10, but this is not an official update and after the update there are problems with running HA and not only problems with HA, but also with other containers. Many have already been affected after upgrading docker to version 20. The only solution to the problem is to install Mac OS on the Synology virtual machine manager.

**Comment by sabeechen** [comment] 2021-02-21 16:04
I suspect there isn't anything I can do about this.  The error you guys are seeing is one from docker, its running into some problem starting the container environment.  I've seen this before when using a "supervised" install (eg managing my own docker environment on Debian) and it was resolved by updating docker.  It seems this is very likely because the HA supervisor [requires docker v19.03 or higher](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md#supported-operating-system-system-dependencies-and-versions).

If there is anything else you think I can do to help with this, please reopen this bug and let me know.  I'm going to close this issue for now.

**Closed by sabeechen** 2021-02-21 16:04 UTC
