### ISSUE TITLE
An unexpected error occurred: ('Connection aborted.', timeout('The write operation timed out',))

### ISSUE THREAD

**Issue by PrathikGopal** [sabeechen/hassio-google-drive-backup#74] opened 2019-07-05 06:38 UTC
Hi Sabeechen, 

Thank you for creating this addon, its the most important addon for me, recently I found the uploads were failing, when i opened the UI i saw the timeout errors, i do run pi-hole so i disabled it to check even turned it off but still the upload fails , the error just wont go away.
I have decent speeds in uploads above 9.XX mbps. It would take around 3 minutes 53 seconds to transfer 250 Megabytes(size of backup) at 1.07 MB/sec.

**Tried the below**
1. Tried increasing timeout to above 320secs, since error logs pointed to the same.
2. disabled pi-hole, even turned it off and routed to google dns
3. Upload speed checked at 9.xx mbps
4. Tried entered different drive ip in settings.
5. Reinstalled Addon.
6. Found googleapis is reachable from my network and so is the drive IP's

Uploads stop at different percentages, sometimes 4%, 21%, 50%. Something else which i don't understand is going on, i would request your help to solve this.
 
**Configuration used:**
{
  "max_snapshots_in_hassio": 2,
  "max_snapshots_in_google_drive": 2,
  "days_between_snapshots": 2,
  "use_ssl": false,
  "snapshot_time_of_day": "04:00",
  "snapshot_password": "!secret gdrive_archive_pass",
  "send_error_reports": false,
  "require_login": true,
  "google_drive_timeout_seconds": 320,
  "alternate_dns_servers": "8.8.8.8,1.1.1.1",
  "drive_ipv4": "216.58.192.170"
}

**Error screenshot**
![image](https://user-images.githubusercontent.com/38837781/60701625-ff6f6500-9f19-11e9-8c73-c67487af2559.png)

**Errors Captured**
Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 102, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 142, in sync
    upload.addSource(self.dest.save(upload, self.source.read(upload)))
  File "/app/backup/drivesource.py", line 114, in save
    for progress in self.drivebackend.create(bytes, file_metadata, MIME_TYPE):
  File "/app/backup/driverequests.py", line 188, in create
    partial = self.retryRequest("PUT", location, headers=headers, data=data, patch_url=False)
  File "/app/backup/driverequests.py", line 241, in retryRequest
    raise e
  File "/app/backup/driverequests.py", line 230, in retryRequest
    response = self._request_client.request(method, url, headers=send_headers, json=json, timeout=self.config.get(Setting.GOOGLE_DRIVE_TIMEOUT_SECONDS), data=data, stream=stream)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out',))

An unexpected error occurred: ('Connection aborted.', timeout('The write operation timed out',))

No problematic logs from the Hassio supervisor just auth logs seen, Would be happy to share any more logs or tests further.

**Comment by sabeechen** [comment] 2019-07-06 19:32
You've tried all the things I would ask for you to try from a networking perspective (increase the timeout, rejigger DNS settings, reinstall, etc), thank you for the due diligence.  Because you're able to upload some part of the snapshot I doubt the problem is related to DNS/pi-hole.  I can only think of a few other possible causes:

1. Your internet connection could just be spotty.  Intermittent drop-outs would show up with this type of error.  Hopefully this isn't the case because I can't really do anything about it and it would I'm not sure how we'd verify its the cause problem.  I could add more options to let you configure the number of retries, etc but we'd really just be shooting in the dark and you'd have to wait for a new release. 
2.  Something is wrong with your Google Drive account.  An individual account with Google can become overloaded if you have a lot of other things writing to it at the same time (or a bunch of less common scenarios).  You could determine if this is the problem by authenticating the add-on with a different account (eg create a new Google Drive account just to test this and then select "ACTIONS > "Reauthenticate with Google Drive" selecting the new account).

How big are your snapshots?  I've suspected this kind of thing could happen for massive snapshots (eg 10's of GB) but I've never had anyone reported.  This is the first time someone has reported connectivity problems with Google Drive for a while.

**Comment by sabeechen** [comment] 2019-07-06 19:44
Marking this a bug for lack of a better explanation.

**Comment by sabeechen** [comment] 2019-07-23 15:54
Closing this to clean it up, but feel free to open it back up if you think I could help more.

**Closed by sabeechen** 2019-07-23 15:54 UTC
Labels: bug
