### ISSUE TITLE
Restoring Hassio from a previous upload fails

### ISSUE THREAD

**Issue by danielsjf** [sabeechen/hassio-google-drive-backup#98] opened 2019-09-03 20:51 UTC
I've recently reinstalled Hassio and now I'm trying to restore one of my old uploads. It gets to 98% every time and then returns the following error.

```
Traceback (most recent call last):
  File "/app/backup/uiserver.py", line 511, in handleError
    return call()
  File "/app/backup/uiserver.py", line 427, in <lambda>
    return self.handleError(lambda: self._upload(slug))
  File "/app/backup/uiserver.py", line 430, in _upload
    self._coord.uploadSnapshot(slug)
  File "/app/backup/coordinator.py", line 122, in uploadSnapshot
    self._withSoftLock(lambda: self._uploadSnapshot(slug))
  File "/app/backup/coordinator.py", line 210, in _withSoftLock
    return callable()
  File "/app/backup/coordinator.py", line 122, in <lambda>
    self._withSoftLock(lambda: self._uploadSnapshot(slug))
  File "/app/backup/coordinator.py", line 134, in _uploadSnapshot
    created = self._model.source.save(snapshot, self._model.dest.read(snapshot))
  File "/app/backup/hasource.py", line 215, in save
    raise UploadFailed()
backup.exceptions.UploadFailed
```

**Comment by sabeechen** [comment] 2019-09-10 19:22
Sorry it took so long to get back, I had to step away from maintaining this for a bit.  Hassio does all the heavy lifting when restoring an addon, so the problem is almost certainly happening there.  Can you check the supervisor logs (Hassio > System > System Logs) to see if they show any more specific errors when a snapshot fails?

  If you're still having trouble restoring, you could bypass the addon by copying the snapshot directly from Google Drive into the /backup folder of the Home Assistant machine.  You should then be able to go to Hassio > Snapshots, click the refresh icon in the upper right and see the snapshot available for restore.  Again check the supervisor logs if things fail.

If all else fails, you could open up the snapshot archive on your computer and inspect the contents.  This won't help you restore add-on configuration, but you should be able to find the contents of your /config directory at the very least.

**Comment by sabeechen** [comment] 2019-10-02 20:14
Closing this out due to age, but feel free to reopen this if there is still some way I can help.

**Closed by sabeechen** 2019-10-02 20:14 UTC
