### ISSUE TITLE
Problem syncing -  The Supervisor Returned an Unexpected Response

### ISSUE THREAD

**Issue by mpieru** [sabeechen/hassio-google-drive-backup#265] opened 2020-09-20 08:38 UTC
I currently get this error: " The Supervisor Returned an Unexpected Response"
I tried to do a resync, tried to stop/restart the module and the whole HA/Raspberry, I did a new authentication on Google Account (really I don't know if it's matter :-) )
anyway the last thing remained is to uninstall and reinstall (not done yet).

EDIT: I notice a strange error on the row:
av.error.ValueError: [Errno 22] Invalid argument: 'rtsp://xxxx:yyyy@192.168.8.90:554/live/ch1'; last error log: [tcp] Port missing in uri
(I changed the xxxx:yyyy obviously)

Description:
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
Addon version: 0.101.3 Home Assistant Version: 0.114.4 Supervisor Version: 245 Supervisor Channel: stable Hassos Version: 4.12 Docker Version: 19.03.11 Architecture: armv7 Machine: raspberrypi4 Date: 2020-09-20T08:25:19.285610+00:00 Timezone: Europe/Rome Failure Time: 2020-09-20T08:08:09.634887+00:00 Last Good Sync: 2020-09-20T08:08:08.297687+00:00

Exception:

 addon/backup/util/asynchttpgetter.py:133 (read)
 /site-packages/aiohttp/streams.py:416 (readexactly)
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
Whose handling caused:
 addon/backup/model/coordinator.py:148 (_sync)
 addon/backup/model/model.py:162 (sync)
 addon/backup/drive/drivesource.py:150 (save)
 addon/backup/drive/driverequests.py:252 (create)
 addon/backup/util/asynchttpgetter.py:140 (read)
backup.exceptions.exceptions.SupervisorUnexpectedError

Snapshots:

{
   "HomeAssistant": {
       "snapshots": 4,
       "retained": 0,
       "deletable": 4,
       "name": "HomeAssistant",
       "latest": "2020-09-18T14:53:30Z",
       "size": "10.3 GB"
   },
   "GoogleDrive": {
       "snapshots": 2,
       "retained": 0,
       "deletable": 2,
       "name": "GoogleDrive",
       "latest": "2020-09-12T13:45:21Z",
       "size": "3.8 GB"
   }
}
Config:
{
   "Setting.MAX_SNAPSHOTS_IN_HASSIO": 5,
   "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 2,
   "Setting.SPECIFY_SNAPSHOT_FOLDER": true,
   "Setting.SEND_ERROR_REPORTS": true
}
Addon Logs:
09-20 08:08:06 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2020-09-18 16:53:29' to Google Drive
09-20 08:08:06 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
09-20 08:08:06 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-UyZqxGfrVywdmx_Q0s9bhgJcfz2l4yWTjte2Y1xRvkH-wMC32Vb_-hsYx0maaCgzUbV8OsZLLAiY42jcDNvNIa7pX5mnw
09-20 08:08:06 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 3472046080
09-20 08:08:06 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
09-20 08:08:06 INFO [backup.model.coordinator] I'll try again in an hour
09-20 09:08:06 DEBUG [backup.model.syncer] Sync requested by Coordinator
09-20 09:08:06 INFO [backup.model.coordinator] Syncing Snapshots
09-20 09:08:06 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
09-20 09:08:06 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
09-20 09:08:07 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/16ygNvI2LIx3m5SDQPNJCMp9ulA30kZfH/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
09-20 09:08:07 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%2716ygNvI2LIx3m5SDQPNJCMp9ulA30kZfH%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
09-20 09:08:08 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2020-09-18 16:53:29' to Google Drive
09-20 09:08:08 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
09-20 09:08:08 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-UyZqxGfrVywdmx_Q0s9bhgJcfz2l4yWTjte2Y1xRvkH-wMC32Vb_-hsYx0maaCgzUbV8OsZLLAiY42jcDNvNIa7pX5mnw
09-20 09:08:08 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 3472046080
09-20 09:08:08 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
09-20 09:08:08 INFO [backup.model.coordinator] I'll try again in an hour
09-20 10:08:08 DEBUG [backup.model.syncer] Sync requested by Coordinator
09-20 10:08:08 INFO [backup.model.coordinator] Syncing Snapshots
09-20 10:08:08 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
09-20 10:08:08 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
09-20 10:08:08 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/16ygNvI2LIx3m5SDQPNJCMp9ulA30kZfH/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
09-20 10:08:09 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%2716ygNvI2LIx3m5SDQPNJCMp9ulA30kZfH%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
09-20 10:08:09 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2020-09-18 16:53:29' to Google Drive
09-20 10:08:09 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
09-20 10:08:09 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-UyZqxGfrVywdmx_Q0s9bhgJcfz2l4yWTjte2Y1xRvkH-wMC32Vb_-hsYx0maaCgzUbV8OsZLLAiY42jcDNvNIa7pX5mnw
09-20 10:08:09 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 3472046080
09-20 10:08:09 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
09-20 10:08:09 INFO [backup.model.coordinator] I'll try again in an hour
Supervisor Logs:
[32m20-09-20 05:08:03 INFO (MainThread) [supervisor.api.security] /snapshots access from f0e7e328_hassio_google_drive_backup[0m
[32m20-09-20 05:08:04 INFO (MainThread) [supervisor.api.security] /snapshots/f4f3bbd2/download access from f0e7e328_hassio_google_drive_backup[0m
[32m20-09-20 05:08:04 INFO (MainThread) [supervisor.api.snapshots] Download snapshot f4f3bbd2[0m
[32m20-09-20 05:25:37 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-09-20 05:54:05 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json[0m
[32m20-09-20 05:55:42 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-09-20 06:08:05 INFO (MainThread) [supervisor.api.security] /snapshots access from f0e7e328_hassio_google_drive_backup[0m
[32m20-09-20 06:08:06 INFO (MainThread) [supervisor.api.security] /snapshots/f4f3bbd2/download access from f0e7e328_hassio_google_drive_backup[0m
[32m20-09-20 06:08:06 INFO (MainThread) [supervisor.api.snapshots] Download snapshot f4f3bbd2[0m
[32m20-09-20 06:25:48 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-09-20 06:27:32 INFO (MainThread) [supervisor.host.info] Update local host information[0m
[32m20-09-20 06:27:33 INFO (MainThread) [supervisor.host.services] Update service information[0m
[32m20-09-20 06:27:33 INFO (MainThread) [supervisor.host.network] Update local network information[0m
[32m20-09-20 06:27:34 INFO (MainThread) [supervisor.host.sound] Update PulseAudio information[0m
[32m20-09-20 06:55:53 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-09-20 07:08:06 INFO (MainThread) [supervisor.api.security] /snapshots access from f0e7e328_hassio_google_drive_backup[0m
[32m20-09-20 07:08:08 INFO (MainThread) [supervisor.api.security] /snapshots/f4f3bbd2/download access from f0e7e328_hassio_google_drive_backup[0m
[32m20-09-20 07:08:08 INFO (MainThread) [supervisor.api.snapshots] Download snapshot f4f3bbd2[0m
[32m20-09-20 07:25:58 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-09-20 07:54:05 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json[0m
[32m20-09-20 07:54:09 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository[0m
[32m20-09-20 07:54:09 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup.git repository[0m
[32m20-09-20 07:54:09 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository[0m
[32m20-09-20 07:54:11 INFO (MainThread) [supervisor.store] Load add-ons from store: 67 all - 0 new - 0 remove[0m
[32m20-09-20 07:56:03 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-09-20 08:08:08 INFO (MainThread) [supervisor.api.security] /snapshots access from f0e7e328_hassio_google_drive_backup[0m
[32m20-09-20 08:08:09 INFO (MainThread) [supervisor.api.security] /snapshots/f4f3bbd2/download access from f0e7e328_hassio_google_drive_backup[0m
[32m20-09-20 08:08:09 INFO (MainThread) [supervisor.api.snapshots] Download snapshot f4f3bbd2[0m
[32m20-09-20 08:25:19 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from f0e7e328_hassio_google_drive_backup[0m

Home Assistant Core Logs:
2020-09-20 10:22:10 WARNING (MainThread) [homeassistant.components.sensor] Updating mitemp_bt sensor took longer than the scheduled update interval 0:00:30
2020-09-20 10:22:29 ERROR (updater) [telegram.ext.updater] Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2020-09-20 10:22:40 WARNING (MainThread) [homeassistant.components.sensor] Updating mitemp_bt sensor took longer than the scheduled update interval 0:00:30
2020-09-20 10:22:48 WARNING (SyncWorker_47) [homeassistant.components.mitemp_bt.sensor] Polling error 
2020-09-20 10:23:01 ERROR (updater) [telegram.ext.updater] Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2020-09-20 10:23:20 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.casa_tdl_camera_temperature is taking over 10 seconds
2020-09-20 10:23:38 ERROR (updater) [telegram.ext.updater] Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2020-09-20 10:23:40 WARNING (MainThread) [homeassistant.components.sensor] Updating mitemp_bt sensor took longer than the scheduled update interval 0:00:30
2020-09-20 10:23:51 WARNING (SyncWorker_1) [homeassistant.components.mitemp_bt.sensor] Polling error 
2020-09-20 10:24:01 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.casa_tdl_camera_humidity is taking over 10 seconds
2020-09-20 10:24:09 ERROR (updater) [telegram.ext.updater] Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2020-09-20 10:24:10 WARNING (MainThread) [homeassistant.components.sensor] Updating mitemp_bt sensor took longer than the scheduled update interval 0:00:30
2020-09-20 10:24:25 ERROR (stream_worker) [root] Uncaught thread exception
Traceback (most recent call last):
 File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
   self.run()
 File "/usr/local/lib/python3.8/threading.py", line 870, in run
   self._target(*self._args, **self._kwargs)
 File "/usr/src/homeassistant/homeassistant/components/stream/worker.py", line 49, in stream_worker
   container = av.open(stream.source, options=stream.options)
 File "av/container/core.pyx", line 354, in av.container.core.open
 File "av/container/core.pyx", line 225, in av.container.core.Container.__cinit__
 File "av/container/core.pyx", line 257, in av.container.core.Container.err_check
 File "av/error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument: 'rtsp://xxxx:yyyy@192.168.8.90:554/live/ch1'; last error log: [tcp] Port missing in uri
2020-09-20 10:24:40 WARNING (MainThread) [homeassistant.components.sensor] Updating mitemp_bt sensor took longer than the scheduled update interval 0:00:30
2020-09-20 10:24:46 ERROR (updater) [telegram.ext.updater] Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2020-09-20 10:25:06 WARNING (SyncWorker_1) [homeassistant.components.mitemp_bt.sensor] Polling error 
2020-09-20 10:25:17 ERROR (updater) [telegram.ext.updater] Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)

**Comment by sabeechen** [comment] 2020-09-22 17:58
Duplicate #226 
This is a duplicate of issue #226, it appears to happen on any 32bit arm platform with snapshots over a couple GB.  It appears to be a problem in the supervisor, I'm waiting to hear back from the supervisor people about it, I've filed an issue with them [here](https://github.com/home-assistant/supervisor/issues/2047).

**Closed by sabeechen** 2020-09-22 17:58 UTC
