### ISSUE TITLE
An unexpected error occurred: ('Connection aborted.', timeout('The write operation timed out'))

### ISSUE THREAD

**Issue by circa1665** [sabeechen/hassio-google-drive-backup#113] opened 2019-10-19 22:17 UTC
Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 102, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 145, in sync
    upload.addSource(self.dest.save(upload, self.source.read(upload)))
  File "/app/backup/drivesource.py", line 117, in save
    for progress in self.drivebackend.create(bytes, file_metadata, MIME_TYPE):
  File "/app/backup/driverequests.py", line 192, in create
    partial = self.retryRequest("PUT", location, headers=headers, data=data, patch_url=False)
  File "/app/backup/driverequests.py", line 245, in retryRequest
    raise e
  File "/app/backup/driverequests.py", line 234, in retryRequest
    response = self._request_client.request(method, url, headers=send_headers, json=json, timeout=self.config.get(Setting.GOOGLE_DRIVE_TIMEOUT_SECONDS), data=data, stream=stream)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out'))

An unexpected error occurred: ('Connection aborted.', timeout('The write operation timed out'))

**Comment by sabeechen** [comment] 2019-10-21 16:28
This means there was an issue reaching Google from your machine, which is almost always temporary.  If you're still seeing the error, you can increase the the "Google Drive Timeout" in your settings, but most likely something just interrupted your internet connection and the addon will retry once the connection is available again.

**Comment by sabeechen** [comment] 2019-10-21 16:28
Duplicate of #115

**Closed by sabeechen** 2019-10-21 16:28 UTC
