### ISSUE TITLE
Feature request: Backup on target folder named as hostname

### ISSUE THREAD

**Issue by clabnet** [sabeechen/hassio-google-drive-backup#129] opened 2019-11-23 16:04 UTC
Hi,
first of all, your app run very fine. Thanks for your work.

For many reason I have 3 different instances of HA, with 3 instances configured of your plugin.
All running fine and the backups are named correctly based on {hostname} variable.
The backup target folder on Google Drive is the same, because I use always my Google account. 

But not all the 3 instances running for 24h 7/7days.
What happens ? the retention policy do not see also the name of hostname backupped from, and provide to delete also the backupped files related to other HA instances.

I propose to add the possibility of define explicitily the name of target folder on Google drive.

Thanks.

**Comment by sabeechen** [comment] 2019-11-24 01:40
Thats a feature i'm working on, its just taking longer than I hoped.  Right now the only way to do multiple instances is to link them to different Google accounts.  Otherwise, they'll delete eachother's snapshots like you're seeing.
duplicate of #75

**Closed by sabeechen** 2019-11-24 01:40 UTC
