### ISSUE TITLE
Plugin causes HA to crash.

### ISSUE THREAD

**Issue by MarkKlerkx** [sabeechen/hassio-google-drive-backup#578] opened 2022-03-26 09:54 UTC
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```
Everytime when the backup starts to run, it seems that a couple of containers are crashing.
I can logon to the webinterface but a lot of functions showing an error message or are not responsible anymore.
Only a forced restart from the hypervisor can solve this.

Why I think there is a relation with the backup plugin:
First I had a look into the logins and the CPU statistics. I noticed that this is happening every 2 days at 02:00. So this is matching with the backupplan configured in the plugin.

 Addon version: `0.106.2`
 Home Assistant Version: `2022.3.7`
 Supervisor Version: `2022.03.5`
 Supervisor Channel: `stable`
 Hassos Version: `7.5`
 Docker Version: `20.10.9`
 Architecture: `amd64`
 Machine: `qemux86-64`
 Date: `2022-03-26T09:50:47.525740+00:00`
 Timezone: `Europe/Amsterdam`
 Failure Time: `Never`
 Last Good Sync: `2022-03-26T09:48:54.232158+00:00`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 0,
        "retained": 0,
        "deletable": 0,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": null,
        "max": 1,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "0.0 B",
        "ignored_size": "0.0 B",
        "free_space": "19.4 GB"
    },
    "GoogleDrive": {
        "backups": 4,
        "retained": 0,
        "deletable": 4,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2022-03-25T07:30:29Z",
        "max": 4,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "1.4 GB",
        "ignored_size": "0.0 B",
        "free_space": "7.6 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 1,
    "Setting.DAYS_BETWEEN_BACKUPS": 2.0,
    "Setting.DELETE_BEFORE_NEW_BACKUP": true,
    "Setting.BACKUP_TIME_OF_DAY": "02:00",
    "Setting.DELETE_AFTER_UPLOAD": true,
    "Setting.SEND_ERROR_REPORTS": true,
    "Setting.CONFIRM_MULTIPLE_DELETES": false
}
 ```
 ###### Addon Logs:
 ```
 03-26 07:48:46 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
03-26 07:48:46 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
03-26 07:48:46 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-26 07:48:48 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1j9MxeTGNM9wQ2nk-h_k13PeeWAAbnWMO/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
03-26 07:48:48 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
03-26 07:48:48 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271j9MxeTGNM9wQ2nk-h_k13PeeWAAbnWMO%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
03-26 08:48:48 DEBUG [backup.model.syncer] Sync requested by Coordinator
03-26 08:48:48 INFO [backup.model.coordinator] Syncing Backups
03-26 08:48:48 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
03-26 08:48:48 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
03-26 08:48:48 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-26 08:48:51 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1j9MxeTGNM9wQ2nk-h_k13PeeWAAbnWMO/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
03-26 08:48:51 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
03-26 08:48:51 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271j9MxeTGNM9wQ2nk-h_k13PeeWAAbnWMO%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
03-26 09:48:52 DEBUG [backup.model.syncer] Sync requested by Coordinator
03-26 09:48:52 INFO [backup.model.coordinator] Syncing Backups
03-26 09:48:52 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
03-26 09:48:52 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
03-26 09:48:52 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-26 09:48:53 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1j9MxeTGNM9wQ2nk-h_k13PeeWAAbnWMO/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
03-26 09:48:53 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
03-26 09:48:53 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271j9MxeTGNM9wQ2nk-h_k13PeeWAAbnWMO%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
03-26 10:48:54 DEBUG [backup.model.syncer] Sync requested by Coordinator
03-26 10:48:54 INFO [backup.model.coordinator] Syncing Backups
03-26 10:48:54 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/supervisor/info
03-26 10:48:54 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/backups
03-26 10:48:54 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
03-26 10:48:55 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1j9MxeTGNM9wQ2nk-h_k13PeeWAAbnWMO/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
03-26 10:48:55 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
03-26 10:48:55 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271j9MxeTGNM9wQ2nk-h_k13PeeWAAbnWMO%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
 ```
 ###### Supervisor Logs:
 ```
 [32m22-03-26 09:27:49 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m22-03-26 09:27:49 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m22-03-26 09:27:49 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m22-03-26 09:30:27 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m22-03-26 09:48:52 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-03-26 09:48:52 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-03-26 09:49:52 INFO (MainThread) [supervisor.host.info] Updating local host information[0m
[32m22-03-26 09:49:53 INFO (MainThread) [supervisor.host.services] Updating service information[0m
[32m22-03-26 09:49:53 INFO (MainThread) [supervisor.host.network] Updating local network information[0m
[32m22-03-26 09:49:53 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
[32m22-03-26 09:49:53 INFO (MainThread) [supervisor.host.manager] Host information reload completed[0m
[32m22-03-26 10:00:27 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m22-03-26 10:27:49 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m22-03-26 10:27:49 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m22-03-26 10:27:49 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE[0m
[32m22-03-26 10:27:49 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR[0m
[32m22-03-26 10:27:49 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[32m22-03-26 10:27:49 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m22-03-26 10:27:49 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN[0m
[32m22-03-26 10:27:49 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m22-03-26 10:27:49 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m22-03-26 10:27:49 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m22-03-26 10:27:49 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m22-03-26 10:27:49 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m22-03-26 10:29:41 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m22-03-26 10:30:27 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m22-03-26 10:48:54 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m22-03-26 10:48:54 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup[0m
[32m22-03-26 10:50:47 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
     self._send_connected_message(
  File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/homeassistant.py", line 129, in _send_connected_message
    self._connect_hass(
  File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/homeassistant.py", line 102, in _connect_hass
    raise PyChromecastError()
pychromecast.error.PyChromecastError
[0m
[31m2022-03-26 10:18:42 ERROR (SyncWorker_8) [custom_components.tuya] Method [Discovery] fails 1 time(s) using poll interval 605 - error: you can discovery once in 1020 seconds[0m
[33m2022-03-26 10:34:36 WARNING (MainThread) [homeassistant.components.mqtt] Can't decode payload b'\xe3k\xf1Z\xfb\xec\xad\t<\xeb\xa5^\xc2\x81q\xbe \xe0\xa4T\x01\xe4\x1e\xd1\xab\x99"\x16m#\x84K/v\x1c\x90\xc6J_\xed#\x87\xa1\xdc*\xa1\xf0H\xa3gY\xfc]B$\xb2|\xd4\x80\x87\xb4p\xb8\xb3\xc9u\xeb\xe0*\xbf\xcf\xa2\x8f9\n\xe9o^\x98D\xa9}.\x83\xa0G_\xdch\x97\x9e\x7f\xc4)\x1d\x91\xb7E\x0e7\xd0\xc1\x85\x06\xaaIe\x8bvex7\xc3\x80\xbbv\xef\x15m\xec*F\xec\xe9\xf3$\x7fFl\xda\x1bR\t8\xaf\x88=\xd3\x0e|\x88\x88\x9c\xaf\x99\xaa\x91\x87' on jbs-gateway/message with encoding utf-8 (for <Job HassJobType.Callback <function MqttSensor._prepare_subscribe_topics.<locals>.message_received at 0x7fe1280c2670>>)[0m
[33m2022-03-26 10:34:36 WARNING (MainThread) [homeassistant.components.mqtt] Can't decode payload b'\xe3k\xf1Z\xfb\xec\xad\t<\xeb\xa5^\xc2\x81q\xbe \xe0\xa4T\x01\xe4\x1e\xd1\xab\x99"\x16m#\x84K/v\x1c\x90\xc6J_\xed#\x87\xa1\xdc*\xa1\xf0H\xa3gY\xfc]B$\xb2|\xd4\x80\x87\xb4p\xb8\xb3\xc9u\xeb\xe0*\xbf\xcf\xa2\x8f9\n\xe9o^\x98D\xa9}.\x83\xa0G_\xdch\x97\x9e\x7f\xc4)\x1d\x91\xb7E\x0e7\xd0\xc1\x85\x06\xaaIe\x8bvex7\xc3\x80\xbbv\xef\x15m\xec*F\xec\xe9\xf3$\x7fFl\xda\x1bR\t8\xaf\x88=\xd3\x0e|\x88\x88\x9c\xaf\x99\xaa\x91\x87' on jbs-gateway/message with encoding utf-8 (for <Job HassJobType.Callback <function MqttSensor._prepare_subscribe_topics.<locals>.message_received at 0x7fe1280c61f0>>)[0m
[33m2022-03-26 10:34:36 WARNING (MainThread) [homeassistant.components.mqtt] Can't decode payload b'\xe3k\xf1Z\xfb\xec\xad\t<\xeb\xa5^\xc2\x81q\xbe \xe0\xa4T\x01\xe4\x1e\xd1\xab\x99"\x16m#\x84K/v\x1c\x90\xc6J_\xed#\x87\xa1\xdc*\xa1\xf0H\xa3gY\xfc]B$\xb2|\xd4\x80\x87\xb4p\xb8\xb3\xc9u\xeb\xe0*\xbf\xcf\xa2\x8f9\n\xe9o^\x98D\xa9}.\x83\xa0G_\xdch\x97\x9e\x7f\xc4)\x1d\x91\xb7E\x0e7\xd0\xc1\x85\x06\xaaIe\x8bvex7\xc3\x80\xbbv\xef\x15m\xec*F\xec\xe9\xf3$\x7fFl\xda\x1bR\t8\xaf\x88=\xd3\x0e|\x88\x88\x9c\xaf\x99\xaa\x91\x87' on jbs-gateway/message with encoding utf-8 (for <Job HassJobType.Callback <function MqttSensor._prepare_subscribe_topics.<locals>.message_received at 0x7fe1280c6b80>>)[0m
[33m2022-03-26 10:34:36 WARNING (MainThread) [homeassistant.components.mqtt] Can't decode payload b'\xe3k\xf1Z\xfb\xec\xad\t<\xeb\xa5^\xc2\x81q\xbe \xe0\xa4T\x01\xe4\x1e\xd1\xab\x99"\x16m#\x84K/v\x1c\x90\xc6J_\xed#\x87\xa1\xdc*\xa1\xf0H\xa3gY\xfc]B$\xb2|\xd4\x80\x87\xb4p\xb8\xb3\xc9u\xeb\xe0*\xbf\xcf\xa2\x8f9\n\xe9o^\x98D\xa9}.\x83\xa0G_\xdch\x97\x9e\x7f\xc4)\x1d\x91\xb7E\x0e7\xd0\xc1\x85\x06\xaaIe\x8bvex7\xc3\x80\xbbv\xef\x15m\xec*F\xec\xe9\xf3$\x7fFl\xda\x1bR\t8\xaf\x88=\xd3\x0e|\x88\x88\x9c\xaf\x99\xaa\x91\x87' on jbs-gateway/message with encoding utf-8 (for <Job HassJobType.Callback <function MqttSensor._prepare_subscribe_topics.<locals>.message_received at 0x7fe1280ca550>>)[0m
[33m2022-03-26 10:34:36 WARNING (MainThread) [homeassistant.components.mqtt] Can't decode payload b'\xe3k\xf1Z\xfb\xec\xad\t<\xeb\xa5^\xc2\x81q\xbe \xe0\xa4T\x01\xe4\x1e\xd1\xab\x99"\x16m#\x84K/v\x1c\x90\xc6J_\xed#\x87\xa1\xdc*\xa1\xf0H\xa3gY\xfc]B$\xb2|\xd4\x80\x87\xb4p\xb8\xb3\xc9u\xeb\xe0*\xbf\xcf\xa2\x8f9\n\xe9o^\x98D\xa9}.\x83\xa0G_\xdch\x97\x9e\x7f\xc4)\x1d\x91\xb7E\x0e7\xd0\xc1\x85\x06\xaaIe\x8bvex7\xc3\x80\xbbv\xef\x15m\xec*F\xec\xe9\xf3$\x7fFl\xda\x1bR\t8\xaf\x88=\xd3\x0e|\x88\x88\x9c\xaf\x99\xaa\x91\x87' on jbs-gateway/message with encoding utf-8 (for <Job HassJobType.Callback <function MqttSensor._prepare_subscribe_topics.<locals>.message_received at 0x7fe1280cb1f0>>)[0m
[33m2022-03-26 10:34:36 WARNING (MainThread) [homeassistant.components.mqtt] Can't decode payload b'\xe3k\xf1Z\xfb\xec\xad\t<\xeb\xa5^\xc2\x81q\xbe \xe0\xa4T\x01\xe4\x1e\xd1\xab\x99"\x16m#\x84K/v\x1c\x90\xc6J_\xed#\x87\xa1\xdc*\xa1\xf0H\xa3gY\xfc]B$\xb2|\xd4\x80\x87\xb4p\xb8\xb3\xc9u\xeb\xe0*\xbf\xcf\xa2\x8f9\n\xe9o^\x98D\xa9}.\x83\xa0G_\xdch\x97\x9e\x7f\xc4)\x1d\x91\xb7E\x0e7\xd0\xc1\x85\x06\xaaIe\x8bvex7\xc3\x80\xbbv\xef\x15m\xec*F\xec\xe9\xf3$\x7fFl\xda\x1bR\t8\xaf\x88=\xd3\x0e|\x88\x88\x9c\xaf\x99\xaa\x91\x87' on jbs-gateway/message with encoding utf-8 (for <Job HassJobType.Callback <function MqttSensor._prepare_subscribe_topics.<locals>.message_received at 0x7fe1280cb8b0>>)[0m
[33m2022-03-26 10:34:36 WARNING (MainThread) [homeassistant.components.mqtt] Can't decode payload b'\xe3k\xf1Z\xfb\xec\xad\t<\xeb\xa5^\xc2\x81q\xbe \xe0\xa4T\x01\xe4\x1e\xd1\xab\x99"\x16m#\x84K/v\x1c\x90\xc6J_\xed#\x87\xa1\xdc*\xa1\xf0H\xa3gY\xfc]B$\xb2|\xd4\x80\x87\xb4p\xb8\xb3\xc9u\xeb\xe0*\xbf\xcf\xa2\x8f9\n\xe9o^\x98D\xa9}.\x83\xa0G_\xdch\x97\x9e\x7f\xc4)\x1d\x91\xb7E\x0e7\xd0\xc1\x85\x06\xaaIe\x8bvex7\xc3\x80\xbbv\xef\x15m\xec*F\xec\xe9\xf3$\x7fFl\xda\x1bR\t8\xaf\x88=\xd3\x0e|\x88\x88\x9c\xaf\x99\xaa\x91\x87' on jbs-gateway/message with encoding utf-8 (for <Job HassJobType.Callback <function MqttSensor._prepare_subscribe_topics.<locals>.message_received at 0x7fe127d39280>>)[0m
[33m2022-03-26 10:34:36 WARNING (MainThread) [homeassistant.components.mqtt] Can't decode payload b'\xe3k\xf1Z\xfb\xec\xad\t<\xeb\xa5^\xc2\x81q\xbe \xe0\xa4T\x01\xe4\x1e\xd1\xab\x99"\x16m#\x84K/v\x1c\x90\xc6J_\xed#\x87\xa1\xdc*\xa1\xf0H\xa3gY\xfc]B$\xb2|\xd4\x80\x87\xb4p\xb8\xb3\xc9u\xeb\xe0*\xbf\xcf\xa2\x8f9\n\xe9o^\x98D\xa9}.\x83\xa0G_\xdch\x97\x9e\x7f\xc4)\x1d\x91\xb7E\x0e7\xd0\xc1\x85\x06\xaaIe\x8bvex7\xc3\x80\xbbv\xef\x15m\xec*F\xec\xe9\xf3$\x7fFl\xda\x1bR\t8\xaf\x88=\xd3\x0e|\x88\x88\x9c\xaf\x99\xaa\x91\x87' on jbs-gateway/message with encoding utf-8 (for <Job HassJobType.Callback <function MqttSensor._prepare_subscribe_topics.<locals>.message_received at 0x7fe127d39c10>>)[0m
[31m2022-03-26 10:36:05 ERROR (SyncWorker_6) [homeassistant.util.logging] Exception in _handle_signal_show_view when dispatching 'cast_show_view': (<pychromecast.controllers.homeassistant.HomeAssistantController object at 0x7fe113ce8f40>, 'media_player.nesthubbe7d', '0', 'google-nest')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 875, in _handle_signal_show_view
    self._hass_cast_controller.show_lovelace_view(view_path, url_path)
  File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/homeassistant.py", line 118, in show_lovelace_view
    self._send_connected_message(
  File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/homeassistant.py", line 129, in _send_connected_message
    self._connect_hass(
  File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/homeassistant.py", line 102, in _connect_hass
    raise PyChromecastError()
pychromecast.error.PyChromecastError
[0m
[31m2022-03-26 10:39:12 ERROR (SyncWorker_4) [custom_components.tuya] Method [Discovery] fails 1 time(s) using poll interval 605 - error: you can discovery once in 1020 seconds[0m

 ```

**Comment by sabeechen** [comment] 2022-03-27 21:03
I don't have a good sense for what might be causing this, so here is some general information that might help you isolate the problem.  This add-on does two main things when a backup is made that might cause this:

1. It asks Home Assistant to create a backup.  Home Assistant's Supervisor is the one who actually creates the backup.  During this time you should see high CPU usage as it compresses the backup and lots of disk activity as it writes it to disk
2. Afterward it uploads the backup to Google Drive.  During this time you'll see high disk activity and network activity.

Of course neither of these things should cause what you're seeing.  Because Home Assistant creates the backup, its likely there is some information or error messages in the supervisor's log that could indicate what the problem is when things goes wrong at 2AM.

- To test if (1) is the problem, create a backup from the Home Assistant UI (Configuration -> Add-ons, Backups & Supervisor -> Backups -> Create Backup).  If things get bad, check the supervisor logs (Configuration -> Add-ons, Backups & Supervisor -> System -> Log Provider -> Supervisor)
- To test if (2) is the problem, in the add-on web-ui:
  - Click a snapshot and select "Load into Home Assistant"
  - Delete it From Google Drive
  - Click "Sync Now"  to have it upload to Google Drive again.

I suspect (1) is where you'll see problems, the supervisor logs are where any issues Home Assistant had creating backups should show up.

**Comment by sabeechen** [comment] 2022-03-27 21:10
Its also worth noting that on some machines, the process of creating a backup can be very resource intensive, which can make the Home Assistant web-ui perform very sluggishly.  It could just be that the machine is bogged down until the backup is finished.

**Comment by sabeechen** [comment] 2022-05-03 18:30
I'm closing this for now, but please let me know if you think there is something else I can help with.

**Closed by sabeechen** 2022-05-03 18:30 UTC
