### ISSUE TITLE
Google drive backup issues

### ISSUE THREAD

**Issue by nikiyao** [sabeechen/hassio-google-drive-backup#43] opened 2019-05-07 23:38 UTC
Can't connect

**Comment by sabeechen** [comment] 2019-05-07 23:42
I'm gonna need a little more info than that to help.  What is the text of the error, what do your logs say, and what configuration are you using?  Are you using the latest version of the add-on?

**Comment by nikiyao** [comment] 2019-05-07 23:50
Sorry I thought that was sending logs. It's the same issue as others are
reporting and that I have reported previously. The new version just gave me
that option which I hadn't had before so I was hoping it would help.

**Comment by sabeechen** [comment] 2019-05-07 23:56
No worries.  Is it showing up as?
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries exceeded with url: <long url> (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa0b8249828>: Failed to establish a new connection: [Errno -3] Try again',)):`

Even if you set the 'drive_ipv4' config option ( [see here](https://github.com/sabeechen/hassio-google-drive-backup/issues/15#issuecomment-489470212) for reference)?

**Comment by nikiyao** [comment] 2019-05-07 23:58
Log

05-07 19:57:56 INFO Loading config from /data/options.json
05-07 19:57:56 INFO Starting server on port 8099
05-07 19:57:56 INFO Starting server on port 1627
05-07 19:57:56 INFO Server started
05-07 19:58:01 ERROR
Traceback (most recent call last):
  File "/app/backup/engine.py", line 162, in doBackupWorkflow
    self._checkForBackup()
  File "/app/backup/engine.py", line 401, in _checkForBackup
    self._syncSnapshots()
  File "/app/backup/engine.py", line 332, in _syncSnapshots
    self.folder_id = self.drive.getFolderId()
  File "/app/backup/drive.py", line 142, in getFolderId
    return self._findDriveFolder()
  File "/app/backup/drive.py", line 150, in _findDriveFolder
    for child in self.drivebackend.query("mimeType='" + FOLDER_MIME_TYPE + "'"):
  File "/app/backup/driverequests.py", line 144, in query
    response = self.retryRequest("GET", URL_FILES + "?" +
urlencode(q), is_json=True)
  File "/app/backup/driverequests.py", line 216, in retryRequest
    response = request(method, url, headers=send_headers, json=json,
timeout=(30, 30), data=data, stream=stream)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line
533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line
646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line
516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError:
HTTPSConnectionPool(host='www.googleapis.com', port=443): Max retries
exceeded with url:
/drive/v3/files/?q=mimeType%3D%27application%2Fvnd.google-apps.folder%27&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%29&pageSize=100
(Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection
object at 0x7f8e42b04198>: Failed to establish a new connection:
[Errno -3] Try again',))


05-07 19:58:01 ERROR A retry will be attempted in 10 seconds

**Comment by nikiyao** [comment] 2019-05-07 23:59
Yes I made those changes and still got the same error. I'll try restarting
hassio as well.

**Comment by nikiyao** [comment] 2019-05-08 00:02
Yeah still no luck.

**Comment by sabeechen** [comment] 2019-05-18 20:05
I've made a lot of changes in the latest release (v0.97) to have a more resilient connection to Google Drive, particularly failing over to known good DNS servers if it has trouble.  Could you see if the latest version fixes this for you?

**Comment by sabeechen** [comment] 2019-05-21 16:57
I'm closing this for now just to keep my bug list clean, but please reopen if you still see the problem with the latest version.

**Closed by sabeechen** 2019-05-21 16:57 UTC
Labels: bug
