### ISSUE TITLE
Couldn't Refresh Google Drive Credentials

### ISSUE THREAD

**Issue by PCServices2** [sabeechen/hassio-google-drive-backup#765] opened 2022-12-12 15:46 UTC
I'm having trouble with "Couldn't Refresh Google Drive Credentials" message and HA giving me a notification of a problem with the backup. I re-authenticate and it works, usually, until the following day. I then have to go through the whole procedure again.

[home-assistant-google-drive-backup.log](https://github.com/sabeechen/hassio-google-drive-backup/files/10209642/home-assistant-google-drive-backup.log)

**Comment by sabeechen** [comment] 2022-12-13 19:49
This looks like just an internet connectivity issue, its having trouble connecting to the add-on's authentication server (https://token1.habackup.io) and its backup server (https://habackup.io), both of which are up right now and successfully serving authentication requests.  Are you sure your Home Assistant is able to connect to the internet reliably?

**Comment by PCServices2** [comment] 2022-12-14 03:32
I am able to confirm connectivity as it’s also my DNS server. I’ve checked the URL’s you mentioned in the DNS logs and they are not being blocked. My other HA Pi has not had this issue and uses the Pi that has the problem as its DNS resolver.

**Comment by sabeechen** [comment] 2023-01-01 04:25
Sorry for taking a while to get back.  Things just keep getting in the way.

As someone who has done more DNS hackery than they should my first thought when reading your response is that the DNS host server is unable to reach itself from inside containers running on the same host, which is a frustratingly common problem on hosts running dns inside docker containers (for example because of port 53 binding conflict).  The timeout being reported could actually be caused by a timeout attempting to resolve the host rather than communicate with it.  [This shirt](https://www.amazon.com/Always-sysadmin-network-administrator-tshirt/dp/B07H6SSH2Q/ref=sr_1_4?crid=ER1070VN4CJK&keywords=it%27s+always+dns&qid=1672546757&sprefix=its+always+dns%2Caps%2C104&sr=8-4) is popular for good reason.

Aside from that, I'm not sure how I can help further.  I've had a lot of people report bugs for connectivity issues, but I don't think I've ever actually done anything on my side that resolved a single one of them.  The addon isn't doing anything special when it attempts to contact Google of habackup.io, its just making a regular HTTP request. The fact that one of your machines on the network running the same software is running fine leads me to think there has to be something special about that machine.

**Comment by sabeechen** [comment] 2023-03-24 16:06
I'm going to close this issue for now, but if you think there is something else I can help with please reopen and let me know.

**Closed as completed by sabeechen** 2023-03-24 16:06 UTC
