### ISSUE TITLE
Oldest snapshot not automatically deleting in Drive

### ISSUE THREAD

**Issue by joshward9182** [sabeechen/hassio-google-drive-backup#338] opened 2021-02-02 23:43 UTC
Oldest snapshot isn't being deleted in Drive before the new one is synced, creating the error in the following image.
Manual deletion & sync works fine.

![Screenshot_20210202-233345](https://user-images.githubusercontent.com/69898979/106676757-626e2580-65af-11eb-8c08-bf68c0692f5f.jpg)

**Comment by sabeechen** [comment] 2021-02-04 18:19
This behavior is [by design](https://github.com/sabeechen/hassio-google-drive-backup#i-configured-this-to-only-keep-4-snapshots-in-drive-and-home-assistant-but-sometimes-i-can-see-there-are-5).  when keeping N snapshots it won't delete the oldest one until a new one is uploaded, so you need to have space for N+1 snapshots.  I'll be adding an option in the future to delete more aggressively as you desire, but I can't provide a good estimate of when that will be released.

In the meantime your options are:

- Keep fewer snapshots in Google Drive
- Buy more space for storage
- Make smaller snapshots (eg use partial snapshots)

**Comment by joshward9182** [comment] 2021-02-04 18:27
Understood!

Thanks for the response and clarification 🙂

**Closed** 2021-02-04 18:28 UTC
