### ISSUE TITLE
An unexpected error occurred: ('Connection aborted.', timeout('The write operation timed out'))

### ISSUE THREAD

**Issue by stanislavmerts** [sabeechen/hassio-google-drive-backup#108] opened 2019-10-18 15:44 UTC
Hello! I have some problems saving snapshots to the cloud.
I activated ingress mode and update addon to latest version. 
After that, I ran into the problem that my snapshot is not saved to the cloud.
10-18 23:28:14 INFO Saving snapshot folder: 1SANqS9joLurCXTGOwYcFWWqBX8MM6rto
10-18 23:31:21 ERROR 
Traceback (most recent call last):
  File "/app/backup/coordinator.py", line 102, in _sync
    self._buildModel().sync(self._time.now())
  File "/app/backup/model.py", line 145, in sync
    upload.addSource(self.dest.save(upload, self.source.read(upload)))
  File "/app/backup/drivesource.py", line 117, in save
    for progress in self.drivebackend.create(bytes, file_metadata, MIME_TYPE):
  File "/app/backup/driverequests.py", line 192, in create
    partial = self.retryRequest("PUT", location, headers=headers, data=data, patch_url=False)
  File "/app/backup/driverequests.py", line 245, in retryRequest
    raise e
  File "/app/backup/driverequests.py", line 234, in retryRequest
    response = self._request_client.request(method, url, headers=send_headers, json=json, timeout=self.config.get(Setting.GOOGLE_DRIVE_TIMEOUT_SECONDS), data=data, stream=stream)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out'))
10-18 23:31:21 INFO Another attempt to sync will be made in 40 seconds
[hassio-google-drive-backup (3).log](https://github.com/sabeechen/hassio-google-drive-backup/files/3744694/hassio-google-drive-backup.3.log)

**Comment by sabeechen** [comment] 2019-10-18 17:27
Based on your log it looks like its making some progress on the upload, but then *something* happens and the connection to google times out and it has to start over.  Transient errors like this happen from time to time, but it is strange you're seeing them over and over again.  Eventually your upload should succeed, but it might take a while if your snapshots are large.

I'll be releasing a new version in the next few days that resumes partially uploaded snapshots better, which should make this less of a problem.

**Comment by stanislavmerts** [comment] 2019-10-18 18:07
I try change timeout to 220, change google account and downgrade to version 0.98.2.
Once the upload on the new google account was successful. But on the next snapshot, the error repeated.
My snapshot is 500Mb about.

**Comment by sabeechen** [comment] 2019-10-21 16:32
Duplicate of #115

**Closed by sabeechen** 2019-10-21 16:32 UTC
Labels: bug
