### ISSUE TITLE
Need to use a bearer token to access binary sensor

### ISSUE THREAD

**Issue by rschuiling** [sabeechen/hassio-google-drive-backup#33] opened 2019-04-30 20:15 UTC
Just upgraded to HA 0.92.1, now I'm getting this error in the log:

api_password is going to deprecate. You need to use a bearer token to access /api/states/binary_sensor.snapshots_stale from 172.30.32.2

This was also mentioned on the community forum topic by another user 22 days ago. I could not find a mention of it in the issues here on Github. Is this something that should be fixed?

**Comment by sabeechen** [comment] 2019-04-30 20:37
I'm pretty confident this is actually a [Hassio bug](https://github.com/home-assistant/hassio/issues/1063) fixed a few days ago.  I'd expect to see it go away in the next release, but if not I'll look into it further.  The add-on talks to Home Assistant through an add-on-only proxy that Hassio exposes, its never used API password.

**Comment by sabeechen** [comment] 2019-04-30 20:48
This log message still comes up when I get rid of api_password on my test rig, so I'm feeling more certain it's just a logging bug on the Hassio side of things.  Can't use an api password if there isn't one in the first place.

**Comment by IsaTTeN** [comment] 2019-05-03 13:34
Same here, just updated Hassio today to 0.92.2 but the error is still there:

`3 WARNING (MainThread) [homeassistant.components.http.auth] api_password is going to deprecate. You need to use a bearer token to access /api/states/binary_sensor.snapshots_stale from 172.30.32.2`

**Comment by sabeechen** [comment] 2019-05-03 22:01
Looks like it really is something I'm doing wrong.  I'll work on a fix for the next release.

**Comment by sabeechen** [comment] 2019-05-04 04:42
I've been unable to figure out how I might be using the add-on api wrong, so I've [asked the Hassio folks for help](https://github.com/home-assistant/hassio/issues/1071).

**Comment by IsaTTeN** [comment] 2019-05-04 10:18
Thanks!

**Comment by sabeechen** [comment] 2019-05-05 22:52
A Hassio dev has confirmed that this is in fact a hassio problem, and that its fixed in their dev branch.  I'm not sure when they merge in dev, but I'd expect it to be soon.

**Closed by sabeechen** 2019-05-05 22:52 UTC
Labels: bug
