### ISSUE TITLE
Snapshot time of day not at specified time

### ISSUE THREAD

**Issue by nikee73** [sabeechen/hassio-google-drive-backup#166] opened 2020-03-17 19:09 UTC
I have snapshot_time_of_day: '12:00' but snapshots are never taken at that time. Snapshots are taken up to 55 minutes after that time. Last days the time was:
12:05
12:18
12:20
12:54
12:41

I'm on the latest version of the add-on v0.100.0
My config:
max_snapshots_in_hassio: 7
max_snapshots_in_google_drive: 14
days_between_snapshots: 1
use_ssl: false
generational_day_of_week: sun
snapshot_time_of_day: '12:00'
snapshot_name: '{year}-{month}-{day} {hr24}:{min} {version_ha} {type}'
send_error_reports: false
confirm_multiple_deletes: false
generational_days: 7
generational_weeks: 4
generational_months: 12
generational_years: 5
background_color: '#ffffff'

[hassio-google-drive-backup.log](https://github.com/sabeechen/hassio-google-drive-backup/files/4345285/hassio-google-drive-backup.log)

**Comment by sabeechen** [comment] 2020-03-17 20:43
Something is definitely wrong.  The logs definitely show it doesn't even start the snapshot until after 12.   Thanks for posting all that, I'll need to dig into the code.
I'm wondering how long this has been happening and for how many users without them noticing (or caring?).  I haven't touched the logic for when a snapshot happens for many months.  Maybe its always been this way? Thankfully it doesn't seem like it is cause *serious* problems, since the snapshots are still happen *roughly* on schedule.

**Comment by nikee73** [comment] 2020-03-17 20:52
I've had this problem since I started using this add-on about 3 weeks ago. Didn't really bother me as snapshots was taken and uploaded just not on the specified time

**Comment by sabeechen** [comment] 2020-03-17 21:01
I'm starting to suspect this is a timezone conversion problem.  Do you know what timezone your Home Assistant machine is running under?  
You should be able to see it under Configuration > General > Time Zone

**Comment by nikee73** [comment] 2020-03-17 21:51
My time zone in Home Assistant is Europe/Stockholm

**Comment by kersten-lohmeyer** [comment] 2020-03-18 06:08
Same Problem over here in Europe/Berlin, snapshot time should be 5am and actually is:

05:21
05:29
05:30

**Comment by sabeechen** [comment] 2020-03-19 18:08
I've been trying to reproduce this in my dev environment but so far have been unsuccessful using any timezone.  Even when a snapshot is created very late, the new one gets made on time the next day.

I have more theories but they'll take longer to test.  Could I have one or both of you restart the addon and see if it creates a snapshot at the correct time the following day?

**Comment by nikee73** [comment] 2020-03-19 20:58
I can do a restart of the add-on now.
Todays snapshot was taken at 12:33 but settings had the time 12:00
Will get beck tomorrow with at what time yesterday snapshot was taken

**Comment by kersten-lohmeyer** [comment] 2020-03-20 05:36
I restartet the addon yesterday and the snapshot took place at 5:11 today.

**Comment by nikee73** [comment] 2020-03-20 14:03
Restarted yesterday and snapshot today was at 12:59
So a restart of add-on didn't help

**Comment by nikee73** [comment] 2020-03-21 14:01
Todays snapshot was at 12:42

**Comment by nikee73** [comment] 2020-04-10 20:05
Snapshot times the last week:
12:43
12:45
12:47
12:49
12:52
12:54
12:56

So it drifts/adds 2minutes every day and never takes the snapshot at 12:00 which is the time I have in settings

**Comment by kersten-lohmeyer** [comment] 2020-04-11 05:51
> Snapshot times the last week:
> 12:43
> 12:45
> 12:47
> 12:49
> 12:52
> 12:54
> 12:56
> 
> So it drifts/adds 2minutes every day and never takes the snapshot at 12:00 which is the time I have in settings

Same for me. Roughly two minutes later every day.

**Comment by beliy1985** [comment] 2020-05-19 22:14
Same "problem" over here in Russia, snapshot time should be 00:00 and actually is 00:10 - 00:50
I use nearly a year

**Comment by nikee73** [comment] 2020-08-16 18:42
> I've been trying to reproduce this in my dev environment but so far have been unsuccessful using any timezone. Even when a snapshot is created very late, the new one gets made on time the next day.
> 
> I have more theories but they'll take longer to test. Could I have one or both of you restart the addon and see if it creates a snapshot at the correct time the following day?

Any status on this error?

**Comment by kersten-lohmeyer** [comment] 2020-08-16 18:46
> > I've been trying to reproduce this in my dev environment but so far have been unsuccessful using any timezone. Even when a snapshot is created very late, the new one gets made on time the next day.
> > I have more theories but they'll take longer to test. Could I have one or both of you restart the addon and see if it creates a snapshot at the correct time the following day?
> 
> Any status on this error?

in any case it is not fixed in the current version

**Comment by sabeechen** [comment] 2020-08-19 04:52
Its definitely still an issue.  In fact I finally saw it happen on my home machine, after leaving it running for ~30 days without a restart, about a minute of drift each day after a few weeks.
I'm still at a loss as to why it happens.  I've scoured over the code, written dozens of tests, and even wrote a one-off version of the addon that runs at 10,000x simulated speed (eg a simulated clock).  Every test turns out the same, no drift.

It's probably a simple, stupid mistake somewhere in my logic, though honestly the logic for figuring out when is the next time to snapshot isn't very complicated.

Honestly, I'm at a place where I'm running out of ideas to test out for what might be wrong :(

**Comment by nikee73** [comment] 2020-10-17 11:32
Any update on this? Snapshot actual time is off by up to 55 minutes

**Comment by sabeechen** [comment] 2020-10-27 01:47
Still stumped!

**Comment by daconrad0** [comment] 2020-11-29 04:38
My HASSIO is running EST and the snapshots seem to be in GMT.  Wondering if this related?

**Comment by GazTheGeek** [comment] 2020-12-09 09:35
I have 2 HA Instances in different locations not connected to each other.
Both are in the same time zone Melbourne/Australia.
Both running on a Pi 4B
I have configured the the snapshot time on both of them for 2:00
Both are up to date running the latest HA 118.5
On one the actual snapshot Times occur between 2:07 and 2:55 with no real consistency (This is fine by me)
On the other the snapshots occur between 7:04 and 10:11 (so up to 8 hours after the selected time) this isn't what I want. All other time related functions appear to be working fine.

**Comment by GazTheGeek** [comment] 2020-12-10 03:32
> I have 2 HA Instances in different locations not connected to each other.
> Both are in the same time zone Melbourne/Australia.
> Both running on a Pi 4B
> I have configured the the snapshot time on both of them for 2:00
> Both are up to date running the latest HA 118.5
> On one the actual snapshot Times occur between 2:07 and 2:55 with no real consistency (This is fine by me)
> On the other the snapshots occur between 7:04 and 10:11 (so up to 8 hours after the selected time) this isn't what I want. All other time related functions appear to be working fine.

Update: I changed the time of backups to 1:00 and the result was a backup at 4:44 So setting the time to 1 hr earlier resulted in a backup 2hrs 16 mins earlier than the earliest back prior. I'm feeling for the dev on this issue. Must be very hard to isolate the issue. Hard to replicate. Let me know if I can help with testing anything.

**Comment by leeandy1** [comment] 2020-12-29 14:52
I also have this issue and have noticed the longer it goes on the more out of sync the snapshot is. For example my snapshots are set to run at 2 am, the snapshot today actually run at 7:16 am. I have noticed that it seems to run 2 minutes later each day.

**Comment by jhampson-dbre** [comment] 2021-01-09 13:48
This "feels" like it has something to due with the `days_between_snapshots: 1` being in days and `snapshot_time_of_day: '03:23'` being in hours minutes. In my case, it looks like it initially is running at `03:23` and then every 24 hours after the last backup completes.

```
01-08 03:30:42 INFO Requesting a new snapshot
01-08 03:32:07 INFO Snapshot finished
.....
01-09 03:33:00 INFO Requesting a new snapshot
01-09 03:34:23 INFO Snapshot finished
````

**Comment by jhampson-dbre** [comment] 2021-01-09 14:03
@sabeechen I'd be happy to dig into this. Can tell me if I'm heading in the right direction? It looks like the snapshot timing logic is in models.py at:

```python
    def nextSnapshot(self, now: datetime):
        latest = max(self.snapshots.values(),
                     default=None, key=lambda s: s.date())
        if latest:
            latest = latest.date()
        return self._nextSnapshot(now, latest)
```

And then this is called in used in `Model.sync` to initiate snapshot at:

```python
        next_snapshot = self.nextSnapshot(now)
        if next_snapshot and now >= next_snapshot and self.source.enabled() and not self.dest.needsConfiguration():
            await self.createSnapshot(CreateOptions(now, self.config.get(Setting.SNAPSHOT_NAME)))
            await self._purge(self.source)
```
Anything I'm overlooking about how snapshot scheduling works?

**Comment by sabeechen** [comment] 2021-01-09 18:35
Gods yes, please do.  Another pair of eyes might be able to see for miles.  I've stared at this one for hours, written dozens of tests and come up with nothing.  The problem, whatever it is, seems to only happen if it runs for several days continously which makes debugging very difficult and slow.

You're on the right track, here are some other pointers with more detail.
The full chain of events that makes a new scheduled snapshot is that once ever 0.5 seconds:
- [Syncer.py:27](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/hassio-google-drive-backup/backup/model/syncer.py#L27) calls Worker.Check
- [Coordinator.py](https://github.com/sabeechen/hassio-google-drive-backup/blob/1b2681d50edade3553d0d18cd4ccbe5694535b62/hassio-google-drive-backup/backup/model/coordinator.py#L55) implements check() and returns true if the current time is greater than [Coordinator.nextSyncAttempt()](https://github.com/sabeechen/hassio-google-drive-backup/blob/1b2681d50edade3553d0d18cd4ccbe5694535b62/hassio-google-drive-backup/backup/model/coordinator.py#L83).  This should be the next time to try syncing between HA and Google Drive, creating new snapshot, or seeing if any snapshot needs to be deleted.
- nextSyncAttempt() then returns [Model.nextSnapshot()](https://github.com/sabeechen/hassio-google-drive-backup/blob/1b2681d50edade3553d0d18cd4ccbe5694535b62/hassio-google-drive-backup/backup/model/model.py#L139), as you've noted.

That all causes [Syncer ](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/hassio-google-drive-backup/backup/model/syncer.py)to think a sync needs to happen, so it calls [Coordinator.sync()](https://github.com/sabeechen/hassio-google-drive-backup/blob/1b2681d50edade3553d0d18cd4ccbe5694535b62/hassio-google-drive-backup/backup/model/coordinator.py#L62) which (after a bunch of threading non-sense to make thing interruptable) calls Model.sync [here](https://github.com/sabeechen/hassio-google-drive-backup/blob/1b2681d50edade3553d0d18cd4ccbe5694535b62/hassio-google-drive-backup/backup/model/coordinator.py#L156), and from there you've already figured out where it calls to create a new snapshot.

**Comment by jhampson-dbre** [comment] 2021-01-11 21:28
@sabeechen I'm a little lost on how the configurations set in the Home Assistant UI make their way into the Google Drive Backup addon runtime config. I checked in  `/data/options.json` inside the running container for the add-on, but it didn't seem to match up with what was configured in the add-on UI. Any insight on how the user provided value for SNAPSHOT_TIME_OF_DAY is provided to the application?

**Comment by sabeechen** [comment] 2021-01-11 21:53
Config.py contains all the logic for reading the configuration.  the configuration is read as 
```python
config.get(Setting.SNAPSHOT_TIME_OF_DAY)
```
which shoudl return something like "03:00".  It either returns the config from a cache or returns the default value, the empty string.
The config object loads its setting in a few ways:

1. When the addon starts it parses /data/config.json ([see here](https://github.com/sabeechen/hassio-google-drive-backup/blob/1b2681d50edade3553d0d18cd4ccbe5694535b62/hassio-google-drive-backup/backup/__main__.py#L32))
2. Every time the addon syncs (usually once an hour) it asks the supervisor if the config has changed and updates its local cache ([see here](https://github.com/sabeechen/hassio-google-drive-backup/blob/1b2681d50edade3553d0d18cd4ccbe5694535b62/hassio-google-drive-backup/backup/ha/hasource.py#L304)).  This is in case you update the config through home assistant without restarting the addon.
3. The config can be overwritten by using the settings dialog in the addon web UI, which ends up calling [this method](https://github.com/sabeechen/hassio-google-drive-backup/blob/1b2681d50edade3553d0d18cd4ccbe5694535b62/hassio-google-drive-backup/backup/ui/uiserver.py#L437) in the addon webserver to save the configuration.

I also should ahve mentioned earlier I have a short guide to setting up a local development environment for the addon [here](https://github.com/sabeechen/hassio-google-drive-backup/blob/1b2681d50edade3553d0d18cd4ccbe5694535b62/CONTRIBUTING.md).

**Comment by jhampson-dbre** [comment] 2021-01-14 18:43
I wrote some tests that validate:
when `nextSnapshotTime()` is before next `scheduled` time, then `nextSnapshotTime()` is returned by `nextSyncAttempt()`
and
when `nextSnapshotTime()` is after next `scheduled` time, then `scheduled` is returned by `nextSyncAttempt()`

I can open PR with those tests if you're interested in including them.

I also validated that :
when the current time is greater than `nextSyncAttempt()`, then `coordinator.check()` returns `True`

From observating over the last few days, when a scheduled sync runs after the scheduled snapshot time, it knows that the 
next snapshot time has been exceeded takes a snapshot as part of the scheduled sync.

All of the above seems to work as designed.

All that leads me to believe that Syncer is not calling `coordinator.check()` as frequently as expected. Or maybe there is some other problem with Syncer, but that main component of the process that I haven't been able to rule out yet.

**Comment by jhampson-dbre** [comment] 2021-01-16 22:31
Well, I was wrong about Syncer being the problem. I added some debug logging and ran it as a local addon.

@sabeechen the problematic code seems to be in [model._nextSnapshot](https://github.com/sabeechen/hassio-google-drive-backup/blob/1b2681d50edade3553d0d18cd4ccbe5694535b62/hassio-google-drive-backup/backup/model/model.py#L134)
```python
        if next < now:
            return now
        else:
            return next
```
From the added logging, we can see where this becomes a problem with setting `snapshot_time_of_day: '20:10'`:
```
01-16 14:09:59 DEBUG [backup.model.coordinator] Checking if current time 2021-01-16 20:09:59.407093+00:00 is greater than next sync time 2021-01-16 20:10:00+00:00.
01-16 14:09:59 DEBUG [backup.model.coordinator] coordinator check returning: False
01-16 14:09:59 DEBUG [backup.model.syncer] No syncs this cycle
01-16 14:09:59 DEBUG [backup.model.coordinator] Checking if current time 2021-01-16 20:09:59.909147+00:00 is greater than next sync time 2021-01-16 20:10:00+00:00.
01-16 14:09:59 DEBUG [backup.model.coordinator] coordinator check returning: False
01-16 14:09:59 DEBUG [backup.model.syncer] No syncs this cycle
01-16 14:10:00 DEBUG [backup.model.coordinator] Checking if current time 2021-01-16 20:10:00.411052+00:00 is greater than next sync time 2021-01-16 20:10:00.411411+00:00.
01-16 14:10:00 DEBUG [backup.model.coordinator] coordinator check returning: False
01-16 14:10:00 DEBUG [backup.model.syncer] No syncs this cycle
01-16 14:10:00 DEBUG [backup.model.coordinator] Checking if current time 2021-01-16 20:10:00.913732+00:00 is greater than next sync time 2021-01-16 20:10:00.914047+00:00.
01-16 14:10:00 DEBUG [backup.model.coordinator] coordinator check returning: False
01-16 14:10:00 DEBUG [backup.model.syncer] No syncs this cycle
```

We see that initially `_nextSnapshot()` returns `next` with value of `2021-01-16 20:10:00`. Once it calls `check()` after the the next snapshot time has passed it begins returning `now`, which is the current time. However, the `now` returned by the `_nextSnapshot()` function is always slightly ahead of `coordinator._time.now()`, so the coordinator [check()](https://github.com/sabeechen/hassio-google-drive-backup/blob/1b2681d50edade3553d0d18cd4ccbe5694535b62/hassio-google-drive-backup/backup/model/coordinator.py#L55) is always false:
```python
    def check(self) -> bool:
        if self._time.now() >= self.nextSyncAttempt():
            self.reset()
            return True
```

A couple of proposals to fix this:

1. Ensure the same instance/value of `time.now()` is used in both coordinator and `model.nextSyncAttempt()`
2. Does `model._nextSnapshot()` even need to return `now` in this scenario? To me, it makes sense for `model._nextSnapshot()` to continue to return the value of the next scheduled snapshot, even if the schedule has been missed. Since `coordinator.check()` is essentially checking if the scheduled time has been exceeded, changing the `_nextSnapshot()` when it's been exceeded complicates this check.
I've tried this out in my local add-on by replacing:
```python
        if next < now:
            return now
        else:
            return next
```
with
```python
        return next
```
This seems to have fixed the problem with the snapshot not running at the planned time, as seen in these logs with `snapshot_time_of_day: '21:11'`
```
01-16 15:10:59 DEBUG [backup.model.coordinator] Checking if current time 2021-01-16 21:10:59.205037+00:00 is greater than next sync time 2021-01-16 21:11:00+00:00.
01-16 15:10:59 DEBUG [backup.model.coordinator] coordinator check returning: False
01-16 15:10:59 DEBUG [backup.model.syncer] No syncs this cycle
01-16 15:10:59 DEBUG [backup.model.coordinator] Checking if current time 2021-01-16 21:10:59.707617+00:00 is greater than next sync time 2021-01-16 21:11:00+00:00.
01-16 15:10:59 DEBUG [backup.model.coordinator] coordinator check returning: False
01-16 15:10:59 DEBUG [backup.model.syncer] No syncs this cycle
01-16 15:11:00 DEBUG [backup.model.coordinator] Checking if current time 2021-01-16 21:11:00.209971+00:00 is greater than next sync time 2021-01-16 21:11:00+00:00.
01-16 15:11:00 DEBUG [backup.model.coordinator] coordinator check returning: true
01-16 15:11:00 DEBUG [backup.model.syncer] Sync requested by Coordinator
01-16 15:11:00 DEBUG [backup.model.syncer] Starting sync
```

Thoughts?

**Comment by sabeechen** [comment] 2021-01-19 18:58
I think you've nailed it.  Moreover, it also explains why the methods I was attempting to use to identify the problem never bore any fruit since:
- All of my tests advance the clock manually, so the small drift in time would never surface.
- All of my manual testing assumed the clock had 1 second resolution.
- Python's datetime resolution (micosecond) and accuracy is platform dependent, so it may be more or less likely on some platforms.
- Its more likely to happen if the machine is busy, since the thread running the addon would be more likely to get interrupted and cause a small delay between the two time checks.  The machines I was using to debug this are fast and otherwise unburdened.

This explains everything!  Finding this kind of of a big deal for me, since this is the last "real" functionality limiting bug the addon has.  `_nextsnapshot()` returns `now` because in an old version of the addon it couldn't be earlier than current time, but thats no longer the case.  I think the correct thing to do is just remove the if statement and always return `next` in `_nextSnapshot()` as you suggest.

Would you like to make a PR to get credit for the fix?  You'd be the first contributor to fix a bug for this project, but if not let me know as I'd like to make a release soon that resolves this.  Regardless I'll be mentioning you in the changelog and if you're ever in the Boulder, CO area let me know and I'll buy you a beer <3

**Comment by jhampson-dbre** [comment] 2021-01-19 20:12
Sure thing. Will put a PR in later today. Glad we found it!

**Comment by sabeechen** [comment] 2021-01-24 06:27
I've just pushed v0.103.1, which includes this fix.  I was unable to reproduce the delay in snapshots in any of my manual testing with the changes.  Regardless if anyone sees this continue to happen, please don't hesitate to reopen this bug and make me aware.

Thanks again @jhampson-dbre for figuring out the fix, this issue has been a thorn in my side for quite a while.  I credited you in the most recent [changelog](https://github.com/sabeechen/hassio-google-drive-backup/blob/master/hassio-google-drive-backup/CHANGELOG.md).

**Closed by sabeechen** 2021-01-24 06:27 UTC
Labels: bug, good first issue
