### ISSUE TITLE
Just upgraded to 98.1 and now I'm unable to open the addon

### ISSUE THREAD

**Issue by dheath73** [sabeechen/hassio-google-drive-backup#83] opened 2019-08-01 10:47 UTC
Hass.io 0.96.5

This is the message from both the 'Open Web UI' link and the ingress link on the left navigation.

401 Unauthorized
You are not authorized to access that resource

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 684, in _do_respond
    self.hooks.run('before_handler')
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 104, in run
    hook()
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "/usr/lib/python3.7/site-packages/cherrypy/lib/auth_basic.py", line 111, in basic_auth
    401, 'You are not authorized to access that resource')
cherrypy._cperror.HTTPError: (401, 'You are not authorized to access that resource')

Just to say I wasn't prompted as mentioned in the CHANGELOG.md 
"the UI will present a dialog asking if you'd still like to serve the Web UI over another port or just use ingress in the future."

Any suggestions please?

**Comment by soppilif** [comment] 2019-08-01 11:07
same here

**Comment by dheath73** [comment] 2019-08-01 11:11
I just uninstalled after taking a copy of the config file then reinstalled pasting the config back in and then reauthorise and it OK again now!

**Comment by VivantSenior** [comment] 2019-08-01 11:11
I have the same issue:

`Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 684, in _do_respond
    self.hooks.run('before_handler')
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 104, in run
    hook()
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 63, in __call__
    return self.callback(**self.kwargs)
  File "/usr/lib/python3.7/site-packages/cherrypy/lib/auth_basic.py", line 111, in basic_auth
    401, 'You are not authorized to access that resource')
cherrypy._cperror.HTTPError: (401, 'You are not authorized to access that resource')`

**Comment by sabeechen** [comment] 2019-08-01 15:52
Could I have one of you seeing the problem post your add-on configuration?  I'll try to reproduce this on my machine.

**Comment by VivantSenior** [comment] 2019-08-01 15:59
I think the issue is that the port I have in "Network" section is not being forwarded on the router (therefore no access from outside of the network).

**Comment by sabeechen** [comment] 2019-08-01 16:46
Could you describe to me how you made the error come up and how you resolved it?  I've got at least a couple users seeing this and I'd like to be able to give them guidance.

**Comment by Tuncay-Ayhan** [comment] 2019-08-01 20:04
> I just uninstalled after taking a copy of the config file then reinstalled pasting the config back in and then reauthorise and it OK again now!
> 
> Ingress is working as expected which is great, thank you, and so if everything else.

This did not work for me though. Got the same problem after updating the addon while using 0.98.5

**Comment by Sjeff** [comment] 2019-08-02 05:30
@sabeechen this is my addon config:
```
{
  "max_snapshots_in_hassio": 10,
  "max_snapshots_in_google_drive": 24,
  "days_between_snapshots": 1,
  "use_ssl": false,
  "verbose": true,
  "snapshot_stale_minutes": 250,
  "require_login": true,
  "snapshot_time_of_day": "02:15",
  "generational_days": 7,
  "generational_weeks": 4,
  "generational_day_of_week": "fri",
  "generational_months": 12,
  "generational_day_of_month": 1,
  "send_error_reports": false
}
```
Network port is disabeld.

The backup of last night has been successful.

**Comment by kroty1** [comment] 2019-08-02 08:18
```
{
  "max_snapshots_in_hassio": 7,
  "max_snapshots_in_google_drive": 30,
  "days_between_snapshots": 1,
  "use_ssl": true,
  "snapshot_time_of_day": "00:00",
  "snapshot_name": "{type} Snapshot Hassio {version_ha} - {day}.{month}.{year}",
  "send_error_reports": true,
  "require_login": true,
  "generational_months": 12,
  "generational_years": 5,
  "google_drive_timeout_seconds": 300
}
```
I have the same issue and this is my add-on config.

**Comment by VivantSenior** [comment] 2019-08-02 14:12
```
{
  "max_snapshots_in_hassio": 10,
  "max_snapshots_in_google_drive": 15,
  "days_between_snapshots": 1,
  "use_ssl": true,
  "generational_day_of_week": "mon",
  "snapshot_time_of_day": "03:00",
  "snapshot_password": "!secret google_backup_pass",
  "snapshot_name": "{year}{month}{day}_{hr24}.{min}.{sec}_{version_ha}_{version_super}_{type}_snapshot",
  "send_error_reports": false,
  "require_login": true,
  "generational_days": 1,
  "generational_weeks": 4,
  "generational_months": 1,
  "generational_years": 1,
  "alternate_dns_servers": "1.1.1.1,1.0.0.1,8.8.8.8,8.8.4.4"
}
```

**Comment by Sjeff** [comment] 2019-08-02 14:43
Just did a  fresh install on my dev setup the error shows immediately.
- Raspberry Pi 3b
- Hass.io 0.97.0b1

config:
```
{
  "max_snapshots_in_hassio": 2,
  "max_snapshots_in_google_drive": 4,
  "days_between_snapshots": 1,
  "use_ssl": false,
  "verbose": true,
  "require_login": true,
  "snapshot_time_of_day": "03:15",
  "snapshot_name": "{type} Snapshot Hassio DEV {version_ha} - {day}.{month}.{year}",
  "send_error_reports": false
}
```

**Comment by sabeechen** [comment] 2019-08-02 16:53
I haven't been able to get this to happen in any of my test setups, but I suspect this has something to do with setting `require_login` and `use_ssl`

Unless you intend to have the web-UI accessible outside of ingress, you should be able to add the following settings as a workaround:
```
"require_login": false,
"use_ssl": false,
"expose_extra_server": false,
```
Since ingress protects the web interface using the ssl and user/pass settings configured for Home Assistant, all this should do is prevent you form having to enter your username/password a second time for the web-ui.

**Comment by kroty1** [comment] 2019-08-02 17:04
That worked! Thanks for developing this amazing add-on.

**Comment by Sjeff** [comment] 2019-08-02 17:09
Thanks @sabeechen working perfect again.

**Comment by VivantSenior** [comment] 2019-08-03 10:53
@sabeechen the "use_ssl" can be set to true. If the settings are set too:
```
  "use_ssl": true,
  "require_login": false,
  "expose_extra_server": false
```
access through Ingress will work.

Thanks for the awesome addon!

BTW, after uninstalling the addon (re @dheath73 [trick](https://github.com/sabeechen/hassio-google-drive-backup/issues/83#issuecomment-517238461)) and installing the addon again I had to set ClientID and API once again and weird part is that addon have removed all files from backup folder on Google Drive (backups on RPi remained untouched). @sabeechen, is it a bug?

**Comment by sabeechen** [comment] 2019-08-04 01:47
If you used a newly generated clientid and secret, then it counts as a new "app" from Google's perspective and it can't see any of the old snapshots or the backup folder in Google Drive, so it will  create a new folder and start uploading there fresh.  Its possible that your snapshots are still there, just in an older folder the addon doesn't have permission to see anymore.   You can try searching for "Hass.io" in Google Drive to see if that is the case.  If not, then its certainly a bug, the addon should never delete more than one snapshot at a time without your intervention.

**Comment by sabeechen** [comment] 2019-08-04 18:42
I've made a fix for this issue in 0.98.2, accessing the page though ingress no longer requires user/pass login regardless of the setting (since ingress should already be considered "authenticated").  If anybody stills sees the problem after upgrading to v0.98.2, please reopen the issue and give me a shout.

**Closed by sabeechen** 2019-08-04 18:42 UTC
Labels: bug

**Comment by VivantSenior** [comment] 2019-08-05 06:22
@sabeechen yeah you are right. The folder is still on my google drive (now I have two folders with the name "Hass.io Snapshots"). What will happen if I will just copy and paste backups from old folder to the new one? Will the addon start to see old backups and manage them?

**Comment by sabeechen** [comment] 2019-08-05 17:09
Unfortunately because of how the permissions in Drive work, it will never be able to see the older folder/snapshots.  Its one of the downsides of using your own client id/secret.  I believe you can work around it if you reuse the same id/secret pair (I haven't tested it specifically), but if you use a different one then Google Drive treats them as two completely separate apps who can't see eachother's files.

**Comment by sabeechen** [comment] 2019-08-05 17:10
I might be able to implement some kind of "import" in the future when I implement choosing your own folder, but its one of those things thats more complicated than it seems because of how Drive works.

**Comment by M0VEJAM** [comment] 2020-09-09 20:50
Hi guys, I just had the same problem.
I deleted the access to google manually and tried again, still no success.
What worked for me was actually simple.
I just refreshed the page (clicked the URL & enter) and then was redirected back to Home Assistant and everything works fine now.
If you need any additional information just let me know :-)
