### ISSUE TITLE
"undefined" showing in addons list

### ISSUE THREAD

**Issue by AlecRust** [sabeechen/hassio-google-drive-backup#700] opened 2022-08-21 12:57 UTC
The list of addons within the "Partial Backups" checkbox in the main settings modal, shows `undefined` under each addon: 

![Screenshot 2022-08-21 at 13 55 59](https://user-images.githubusercontent.com/247634/185791962-e6d50790-665f-4b54-945a-e3ab031cb2e8.png)

**Comment by sabeechen** [comment] 2022-08-22 23:16
Looks like this was caused by a change in the supervisor's API, not sure how long its been busted.  This also prevented the logo for addons from showing up when you view a backup's details.  I've fixed in in v0.108.4, which I just released earlier today.

**Closed by sabeechen** 2022-08-22 23:16 UTC
