### ISSUE TITLE
'401: Unauthorized' when opening WebUI

### ISSUE THREAD

**Issue by radicalmachine** [sabeechen/hassio-google-drive-backup#436] opened 2021-07-26 16:38 UTC
This seems not the same issue as the the '401: Unauthorised when trying to authenticate' issue (although happy to be corrected on that), as this occurs when attempting to open the WebUI. I am using Firefox and HA running in Docker on a Pi4. Works fine in Edge.

Currently have to use Edge in order to look at the WebUI or make any changes, which isn't ideal.

**Comment by sabeechen** [comment] 2021-07-26 17:31
Could I have you do two things to help me dig into this:
* Open the web-ui in both edge and firefox.  After you get the 401 error in firefox,  use edge to go to "Actions" > "Report a bug" in the addon web-ui and copy the details it gives you here.  This gets me details abotu your configuration that avoids me having to ask you a million questions.
* If you are running the UI through a reverse proxy (eg NGinx, Traefik, etc) could you see if any errors show up in logs for your proxy?  If this doesn't make sense you probably don't use a reverse proxy and can ignore this.

**Comment by radicalmachine** [comment] 2021-07-26 18:31
###### Description:
```
Sure thing, hope the below is useful - let me know if I can provide any more logs or information. I don't run a reverse proxy.
```

 Addon version: `0.104.3`
 Home Assistant Version: `2021.7.4`
 Supervisor Version: `2021.06.8`
 Supervisor Channel: `stable`
 Hassos Version: `None`
 Docker Version: `20.10.7`
 Architecture: `armv7`
 Machine: `raspberrypi4`
 Date: `2021-07-26T18:22:58.177469+00:00`
 Timezone: `Europe/London`
 Failure Time: `2021-07-26T16:49:29.989527+00:00`
 Last Good Sync: `2021-07-26T17:53:36.042874+00:00`
 ###### Exception:
 ```
 No error could be identified automatically.
 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 1,
        "retained": 0,
        "deletable": 1,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": "2021-07-26T16:51:48Z",
        "max": 10,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "77.6 MB",
        "ignored_size": "0.0 B",
        "free_space": "104.3 GB"
    },
    "GoogleDrive": {
        "snapshots": 1,
        "retained": 0,
        "deletable": 1,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": "2021-07-26T16:51:48Z",
        "max": 9,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "77.6 MB",
        "ignored_size": "0.0 B",
        "free_space": "14.9 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_SNAPSHOTS_IN_HASSIO": 10,
    "Setting.MAX_SNAPSHOTS_IN_GOOGLE_DRIVE": 9,
    "Setting.DAYS_BETWEEN_SNAPSHOTS": 0.0,
    "Setting.SNAPSHOT_TIME_OF_DAY": "20:00",
    "Setting.SNAPSHOT_PASSWORD": "REDACTED"
}
 ```
 ###### Addon Logs:
 ```
 07-26 17:52:53 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdsMebxETPezE03P5icXjfEhbD2-NPEQmJjF9k9T1z8qMp1V-QnGccZ0oczX4xaVQJ5oG7D7iSMZssjZ16QmWFnfPudgSA
07-26 17:52:58 DEBUG [backup.drive.drivesource] Uploading Weekly_Backup_2021-07-26 17:51:48.317117+01:00 26.08%
07-26 17:52:58 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
07-26 17:52:58 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdsMebxETPezE03P5icXjfEhbD2-NPEQmJjF9k9T1z8qMp1V-QnGccZ0oczX4xaVQJ5oG7D7iSMZssjZ16QmWFnfPudgSA
07-26 17:53:10 DEBUG [backup.drive.drivesource] Uploading Weekly_Backup_2021-07-26 17:51:48.317117+01:00 38.96%
07-26 17:53:10 DEBUG [backup.drive.driverequests] Sending 8650752 bytes to Google Drive
07-26 17:53:10 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdsMebxETPezE03P5icXjfEhbD2-NPEQmJjF9k9T1z8qMp1V-QnGccZ0oczX4xaVQJ5oG7D7iSMZssjZ16QmWFnfPudgSA
07-26 17:53:14 DEBUG [backup.drive.drivesource] Uploading Weekly_Backup_2021-07-26 17:51:48.317117+01:00 49.59%
07-26 17:53:14 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
07-26 17:53:14 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdsMebxETPezE03P5icXjfEhbD2-NPEQmJjF9k9T1z8qMp1V-QnGccZ0oczX4xaVQJ5oG7D7iSMZssjZ16QmWFnfPudgSA
07-26 17:53:19 DEBUG [backup.drive.drivesource] Uploading Weekly_Backup_2021-07-26 17:51:48.317117+01:00 62.47%
07-26 17:53:19 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
07-26 17:53:19 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdsMebxETPezE03P5icXjfEhbD2-NPEQmJjF9k9T1z8qMp1V-QnGccZ0oczX4xaVQJ5oG7D7iSMZssjZ16QmWFnfPudgSA
07-26 17:53:24 DEBUG [backup.drive.drivesource] Uploading Weekly_Backup_2021-07-26 17:51:48.317117+01:00 75.35%
07-26 17:53:24 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
07-26 17:53:24 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdsMebxETPezE03P5icXjfEhbD2-NPEQmJjF9k9T1z8qMp1V-QnGccZ0oczX4xaVQJ5oG7D7iSMZssjZ16QmWFnfPudgSA
07-26 17:53:29 DEBUG [backup.drive.drivesource] Uploading Weekly_Backup_2021-07-26 17:51:48.317117+01:00 88.23%
07-26 17:53:29 DEBUG [backup.drive.driverequests] Sending 10485760 bytes to Google Drive
07-26 17:53:29 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ADPycdsMebxETPezE03P5icXjfEhbD2-NPEQmJjF9k9T1z8qMp1V-QnGccZ0oczX4xaVQJ5oG7D7iSMZssjZ16QmWFnfPudgSA
07-26 17:53:35 DEBUG [backup.drive.drivesource] Uploading Weekly_Backup_2021-07-26 17:51:48.317117+01:00 100.00%
07-26 17:53:35 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1g7MRwZhyDhloTllmO7RnwbAf0kD-sTp9/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
07-26 17:53:52 INFO [backup.drive.drivesource] Deleting 'Full Snapshot 2021-07-26 17:24:56' From Google Drive
07-26 17:53:52 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1v8cqGrP4TV7S-oSYih0yBa7AxLQkFRVQ/?supportsAllDrives=true
07-26 18:53:36 DEBUG [backup.model.syncer] Sync requested by Coordinator
07-26 18:53:36 INFO [backup.model.coordinator] Syncing Snapshots
07-26 18:53:36 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
07-26 18:53:36 DEBUG [backup.drive.driverequests] Requesting refreshed Google Drive credentials
07-26 18:53:36 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1eTfYoX6o2VM0QMrzNrEw0mZGXjjF4pQ5/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId&supportsAllDrives=true
07-26 18:53:36 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/about?fields=storageQuota
07-26 18:53:36 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271eTfYoX6o2VM0QMrzNrEw0mZGXjjF4pQ5%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%2CdriveId%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
 ```
 ###### Supervisor Logs:
 ```
 [32m21-07-26 18:05:45 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[32m21-07-26 18:05:45 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m21-07-26 18:05:45 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m21-07-26 18:05:45 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m21-07-26 18:05:45 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m21-07-26 18:05:45 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m21-07-26 18:05:45 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m21-07-26 18:05:45 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m21-07-26 18:06:17 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-07-26 18:36:24 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-07-26 18:53:36 INFO (MainThread) [supervisor.api.middleware.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m21-07-26 19:05:45 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING[0m
[32m21-07-26 19:05:45 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON[0m
[32m21-07-26 19:05:45 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE[0m
[32m21-07-26 19:05:45 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM[0m
[32m21-07-26 19:05:45 INFO (MainThread) [supervisor.resolution.check] System checks complete[0m
[32m21-07-26 19:05:45 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING[0m
[32m21-07-26 19:05:45 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete[0m
[32m21-07-26 19:05:45 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING[0m
[32m21-07-26 19:05:45 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete[0m
[32m21-07-26 19:06:30 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m21-07-26 19:06:30 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json[0m
[32m21-07-26 19:13:10 INFO (MainThread) [supervisor.host.info] Updating local host information[0m
[32m21-07-26 19:13:10 INFO (MainThread) [supervisor.host.services] Updating service information[0m
[32m21-07-26 19:13:10 INFO (MainThread) [supervisor.host.network] Updating local network information[0m
[32m21-07-26 19:13:12 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information[0m
[32m21-07-26 19:13:12 INFO (MainThread) [supervisor.host] Host information reload completed[0m
[33m21-07-26 19:22:07 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None[0m
[32m21-07-26 19:22:58 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

**Comment by sabeechen** [comment] 2021-07-26 22:51
It looks like the relevant problem is in the supervisor logs:
```
[33m21-07-26 19:22:07 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None
```

This means the supervisor for some reason doesn't think you have authorzation to see the addon.  Is suspect that you're also unable to see the web-ui of any addon with firefox, not just this one.

I was able to find [this issue](https://github.com/home-assistant/supervisor/issues/3021) open with the supervisor where people appear to be the exact same problem as you with firefox and a few other browsers.   Its currently unresolved, but reading through it seems like ti might have something to do with recent changes in firefox's tracking protection. This isn't very surprising to me, as the way the supervisor manages the cookies to authenticate the web-ui for addons is pretty complicated and looks a lot like sketchy user tracking.

Unfortunately that also means there isn't much I can do about it, since its an issue between Firefox and the supervisor.  
As a workaround, you could:
* Enable the "Expose an additional webserver" option in the addon web-ui and reach the UI through http://homeassistant.local:1627 to bypass the internal proxy the supervisor makes for addons like this one.
* Disable tracking prtection prtoection in firefox, that seems to have worked for many people in the [open bug](https://github.com/home-assistant/supervisor/issues/3021).

Though honestly it might just be better to use edge until the issue is sorted out.

I'm going to close this, but if you think I misunderstood something or can help in some other way, feel free to comment or reopen it.

**Closed by sabeechen** 2021-07-26 22:51 UTC
Labels: bug

**Comment by sabeechen** [comment] 2021-07-26 23:02
Its worth noting that I also use Firefox in its "strict" tracking protection mode and see this problem.  If I add my HA server's address to the cookie exception list in Firefox's settings, the problem goes away for me.  I have this turned on all the time anyway to maintain my logged in session.  So thats another workaround.

**Comment by radicalmachine** [comment] 2021-07-28 17:47
Hi Stephen,

Thanks for the great context, information and workaround suggestions. I added a cookie exception as you directed which is working well. Much appreciated, and great add-on!

All the best
