### ISSUE TITLE
Unable to Talk to the Home Assistant Supervisor

### ISSUE THREAD

**Issue by RaspTLC** [sabeechen/hassio-google-drive-backup#565] opened 2022-03-02 15:20 UTC
###### Description:
```
If you have anything else that could help explain what happened, click "Markdown" above and write it here.
```

 Addon version: `0.105.2`
 Home Assistant Version: `Uninitialized`
 Supervisor Version: `Uninitialized`
 Supervisor Channel: `{supervisor_channel}`
 Hassos Version: `{hassos_version}`
 Docker Version: `{docker_version}`
 Architecture: `Uninitialized`
 Machine: `{machine}`
 Date: `2022-03-02T15:20:01.662419+00:00`
 Timezone: `Uninitialized`
 Failure Time: `2022-03-02T15:19:57.458366+00:00`
 Last Good Sync: `2022-03-02T15:19:57.429878+00:00`
 ###### Exception:
 ```
 
  addon/backup/ha/harequests.py:31 (wrap_and_call)
  addon/backup/ha/harequests.py:242 (_getHassioData)
  addon/backup/ha/harequests.py:202 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://supervisor/addons/self/info')
Whose handling caused:
  addon/backup/model/coordinator.py:176 (_sync)
  addon/backup/model/model.py:167 (sync)
  addon/backup/model/model.py:265 (_syncBackups)
  addon/backup/ha/hasource.py:242 (get)
  addon/backup/ha/hasource.py:356 (init)
  addon/backup/ha/hasource.py:399 (_refreshInfo)
  addon/backup/ha/hasource.py:364 (_refreshInfo)
  addon/backup/ha/harequests.py:31 (wrap_and_call)
  addon/backup/ha/harequests.py:136 (selfInfo)
  addon/backup/ha/harequests.py:31 (wrap_and_call)
  addon/backup/ha/harequests.py:140 (getAddonInfo)
  addon/backup/ha/harequests.py:38 (wrap_and_call)
backup.exceptions.exceptions.SupervisorPermissionError

 ```
 Backups:
 ```
 {
    "HomeAssistant": {
        "backups": 0,
        "retained": 0,
        "deletable": 0,
        "name": "HomeAssistant",
        "title": "Home Assistant",
        "latest": null,
        "max": 2,
        "enabled": true,
        "icon": "home-assistant",
        "ignored": 0,
        "size": "0.0 B",
        "ignored_size": "0.0 B",
        "free_space": "6.1 GB"
    },
    "GoogleDrive": {
        "backups": 0,
        "retained": 0,
        "deletable": 0,
        "name": "GoogleDrive",
        "title": "Google Drive",
        "latest": null,
        "max": 10,
        "enabled": true,
        "icon": "google-drive",
        "ignored": 0,
        "size": "0.0 B",
        "ignored_size": "0.0 B"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.MAX_BACKUPS_IN_HA": 2,
    "Setting.MAX_BACKUPS_IN_GOOGLE_DRIVE": 10,
    "Setting.DAYS_BETWEEN_BACKUPS": 1.0
}
 ```
 ###### Addon Logs:
 ```
 03-02 15:48:57 DEBUG [backup.worker.watcher] Backup directory modified event
03-02 15:48:57 DEBUG [backup.worker.watcher] Backup directory changed
03-02 15:48:57 DEBUG [backup.worker.watcher] Backup directory changed
03-02 15:48:57 DEBUG [backup.worker.watcher] Backup directory modified event
03-02 15:49:02 INFO [backup.worker.watcher] Backup directory changed
03-02 15:49:02 DEBUG [backup.model.syncer] Sync requested by Backup Directory Watcher
03-02 15:49:02 INFO [backup.model.coordinator] Syncing Backups
03-02 15:49:02 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/self/info
03-02 15:49:02 DEBUG [backup.ha.hasource] Failed to connect to supervisor
03-02 15:49:03 DEBUG [backup.ha.hasource] 
  addon/backup/ha/harequests.py:31 (wrap_and_call)
  addon/backup/ha/harequests.py:242 (_getHassioData)
  addon/backup/ha/harequests.py:202 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://supervisor/addons/self/info')
Whose handling caused:
  addon/backup/ha/hasource.py:364 (_refreshInfo)
  addon/backup/ha/harequests.py:31 (wrap_and_call)
  addon/backup/ha/harequests.py:136 (selfInfo)
  addon/backup/ha/harequests.py:31 (wrap_and_call)
  addon/backup/ha/harequests.py:140 (getAddonInfo)
  addon/backup/ha/harequests.py:38 (wrap_and_call)
backup.exceptions.exceptions.SupervisorPermissionError

03-02 15:49:03 ERROR [backup.model.coordinator] The supervisor is rejecting requests from the addon.  Please visit the web-UI for guidance
03-02 15:49:03 INFO [backup.model.coordinator] I'll try again in an hour
03-02 15:51:26 ERROR [backup.ha.haupdater] Trouble updating Home Assistant sensors.
03-02 15:56:36 ERROR [backup.ha.haupdater] Trouble updating Home Assistant sensors.
03-02 16:01:46 ERROR [backup.ha.haupdater] Trouble updating Home Assistant sensors.
03-02 16:06:56 ERROR [backup.ha.haupdater] Trouble updating Home Assistant sensors.
03-02 16:12:06 ERROR [backup.ha.haupdater] Trouble updating Home Assistant sensors.
03-02 16:17:17 ERROR [backup.ha.haupdater] Trouble updating Home Assistant sensors.
03-02 16:18:59 INFO [backup.model.coordinator] Syncing Backups
03-02 16:18:59 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/self/info
03-02 16:18:59 DEBUG [backup.ha.hasource] Failed to connect to supervisor
03-02 16:18:59 DEBUG [backup.ha.hasource] 
  addon/backup/ha/harequests.py:31 (wrap_and_call)
  addon/backup/ha/harequests.py:242 (_getHassioData)
  addon/backup/ha/harequests.py:202 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://supervisor/addons/self/info')
Whose handling caused:
  addon/backup/ha/hasource.py:364 (_refreshInfo)
  addon/backup/ha/harequests.py:31 (wrap_and_call)
  addon/backup/ha/harequests.py:136 (selfInfo)
  addon/backup/ha/harequests.py:31 (wrap_and_call)
  addon/backup/ha/harequests.py:140 (getAddonInfo)
  addon/backup/ha/harequests.py:38 (wrap_and_call)
backup.exceptions.exceptions.SupervisorPermissionError

03-02 16:18:59 ERROR [backup.model.coordinator] The supervisor is rejecting requests from the addon.  Please visit the web-UI for guidance
03-02 16:18:59 INFO [backup.model.coordinator] I'll try again in an hour
03-02 16:19:57 INFO [backup.model.coordinator] Syncing Backups
03-02 16:19:57 DEBUG [backup.ha.harequests] Making Hassio request: http://supervisor/addons/self/info
03-02 16:19:57 DEBUG [backup.ha.hasource] Failed to connect to supervisor
03-02 16:19:57 DEBUG [backup.ha.hasource] 
  addon/backup/ha/harequests.py:31 (wrap_and_call)
  addon/backup/ha/harequests.py:242 (_getHassioData)
  addon/backup/ha/harequests.py:202 (_validateHassioReply)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://supervisor/addons/self/info')
Whose handling caused:
  addon/backup/ha/hasource.py:364 (_refreshInfo)
  addon/backup/ha/harequests.py:31 (wrap_and_call)
  addon/backup/ha/harequests.py:136 (selfInfo)
  addon/backup/ha/harequests.py:31 (wrap_and_call)
  addon/backup/ha/harequests.py:140 (getAddonInfo)
  addon/backup/ha/harequests.py:38 (wrap_and_call)
backup.exceptions.exceptions.SupervisorPermissionError

03-02 16:19:57 ERROR [backup.model.coordinator] The supervisor is rejecting requests from the addon.  Please visit the web-UI for guidance
03-02 16:19:57 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 
  addon/backup/ha/harequests.py:31 (wrap_and_call)
  addon/backup/ha/harequests.py:190 (getSuperLogs)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://supervisor/supervisor/logs')
Whose handling caused:
  addon/backup/debugworker.py:162 (buildBugReportData)
  addon/backup/ha/harequests.py:38 (wrap_and_call)
backup.exceptions.exceptions.SupervisorPermissionError

 ```
 ###### Home Assistant Core Logs:
 ```
 
  addon/backup/ha/harequests.py:31 (wrap_and_call)
  addon/backup/ha/harequests.py:197 (getCoreLogs)
  /site-packages/aiohttp/client_reqrep.py:1000 (raise_for_status)
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://supervisor/core/logs')
Whose handling caused:
  addon/backup/debugworker.py:166 (buildBugReportData)
  addon/backup/ha/harequests.py:38 (wrap_and_call)
backup.exceptions.exceptions.SupervisorPermissionError

 ```

**Comment by sabeechen** [comment] 2022-03-20 19:57
Sorry this took me a while to get back to you on, I've been out of touch for a while.

I've seen this error from users before, but have been unable to determine what causes it.  Sometimes the Home Assistant Supervisor "forgets" the permissions the addon has and rejects any requests it makes, which causes the addon to stop working completely.  The fix has been to restart the machine running Home Assistant (eg turn it off, turn it on).  If that doesn't work or you have any other information that might indicate what the cause is, please feel free to reopen this issue.

**Closed by sabeechen** 2022-03-20 19:57 UTC
