### ISSUE TITLE
Sync issues

### ISSUE THREAD

**Issue by WonderMoose** [sabeechen/hassio-google-drive-backup#290] opened 2020-10-25 14:05 UTC
###### Description:
```
I am having sync issues. To be honest, I have  had it for a month or more, but did not have time to look into it. It seems that it is able to sync to Google Drive sometimes, but most updates fails due to a sync issue. Log attached. 
```

 Addon version: `0.101.3`
 Home Assistant Version: `0.116.4`
 Supervisor Version: `249`
 Supervisor Channel: `stable`
 Hassos Version: `4.15`
 Docker Version: `19.03.11`
 Architecture: `armv7`
 Machine: `raspberrypi3`
 Date: `2020-10-25T14:01:28.643498+00:00`
 Timezone: `Europe/Copenhagen`
 Failure Time: `2020-10-25T14:01:14.810936+00:00`
 Last Good Sync: `2020-10-25T14:01:14.033641+00:00`
 ###### Exception:
 ```
 
  addon/backup/util/asynchttpgetter.py:133 (read)
  /site-packages/aiohttp/streams.py:416 (readexactly)
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
Whose handling caused:
  addon/backup/model/coordinator.py:148 (_sync)
  addon/backup/model/model.py:162 (sync)
  addon/backup/drive/drivesource.py:150 (save)
  addon/backup/drive/driverequests.py:252 (create)
  addon/backup/util/asynchttpgetter.py:140 (read)
backup.exceptions.exceptions.SupervisorUnexpectedError

 ```
 Snapshots:
 ```
 {
    "HomeAssistant": {
        "snapshots": 3,
        "retained": 0,
        "deletable": 3,
        "name": "HomeAssistant",
        "latest": "2020-10-25T05:00:21Z",
        "size": "9.1 GB"
    },
    "GoogleDrive": {
        "snapshots": 1,
        "retained": 0,
        "deletable": 1,
        "name": "GoogleDrive",
        "latest": "2020-10-13T04:11:11Z",
        "size": "1.6 GB"
    }
}
 ```
 ###### Config:
 ```
 {
    "Setting.SEND_ERROR_REPORTS": true
}
 ```
 ###### Addon Logs:
 ```
 10-25 15:00:01 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-25 15:00:01 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271W3RF0dtNLI_3iyhquxu_DzI4HoLgxpWb%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-25 15:00:01 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2020-10-25 06:00:20' to Google Drive
10-25 15:00:01 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
10-25 15:00:01 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-UxE3Xy0P8LC8kZjzAxrSKBvVht1ftELJ9o2YG7k002hJAwbG_I06t4Wx23ssWvpsKCWLdlsfmkb0AOldJb3AHoml2DcWw
10-25 15:00:01 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 4092835840
10-25 15:00:01 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
10-25 15:00:01 INFO [backup.model.coordinator] I'll try again in an hour
10-25 15:00:02 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/addons/self/options
10-25 15:00:03 DEBUG [backup.model.syncer] Sync requested by UI Server
10-25 15:00:03 INFO [backup.model.coordinator] Syncing Snapshots
10-25 15:00:03 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-25 15:00:03 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271W3RF0dtNLI_3iyhquxu_DzI4HoLgxpWb%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-25 15:00:03 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2020-10-25 06:00:20' to Google Drive
10-25 15:00:03 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
10-25 15:00:03 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-UxE3Xy0P8LC8kZjzAxrSKBvVht1ftELJ9o2YG7k002hJAwbG_I06t4Wx23ssWvpsKCWLdlsfmkb0AOldJb3AHoml2DcWw
10-25 15:00:03 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 4092835840
10-25 15:00:03 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
10-25 15:00:03 INFO [backup.model.coordinator] I'll try again in an hour
10-25 15:00:05 INFO [backup.debugworker] Sending error report (see settings to disable)
10-25 15:01:14 INFO [backup.model.coordinator] Syncing Snapshots
10-25 15:01:14 DEBUG [backup.ha.harequests] Making Hassio request: http://hassio/snapshots
10-25 15:01:14 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/1W3RF0dtNLI_3iyhquxu_DzI4HoLgxpWb/?fields=id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents&supportsAllDrives=true
10-25 15:01:14 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/drive/v3/files/?q=%271W3RF0dtNLI_3iyhquxu_DzI4HoLgxpWb%27+in+parents&fields=nextPageToken%2Cfiles%28id%2Cname%2CappProperties%2Csize%2Ctrashed%2CmimeType%2CmodifiedTime%2Ccapabilities%2Cparents%29&pageSize=100&supportsAllDrives=true&includeItemsFromAllDrives=true&corpora=allDrives
10-25 15:01:14 INFO [backup.drive.drivesource] Uploading 'Full Snapshot 2020-10-25 06:00:20' to Google Drive
10-25 15:01:14 DEBUG [backup.drive.driverequests] Attempting to resume a previosuly failed upload where we left off
10-25 15:01:14 DEBUG [backup.drive.driverequests] Making Google Drive request: https://www.googleapis.com/upload/drive/v3/files/?uploadType=resumable&supportsAllDrives=true&upload_id=ABg5-UxE3Xy0P8LC8kZjzAxrSKBvVht1ftELJ9o2YG7k002hJAwbG_I06t4Wx23ssWvpsKCWLdlsfmkb0AOldJb3AHoml2DcWw
10-25 15:01:14 DEBUG [backup.drive.driverequests] Resuming upload at byte 0 of 4092835840
10-25 15:01:14 ERROR [backup.model.coordinator] The supervisor gave an unexpected response
10-25 15:01:14 INFO [backup.model.coordinator] I'll try again in an hour
 ```
 ###### Supervisor Logs:
 ```
 [32m20-10-25 13:58:05 INFO (SyncWorker_5) [supervisor.docker.interface] Removeing image sabeechen/hassio-google-drive-backup-armv7 with latest and 3.12[0m
[32m20-10-25 13:58:05 INFO (MainThread) [supervisor.addons.addon] Removing add-on data folder /data/addons/data/cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 13:58:05 INFO (MainThread) [supervisor.addons] Add-on 'cebe7a76_hassio_google_drive_backup' successfully removed[0m
[32m20-10-25 13:58:36 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 13:58:36 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image sabeechen/hassio-google-drive-backup-armv7 with tag 0.101.3.[0m
[32m20-10-25 13:58:39 INFO (MainThread) [supervisor.addons] Add-on 'cebe7a76_hassio_google_drive_backup' successfully installed[0m
[32m20-10-25 13:58:49 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on sabeechen/hassio-google-drive-backup-armv7 with version 3.12[0m
[31m20-10-25 13:58:54 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connection refused][0m
[32m20-10-25 13:58:55 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token[0m
[32m20-10-25 13:58:55 INFO (MainThread) [supervisor.api.security] /core/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 13:58:55 INFO (MainThread) [supervisor.api.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 13:58:55 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 13:58:55 INFO (MainThread) [supervisor.api.security] /snapshots/40cbc2bf/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 13:58:55 INFO (MainThread) [supervisor.api.security] /snapshots/60a23d54/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 13:58:55 INFO (MainThread) [supervisor.api.security] /snapshots/be6327e3/info access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 13:59:51 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 13:59:58 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 13:59:59 INFO (MainThread) [supervisor.api.security] /snapshots/60a23d54/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 13:59:59 INFO (MainThread) [supervisor.api.snapshots] Downloading snapshot 60a23d54[0m
[32m20-10-25 14:00:01 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 14:00:01 INFO (MainThread) [supervisor.api.security] /snapshots/60a23d54/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 14:00:01 INFO (MainThread) [supervisor.api.snapshots] Downloading snapshot 60a23d54[0m
[32m20-10-25 14:00:03 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 14:00:03 INFO (MainThread) [supervisor.api.security] /snapshots/60a23d54/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 14:00:03 INFO (MainThread) [supervisor.api.snapshots] Downloading snapshot 60a23d54[0m
[32m20-10-25 14:01:14 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 14:01:14 INFO (MainThread) [supervisor.api.security] /snapshots/60a23d54/download access from cebe7a76_hassio_google_drive_backup[0m
[32m20-10-25 14:01:14 INFO (MainThread) [supervisor.api.snapshots] Downloading snapshot 60a23d54[0m
[32m20-10-25 14:01:28 INFO (MainThread) [supervisor.api.security] /supervisor/logs access from cebe7a76_hassio_google_drive_backup[0m

 ```
 ###### Home Assistant Core Logs:
 ```
 2020-10-25 15:01:32 DEBUG (MainThread) [websockets.protocol] client - event = data_received(<6 bytes>)
2020-10-25 15:01:32 DEBUG (MainThread) [websockets.protocol] client < Frame(fin=True, opcode=10, data=b"\x9a\x01\xd1'", rsv1=False, rsv2=False, rsv3=False)
2020-10-25 15:01:32 DEBUG (MainThread) [websockets.protocol] client - received solicited pong: 9a01d127
2020-10-25 15:01:33 DEBUG (Recorder) [homeassistant.components.recorder] Sending keepalive
2020-10-25 15:01:33 DEBUG (MainThread) [homeassistant.components.hue.light] Finished fetching group data in 0.070 seconds
2020-10-25 15:01:33 DEBUG (MainThread) [homeassistant.components.hue.sensor_base] Finished fetching sensor data in 0.079 seconds
2020-10-25 15:01:33 DEBUG (SyncWorker_8) [homeassistant.components.nmap_tracker.device_tracker] Scanning...
2020-10-25 15:01:34 DEBUG (MainThread) [websockets.protocol] client > Frame(fin=True, opcode=9, data=b'\xef\xbd7{', rsv1=False, rsv2=False, rsv3=False)
2020-10-25 15:01:34 DEBUG (MainThread) [websockets.protocol] client - event = data_received(<6 bytes>)
2020-10-25 15:01:34 DEBUG (MainThread) [websockets.protocol] client < Frame(fin=True, opcode=10, data=b'\xef\xbd7{', rsv1=False, rsv2=False, rsv3=False)
2020-10-25 15:01:34 DEBUG (MainThread) [websockets.protocol] client - received solicited pong: efbd377b
2020-10-25 15:01:34 DEBUG (MainThread) [websockets.protocol] client > Frame(fin=True, opcode=9, data=b"\xb2\xb4'2", rsv1=False, rsv2=False, rsv3=False)
2020-10-25 15:01:34 DEBUG (MainThread) [websockets.protocol] client - event = data_received(<6 bytes>)
2020-10-25 15:01:34 DEBUG (MainThread) [websockets.protocol] client < Frame(fin=True, opcode=10, data=b"\xb2\xb4'2", rsv1=False, rsv2=False, rsv3=False)
2020-10-25 15:01:34 DEBUG (MainThread) [websockets.protocol] client - received solicited pong: b2b42732
2020-10-25 15:01:34 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/hassio_ingress/HYk3-O1h-2AGhcYTlX0UsILYIZi3ad5QLYWpT9nd8Rk/getstatus to 172.30.33.4 (auth: False)/usr/local/lib/python3.8/site-packages/aiohttp/connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
2020-10-25 15:01:34 DEBUG (MainThread) [homeassistant.components.http.view] Serving /api/hassio_ingress/HYk3-O1h-2AGhcYTlX0UsILYIZi3ad5QLYWpT9nd8Rk/getstatus to 172.30.33.4 (auth: False)
2020-10-25 15:01:34 DEBUG (SyncWorker_8) [homeassistant.components.nmap_tracker.device_tracker] nmap scan successful
2020-10-25 15:01:34 DEBUG (SyncWorker_8) [homeassistant.components.nmap_tracker.device_tracker] Nmap last results []
2020-10-25 15:01:35 DEBUG (MainThread) [websockets.protocol] client > Frame(fin=True, opcode=9, data=b'\x80N\x92t', rsv1=False, rsv2=False, rsv3=False)
2020-10-25 15:01:35 DEBUG (MainThread) [websockets.protocol] client - event = data_received(<6 bytes>)
2020-10-25 15:01:35 DEBUG (MainThread) [websockets.protocol] client < Frame(fin=True, opcode=10, data=b'\x80N\x92t', rsv1=False, rsv2=False, rsv3=False)
2020-10-25 15:01:35 DEBUG (MainThread) [websockets.protocol] client - received solicited pong: 804e9274
2020-10-25 15:01:35 DEBUG (MainThread) [websockets.protocol] client > Frame(fin=True, opcode=9, data=b'Ob\xe2\x00', rsv1=False, rsv2=False, rsv3=False)
2020-10-25 15:01:35 DEBUG (MainThread) [websockets.protocol] client - event = data_received(<6 bytes>)
2020-10-25 15:01:35 DEBUG (MainThread) [websockets.protocol] client < Frame(fin=True, opcode=10, data=b'Ob\xe2\x00', rsv1=False, rsv2=False, rsv3=False)
2020-10-25 15:01:35 DEBUG (MainThread) [websockets.protocol] client - received solicited pong: 4f62e200
2020-10-25 15:01:35 DEBUG (MainThread) [homeassistant.components.hue.light] Finished fetching light data in 0.078 seconds

 ```

**Comment by circa1665** [comment] 2020-10-27 23:57
I'm having similar issues having checked, last successfully synched in May!

**Comment by sabeechen** [comment] 2020-10-29 15:18
This is certainly another instance of #226. You'll see this if you are both:

  * Using the 32-bit arm verison of Home Assistant (you are)
  * Have a snapshot over 2GB in size (you do)

It is caused by a bug in the supervisor. You can verify this is the case by going to the supervisor's own snapshots page (Supervisor > Snapshots) and trying to download the large snapshot, which will fail. I've filed [an issue](https://github.com/home-assistant/supervisor/issues/2047) and they think they've resolved it, and will be released as a supervisor update within a week.
If you want to fix it faster, the only workarounds until the fix is released are:

 * Install and run the 64 bit version of Home Assistant (Admittedly I don't know why the 32 bit versions are recommended).
 * Keep the snapshot below 2GB. Usually large snapshots are from storing the database or camera images, and usually the snapshot can do without them.

I'll update #266 when I have any new information on the issue.

Duplicate #226

**Closed by sabeechen** 2020-10-29 15:18 UTC

**Comment by circa1665** [comment] 2020-10-29 15:24
Thanks for your response but I use HassOS on an intel-nuc. So definitely not on arm and my snapshots are less 500mb.

**Comment by sabeechen** [comment] 2020-10-29 15:29
Ah, I hadn't noticed your logs are different.  I've opened #296 for you since it doesn't have anything to do with the original poster's issue.

**Comment by circa1665** [comment] 2020-10-29 16:03
My bad! Thank you 👍
